"""Gemeinsame Prioritäten für Prompt- und Routing-Generatoren."""

from __future__ import annotations


PLUGIN_PRIORITY_SKILLS: dict[str, list[str]] = {
    "vergabestelle-behoerden": [
        "vergabe-os-master-orchestrator",
        "workflow-kaltstart-und-routing",
        "einstieg-routing",
        "workflow-fristen-und-risikoampel",
        "dokumente-intake",
        "quellen-livecheck",
        "vergaberecht-tatbestand-beweis-und-belege",
        "schwellenwerte-2026-2027-livecheck",
        "03-schwellenwert-pruefung",
        "bundeswehrbeschaffung-bwbbg-2026",
        "verfahrenswahl-kompass",
        "04-verfahrensart-waehlen",
        "wirklichkeitsdaten-beschaffung-steuern",
        "bestangebot-durchsetzen",
        "netto-null-technologien-vergabe",
        "10-zuschlagsmatrix-aufbauen",
        "06-eignungs-und-zuschlagskriterien",
        "zuschlagskriterien-paragraf-127-gwb",
        "wertungspreisqualitaet-matrix",
        "17-wertung-leistung-preis",
        "18-wertungsvermerk-erstellen",
        "markterkundung-und-vorbefassung",
        "losbildung-mittelstandsfoerderung",
        "legacy-systeme-integration",
        "07-vergabeunterlagen-erstellen",
        "vergabeunterlagen-lv-datenformate-bereitstellen",
        "eforms-ted-bekanntmachung-check",
        "05-bekanntmachung-erstellen",
        "bekanntmachung-berichtigung-und-upload-routing",
        "25-vergabevermerk-paragraf-8-vgv",
        "vergabeakte-dokumentationsvermerk-builder",
        "bieterfragen-antworten-management",
        "12-ausschlussgruende-pruefen",
        "wettbewerbsregister-abfrage-selbstreinigung",
        "29-ev-vorabinformation-frist",
        "vorinformation-134-gwb-stillhaltefrist",
        "22-ruegeerwiderung",
        "23-stellungnahme-vergabekammer",
        "26-akteneinsicht-vergabekammer",
        "24-vorlage-an-den-vergabesenat",
        "aufklaerung-nachforderung-56-vgv",
        "vertragsaenderung-132-gwb-change-control",
        "insolvenz-und-132-gwb-auftragnehmerwechsel",
        "vergabe-behoerden-gericht-und-registerweg",
        "uvgo-unterschwellenvergabe",
        "sektorenvergabe-sektvo",
        "konzessionsvergabe-konzvgv",
        "vob-a-bauvergabe",
        "foerdermittelvergabe-rueckforderung",
        "ki-beschaffung-ai-act-daten-cloud",
        "nachhaltigkeit-tariftreue-lksg-cbam",
    ],
    "bieter-unternehmen": [
        "vergabe-os-master-orchestrator",
        "workflow-kaltstart-und-routing",
        "einstieg-routing",
        "bieter-dashboard-canvas",
        "dokumente-intake",
        "unterlagen-luecken",
        "workflow-unterlagen-lueckenliste",
        "unterlagen-und-lv-datenformate-auslesen",
        "bundeswehrbeschaffung-bwbbg-2026",
        "legacy-systeme-integration",
        "angebot-in-vorgegebenem-format-erstellen",
        "qualitaetsvorsprung-nachweisen",
        "netto-null-technologien-vergabe",
        "13-konzeptionelle-anlagen",
        "eignung-referenzen-umsatz-nachunternehmer",
        "08-bietergemeinschaft-bildung",
        "17-bietergemeinschaftserklaerung",
        "09-angebotskalkulation-stueckpreise",
        "10-leistungsverzeichnis-bepreisen",
        "schriftsatzkern-substantiierung",
        "21-ruegeschreiben-erstellen",
        "ruege-vor-zuschlag",
        "ruegeschriftsatz-erstellen",
        "bieterfragen-antworten-management",
        "angebotsoeffnung-formfehler-preisblatt",
        "schnittstelle-zahlen-schwellen-und-berechnung",
        "schwellenwerte-2026-2027-livecheck",
        "03-go-no-go-entscheidung",
        "16-frist-und-zustellung-pruefen",
        "18-aufklaerung-niedriges-angebot-paragraf-60",
        "eignungspruefung",
        "ausschluss-bieter-paragraf-124-gwb",
        "28-selbstreinigung-nach-ausschluss-paragraf-125",
        "nachpruefungsantrag-powerdraft",
        "nachpruefungsantrag-vk",
        "nachpruefungsverfahren-vk",
        "vergabekammer-termin-simulation",
        "vergabekammer-verhandlung-vergleich-und-eskalation",
        "vergleichsverhandlung-strategie",
        "verg-mehrparteien-konflikt-und-interessen",
        "insolvenz-und-132-gwb-auftragnehmerwechsel",
        "27-vertragsanpassung-paragraf-132-gwb",
        "de-facto-vergabe-135-gwb-fristen",
        "de-facto-vergabe-klage",
        "uvgo-fristen-form-und-zustaendigkeit",
        "sektvo-dokumentenmatrix-und-lueckenliste",
        "konzvgv-risikoampel-und-gegenargumente",
        "wettbewerbsregister-abfrage-selbstreinigung",
        "vergabesperre-korruption-selbstreinigung",
    ],
    "konkurrenten-rechtsschutz": [
        "konkurrenzrechtsschutz-orchestrator",
        "startbildschirm-konkurrentenangriff",
        "bundeswehrbeschaffung-bwbbg-2026",
        "ruege-konkurrent-160-gwb",
        "nachpruefungsantrag-konkurrent-vk",
        "eilantrag-zuschlagssperre-169",
        "wertungsangriff-und-dokumentationsluecken",
        "billigzuschlag-angreifen",
        "produktneutralitaet-und-leistungsbeschreibung",
        "netto-null-technologien-vergabe",
        "eignungs-und-ausschlussangriff-konkurrent",
        "akteneinsicht-schwaerzung-belegmatrix",
        "beweisstrategie-und-portalnachweise",
        "legacy-systeme-integration",
        "de-facto-vergabe-135-gwb",
        "unterlagen-lv-formatangriff",
        "bekanntmachung-fristen-und-zugang",
        "vergleich-und-abstellungsstrategie",
        "kosten-und-schadensersatzrisiko",
        "sofortige-beschwerde-olg-vergabesenat",
    ],
}


MEGAPROMPT_MODULE_LIMITS: dict[str, int | None] = {
    "vergabestelle-behoerden": 21,
    "bieter-unternehmen": 21,
    "konkurrenten-rechtsschutz": None,
}


MINI_SKILL_SUMMARIES: dict[str, str] = {
    "workflow-kaltstart-und-routing": "Ein einzelnes Dokument oder eine konkrete Frage schnell einordnen: Rolle, Stand, rote Frist, Rechtsregime, Fundstelle, Output-Weiche und nächstes Spezialmodul. Vollständige Ordner und ZIP-Pakete gehen an den Master-Orchestrator.",
    "konkurrenzrechtsschutz-orchestrator": "Vollständigen Konkurrentenfall aus Ordner, ZIP, Portal- oder Aktenexport ohne Skillwahl triagieren: Fristen, Herkunft, Beweiskette, Angriff, Kausalität, Zuschlagschance und erster Antrag.",
    "startbildschirm-konkurrentenangriff": "Nach abgeschlossener Triage Fristen, stärksten Angriff, Belege, Aktenlücken, Antrag und nächste Handlung als kompaktes Streitdashboard darstellen; kein eigener Akten-Kaltstart.",
    "quellen-livecheck": "Tragende Normen, Schwellenwerte, Rechtsprechung und Landesrecht nur mit aktueller amtlicher oder frei prüfbarer Quelle verwenden und Unsicherheiten markieren.",
    "03-schwellenwert-pruefung": "Auftragswert, Lose, Optionen, Laufzeit und Auftraggebertyp gegen EU-Schwellenwerte und Wertgrenzen prüfen; daraus Regime, Rechtsweg und Vermerk ableiten.",
    "04-verfahrensart-waehlen": "Offenes, nichtoffenes, Verhandlungsverfahren, Dialog, Innovationspartnerschaft, UVgO oder Direktauftrag aus Bedarf, Markt, Schwelle und Ausnahmegrund begründen.",
    "markterkundung-und-vorbefassung": "Markt vor Veröffentlichung klären: Anbieterfeld, technische Lösung, Vorbefassung, Ausgleichsmaßnahme, Gleichbehandlung und Aktenvermerk.",
    "losbildung-mittelstandsfoerderung": "Fach- und Teillose, Gesamtvergabe, Bündelung, Mittelstandsschutz, Skaleneffekt, Anbieterfeld und Rügefestigkeit begründen.",
    "wirklichkeitsdaten-beschaffung-steuern": "Bauwerk, PMS/BMS, Planung, BIM, Kosten, Nachträge, Klima, Normen und Recht mit Feldautorität und Entscheidungsbrücke verbinden; daraus Priorisierung, LV, Kriterien, Budget, Szenario und Aktenvermerk bauen.",
    "bestangebot-durchsetzen": "Bestes Preis-Leistungs-Verhältnis statt billigsten Reflex sichern: Qualität, Tempo, Servicelevel, Betriebssicherheit, Nachhaltigkeit und Lebenszykluskosten in Matrix, Formeltest und Vergabevermerk verankern.",
    "netto-null-technologien-vergabe": "Artikel 25 der Verordnung EU 2024/1735 und Verordnung EU 2026/718 rollenfest anwenden: Richtlinien- und Technologiegate, Windrotorblatt-Rezyklierbarkeit, Bau-Zusatzpflichten, Resilienz, GPA, Ausnahme, Nachweis und Rechtsfolge.",
    "bundeswehrbeschaffung-bwbbg-2026": "Bundeswehr-, Verteidigungs- und Sicherheitsbeschaffungen nach dem seit 14. Februar 2026 geltenden BwBBG rollenfest bearbeiten: Anwendungsbereich, Übergang, Sonderroute, Drittstaaten, Vorab-Rüge, VK Bund, OLG, Sanktion und Vertragsänderung.",
    "10-zuschlagsmatrix-aufbauen": "Vergabestelle baut die Zuschlagsmatrix so, dass Preis, Qualität, Tempo, Personal, Servicelevel und Lebenszykluskosten echte Punkte auslösen und nicht vom Preis überrollt werden.",
    "06-eignungs-und-zuschlagskriterien": "Vergabestelle trennt Eignung und Zuschlag, formuliert auftragsbezogene Kriterien und macht Qualitäts-, Tempo- und Lebenszyklusvorteile transparent bewertbar.",
    "zuschlagskriterien-paragraf-127-gwb": "Paragraf 127 GWB und Paragraf 58 VgV als Bestwertungsanker: wirtschaftlichstes Angebot, Auftragsbezug, Bewertungsmaßstab, Transparenz und Rügefestigkeit.",
    "wertungspreisqualitaet-matrix": "Preis-Qualitäts-Matrix, Gewichtung und Preisformel testen: verhindert Scheinqualität, Preisautomatismus und mathematische Entwertung eines besseren Angebots.",
    "17-wertung-leistung-preis": "Angebote entlang der Matrix werten: Preis, Qualität, Tempo, Konzept, Lebenszykluskosten und Dokumentation trennen, Punkte vergeben und Fehlerverdacht markieren.",
    "18-wertungsvermerk-erstellen": "Wertungsentscheidung so dokumentieren, dass Bestangebot, Aufklärung, Ausschluss, Preisformel, Qualitätswertung und Zuschlagsbegründung vor VK/OLG halten.",
    "legacy-systeme-integration": "Systemexporte rollenspezifisch verarbeiten: Behörden erhalten Feldautorität und Entscheidungsbrücke, Bieter Angebotsfreeze und Quittungsabgleich, Konkurrenten Herkunftszone und Beweiskette; jeweils mit Hash, Transformation, Freigabe und Rückkanal.",
    "vergabeunterlagen-lv-datenformate-bereitstellen": "LV und Unterlagen aus GAEB, XML, Excel, PDF oder Fachsystemen bereitstellen, Pflichtfelder prüfen und Upload- oder Bekanntmachungspaket vorbereiten.",
    "bekanntmachung-berichtigung-und-upload-routing": "Berichtigung, Fristverlängerung, eForms, TED, DVAL und Plattformupload mit Feldliste, Freigabe, Hash, Quittung und Vergabeaktenvermerk steuern.",
    "qualitaetsvorsprung-nachweisen": "Bieter zeigt, warum sein Angebot trotz höherem Preis besser ist: Qualität, Tempo, Personal, Servicelevel, Betriebssicherheit, Lebenszyklusvorteile und Nachweise.",
    "eignung-referenzen-umsatz-nachunternehmer": "Eignungspaket des Bieters bauen: Referenzen, Umsatz, Personal, Nachunternehmer, Eignungsleihe, Nachweise und Angriffsflächen vor Abgabe prüfen.",
    "08-bietergemeinschaft-bildung": "Bietergemeinschaft bilden: Mitglieder, Federführer, Haftung, ESPD je Mitglied, Steuer-/Sozialabgabencheck und Krisenpfad bei problematischem Mitglied.",
    "17-bietergemeinschaftserklaerung": "Bietergemeinschaftserklärung abgabereif machen: Vollmacht, Haftung, Mitglieder, Compliance-Bestätigung, Austauschpfad und Unterschriften.",
    "unterlagen-und-lv-datenformate-auslesen": "Bekanntmachung, Unterlagen, LV, GAEB, XML, Excel und PDF auslesen, Angebotslücken markieren und daraus Preisblatt-, Nachweis- und Rügeroute bilden.",
    "angebot-in-vorgegebenem-format-erstellen": "Angebot exakt im geforderten Format liefern: XML, GAEB, Excel, PDF, Portalformular, Anlagenstruktur, Signatur, Hash, Freigabe und Uploadnachweis.",
    "bieter-dashboard-canvas": "Komplexe Bieterakte als Dashboard ordnen: Rollen, Fristen, Dokumente, Rügepunkte, Bewertungsfehler, Rechtsweg, Risiken, Aufgaben und offene Fragen.",
    "21-ruegeschreiben-erstellen": "Rüge vor Präklusion erstellen: Fehler, Norm, Kenntnis, Frist, Kausalität, Abhilfeziel, Anlagen und Portalzustellung sauber trennen.",
    "ruege-vor-zuschlag": "Bieter rügt vor Zuschlag: erkannter Fehler, Präklusion, Frist, Abhilfeziel, Portalzustellung, Nichtabhilfe und VK-Reserve in einem Arbeitsgang.",
    "ruegeschriftsatz-erstellen": "Rügeschriftsatz mit Norm, Tatsache, Beleg, Kausalität und konkreter Abhilfe formulieren; keine pauschalen Beanstandungen, sondern antragsfähige Fehlerlinie.",
    "bieterfragen-antworten-management": "Vor der Rüge klären: Bieterfrage, Antwortlog, Fristverlängerung, Portalbeleg, Folgefrage und Umschaltpunkt zur Rüge.",
    "ausschluss-bieter-paragraf-124-gwb": "Bieter verteidigt sich gegen fakultativen Ausschluss: Schlechtleistung, Interessenkonflikt, Integrität, Verhältnismäßigkeit, Selbstreinigung und Belege.",
    "28-selbstreinigung-nach-ausschluss-paragraf-125": "Selbstreinigungsdossier nach Paragraf 125 GWB bauen: Schadensausgleich, Aufklärung, Compliance-Maßnahmen, Belege und Wiederzulassung.",
    "de-facto-vergabe-135-gwb-fristen": "Direktauftrag, fehlende Bekanntmachung, Interimsauftrag oder laufende Leistung prüfen: qualifizierte Information oder EU-Bekanntmachung, 30 Kalendertage, Sechsmonatsgrenze, Ex-ante-Wartezeit, VK-Antrag und Belege.",
    "nachpruefungsantrag-vk": "Nachprüfungsantrag an die Vergabekammer: Zulässigkeit, Antragsbefugnis, Rügeobliegenheit, Sachanträge, Akteneinsicht, Zuschlagssperre und Belege.",
    "vergabekammer-verhandlung-vergleich-und-eskalation": "VK-Verhandlung aus Bietersicht vorbereiten: Hinweise der Kammer, Vergleichsfenster, Beweislinie, Antragstaktik, Eskalation und OLG-Reserve.",
    "billigzuschlag-angreifen": "Konkurrent greift Preisautomatismus an: Dumpingpreis, ungewöhnlich niedriges Angebot, ignorierter Qualitätsvorsprung, verzerrte Formel, Scheinqualität und Aufklärungslücken.",
    "produktneutralitaet-und-leistungsbeschreibung": "Hersteller-, Typ-, Material-, System- oder Schnittstellenvorgabe angreifen; Gleichwertigkeit, technische Spezifikation und verdeckte Produktauswahl belegen.",
    "eignungs-und-ausschlussangriff-konkurrent": "Eignung oder Ausschluss des Zuschlagsprätendenten angreifen: Referenzen, Umsatz, Steuern, Sozialabgaben, Selbstreinigung, Register und Nachweise.",
    "bekanntmachung-fristen-und-zugang": "Bekanntmachung, eForms/TED, Landesportal, Zugang zu Unterlagen, Friststart, Berichtigung und Fristverlängerung aus Konkurrentensicht prüfen.",
    "unterlagen-lv-formatangriff": "Unterlagen, LV, GAEB, XML, Excel, PDF und Portalvorgaben angreifen: Mindestanforderungen, Widersprüche, Formatfehler, Lesbarkeit und Abgabevorgaben.",
    "kosten-und-schadensersatzrisiko": "Gebühren, Streitwert, Vorschuss, Kostenerstattung, anwaltliche Vertretung, Schadensersatz und Vergleichskosten vor Eskalation bewerten.",
    "beweisstrategie-und-portalnachweise": "Uploadquittungen, Portalnachrichten, Zeitstempel, Hashes, Dateiversionen, Screenshots und Zustellnachweise in eine gerichtsfeste Belegmatrix bringen.",
    "eilantrag-zuschlagssperre-169": "Zuschlag heute oder morgen stoppen: Paragraf 134 GWB-Schreiben, Stillhaltefrist, VK-Eingang, Zuschlagssperre, Gestattungsantrag und Eilbegründung.",
    "de-facto-vergabe-135-gwb": "Ohne Ausschreibung, Direktauftrag, Interimsauftrag, Vertrag schon unterschrieben, Leistung läuft oder Nachtrag: Unwirksamkeit, Frist und Ausnahme prüfen.",
}


PLUGIN_TRIGGER_ROUTES: dict[str, list[tuple[str, str]]] = {
    "vergabestelle-behoerden": [
        ("Kaltstart, Aktenordner, ZIP, unklarer Stand", "vergabe-os-master-orchestrator"),
        ("rote Frist, Rüge, § 134 GWB, VK oder OLG", "workflow-fristen-und-risikoampel"),
        ("Bekanntmachung, eForms, TED, DVAL oder Portalveröffentlichung", "eforms-ted-bekanntmachung-check"),
        ("Bestangebot statt billigstes Angebot", "bestangebot-durchsetzen"),
        ("Netto-Null, Rotorblatt, Recyclingquote, Resilienz", "netto-null-technologien-vergabe"),
        ("Bundeswehr, Verteidigung, Sicherheit, VSVgV oder BwBBG", "bundeswehrbeschaffung-bwbbg-2026"),
        ("Zuschlagsmatrix, Qualität, Tempo, Servicelevel oder Lebenszykluskosten", "10-zuschlagsmatrix-aufbauen"),
        ("Wirklichkeitsdaten: Bauwerk, PMS/BMS, BIM, Kosten, Klima oder Recht", "wirklichkeitsdaten-beschaffung-steuern"),
        ("Legacy: SAP/ERP/AVA/DMS/API/MCP, Feldautorität oder Rückschreiben", "legacy-systeme-integration"),
        ("LV, GAEB, XML, Excel, PDF oder Uploadpaket bereitstellen", "vergabeunterlagen-lv-datenformate-bereitstellen"),
        ("Ausschluss, Register, Selbstreinigung, Steuer oder Sozialabgaben", "wettbewerbsregister-abfrage-selbstreinigung"),
        ("BTTG, Tariftreue, Nachunternehmerlohn oder Vertragsklausel", "nachhaltigkeit-tariftreue-lksg-cbam"),
        ("Rügeerwiderung, VK-Stellungnahme, Akteneinsicht oder OLG-Erwiderung", "23-stellungnahme-vergabekammer"),
    ],
    "bieter-unternehmen": [
        ("Kaltstart, Unterlagenpaket, Portalexport oder unklare Rolle", "vergabe-os-master-orchestrator"),
        ("Komplexe Bieterakte mit Fristen, Belegen und mehreren Risiken", "bieter-dashboard-canvas"),
        ("Bekanntmachung, Unterlagen, LV, GAEB, XML, Excel oder PDF auslesen", "unterlagen-und-lv-datenformate-auslesen"),
        ("Angebotsformat, Systemdaten oder Angebotsfreeze", "angebot-in-vorgegebenem-format-erstellen"),
        ("Legacy: SAP/ERP/CRM/HR/AVA/DMS/API/MCP oder Datenmapping", "legacy-systeme-integration"),
        ("nicht niedrigster Preis, aber bestes Angebot", "qualitaetsvorsprung-nachweisen"),
        ("Netto-Null, Windrotorblatt, Rezyklierbarkeit oder Herkunftsquote", "netto-null-technologien-vergabe"),
        ("Bundeswehr, Verteidigung, Sicherheit, VSVgV oder BwBBG", "bundeswehrbeschaffung-bwbbg-2026"),
        ("Bieterfrage, unklare Unterlage oder Fristverlängerung vor Rüge", "bieterfragen-antworten-management"),
        ("Rüge, Präklusion, § 160 GWB oder Vergabefehler", "21-ruegeschreiben-erstellen"),
        ("Nichtabhilfe, VK-Antrag oder Zuschlag stoppen", "nachpruefungsantrag-powerdraft"),
        ("laufendes VK-Verfahren, Termin, Vergleich oder OLG-Reserve", "vergabekammer-verhandlung-vergleich-und-eskalation"),
        ("Ausschluss, Eignung, Nachforderung oder Selbstreinigung", "eignungspruefung"),
        ("BTTG, Tariftreue, Lohnkalkulation oder Nachunternehmer", "09-angebotskalkulation-stueckpreise"),
        ("Bietergemeinschaft, problematisches Mitglied oder C-268/25", "08-bietergemeinschaft-bildung"),
    ],
    "konkurrenten-rechtsschutz": [
        ("Kaltstart: Ordner, ZIP, § 134-Schreiben oder unklare Akte", "konkurrenzrechtsschutz-orchestrator"),
        ("Triage steht; Streitdashboard oder Startbildschirm erstellen", "startbildschirm-konkurrentenangriff"),
        ("Billigzuschlag, Nur-Preis-Wertung, Unterpreis oder Dumping", "billigzuschlag-angreifen"),
        ("Qualitätswertung, Tempo, Lieferzeit oder neue Wertung", "wertungsangriff-und-dokumentationsluecken"),
        ("Produkt-, Hersteller-, Material-, System- oder Schnittstellenvorgabe", "produktneutralitaet-und-leistungsbeschreibung"),
        ("Netto-Null: Windblatt, Quote, GPA", "netto-null-technologien-vergabe"),
        ("Bundeswehr, Verteidigung, Sicherheit, VSVgV oder BwBBG", "bundeswehrbeschaffung-bwbbg-2026"),
        ("Rüge, Präklusion, Kenntnis oder Abhilfeverlangen", "ruege-konkurrent-160-gwb"),
        ("VK-Antrag, Zuschlagssperre oder drohender Zuschlag", "eilantrag-zuschlagssperre-169"),
        ("Portalnachricht, Uploadquittung, Zeitstempel, Hash oder Screenshot", "beweisstrategie-und-portalnachweise"),
        ("Portal/TED/eForms, GAEB, DMS, API, MCP oder eigener Export", "legacy-systeme-integration"),
        ("Direktauftrag, fehlende Bekanntmachung oder Interimsauftrag", "de-facto-vergabe-135-gwb"),
        ("BTTG, Tariftreueausschluss oder bestandskräftige Feststellung", "eignungs-und-ausschlussangriff-konkurrent"),
        ("Kosten, Gebühren, Streitwert, Vorschuss, Unterliegen oder Vergleich", "kosten-und-schadensersatzrisiko"),
    ],
}
