"""Vergabe, Ausführung, Vermietung und Objektbetreuung des Wohnhauses. Autor: Klotzkette."""
from __future__ import annotations
import csv
import re
import textwrap
from PIL import Image, ImageDraw, PngImagePlugin
from akten_build_runtime import screen_font
from pathlib import Path
from bauwirtschaft_hildesheim_common import CASE, ACTORS, build_records, euro, REF

ACTORS['konkurrenz'] = ('Massivbogen Bau GmbH','Baustraße 28, 31137 Hildesheim','angebot@massivbogen.example','Holger Kern, Geschäftsführer')
LOTS = [
 ('rohbau','Erdarbeiten und Rohbau',650000,[
 ('Baustelleneinrichtung',40000,'Bauzaun mit abschließbarem Zugang, Sanitärcontainer, Baustrom-Unterverteilung, Baustellenbeleuchtung und Kran einschließlich Aufbau, Betrieb und Rückbau für den Rohbau. Der öffentliche Gehweg bleibt frei. Der von der Bauherrin beauftragte SiGe-Koordinator erhält Zugang.'),
 ('Erdarbeiten und Gründungsvorbereitung',90000,'Aushub für Bodenplatte, Leitungsgräben und Aufzugunterfahrt innerhalb des freigegebenen Baufeldes, getrennte Bodenlagerung, Abfuhr überschüssigen unbelasteten Bodens und Verdichtungskontrollen. Grundlage ist der Baugrundbericht. Abweichende wasserführende Schichten sind vor weiterer Bearbeitung zu dokumentieren.'),
 ('Beton und tragendes Mauerwerk',360000,'Bodenplatte, Stützen, drei Geschosse mit tragenden Wänden und Geschossdecken sowie Treppenläufe nach freigegebener Schal- und Bewehrungsplanung. Gebäude EG und 1. OG 20,00 mal 15,00 m, oberstes Geschoss 20,00 mal 11,00 m, ohne Keller. Einbauteile, Aussparungen und Aufzugschacht sind mit den Fachplänen abzugleichen.'),
 ('Rohbaunebenarbeiten',160000,'Nichttragende Rohbauwände, Anschlüsse, Gerüste für den eigenen Leistungsumfang, Treppenpodeste, Durchbruchschließungen und geplanter Sockelrohbau. Die Gebäudehülle und der Innenausbau werden gesondert ausgeführt. Vor dem Betonieren erfolgt ein gemeinsamer Abgleich der Durchführungen.')]),
 ('huelle','Dach Fassade und Fenster',440000,[
 ('Dachabdichtung und Dämmung',130000,'Abdichtung beider Flachdachebenen mit insgesamt 300 m² Dachgrundfläche nach Detailplanung, Gefälledämmung, Attikaanschlüsse, Haupt- und Notentwässerung. Die Unterkonstruktion der PV-Anlage wird mit Los Elektro abgestimmt. Befestigungen dürfen die Dachabdichtung nicht unkontrolliert durchdringen.'),
 ('Fassade und Sockel',130000,'Vollständiges Dämm- und Putzsystem für die planmäßig dargestellten Außenwände einschließlich Laibungen, Brandriegeln nach Fachplanung, Sockelanschlüssen und Gerüst. Bauteilanschlüsse werden vor dem Verdecken fotografisch und im Prüfprotokoll dokumentiert.'),
 ('Fenster und Außentüren',140000,'Sämtliche Fenster und Außentüren des Achtfamilienhauses nach Fensterliste, einschließlich Montage, dreistufigem Anschluss, Außenfensterbänken und erforderlichen Sicherheitsverglasungen. Schwellenlose Zugänge der acht Wohnungen und Rettungsöffnungen sind nach freigegebenen Detailmaßen auszuführen.'),
 ('Sonnenschutz und Anschlussprüfung',40000,'Außenliegender Sonnenschutz an den dafür vorgesehenen Wohnraumfenstern, Funktionsprüfung, Einstellung der Beschläge sowie Luftdichtheits- und Anschlusskontrollen mit den zuständigen Fachleuten. Elektrische Zuleitungen kommen aus Los Elektro.')]),
 ('hls','Heizung Lüftung und Sanitär',360000,[
 ('Wärmeerzeugung und Verteilung',140000,'Zwei Luft-Wasser-Wärmepumpen mit je 18 kW nominaler Leistung, Speicher, Pumpen und Regelung nach TGA-Planung. Leistungsangaben ersetzen nicht die raumweise Heizlastberechnung. Hydraulischer Abgleich, dokumentierte Einstellwerte und Einweisung sind eingeschlossen.'),
 ('Sanitäre Anlagen',125000,'Trinkwasser- und Abwasserinstallation für acht Wohnungen sowie Hausanschluss- und Technikbereich. Vollständige Bäder nach freigegebenen Ausstattungslisten, insbesondere rollstuhlgerechte Ausstattung der Wohnung 01. Druck-, Dichtheits- und Spülprotokolle werden vor Abnahme übergeben.'),
 ('Lüftung und Schallschutz',65000,'Wohnungslüftung, erforderliche Abluftführung, Schalldämpfung und Kondensatableitung nach abgestimmter TGA-Planung. Einregulierung jeder Wohnung und Messprotokoll für die vorgesehenen Betriebsstufen. Brandschutzdurchführungen werden zugelassen und gekennzeichnet ausgeführt.'),
 ('Zähler und Inbetriebnahme',30000,'Acht Wohnungswärmezähler sowie die vereinbarten Wasserzähler, Kennzeichnung, Anlagenbuch, Prüfungen und gemeinsame Inbetriebnahme. Die Mietverwaltung erhält die Zählerzuordnung und die Bedienunterlagen. Ein Wartungsvertrag ist gesondert zu schließen.')]),
 ('elektro','Elektrotechnik Photovoltaik und Ladeinfrastruktur',150000,[
 ('Elektroinstallation',65000,'Zählerschrank, Hauptverteilung, acht Wohnungsverteilungen, Stromkreise, Steckdosen, Lichtauslässe, Potentialausgleich und Schutzmaßnahmen nach Fachplanung. Mess- und Prüfprotokolle jeder Verteilung sowie Stromlaufpläne gehören zur Übergabe.'),
 ('Kommunikation und Allgemeinstrom',20000,'Türkommunikation, Glasfaser-Leerrohre, Allgemeinbeleuchtung, Aufzugzuleitung und technische Stromkreise. Wohnungsstromverträge schließen die Mietparteien selbst. Die PV-Anlage versorgt vereinbarungsgemäß den Allgemeinstromkreis.'),
 ('Ladeinfrastruktur',20000,'Vollständige Vorverkabelung aller acht Pkw-Stellplätze und zwei Ladepunkte mit Lastmanagement, davon einer am barrierefreien Stellplatz. Leitungswege, Leistungsschutz und mögliche Erweiterung werden dokumentiert. Die Netzabstimmung ist im Angebot enthalten.'),
 ('Photovoltaik',45000,'PV-Anlage mit 80 Modulen zu je 450 Wp und insgesamt 36 kWp auf dem Wohnhaus, Wechselrichter, Leitungen und Montage. Modulfläche insgesamt 160 m². Inbetriebnahme und Messkonzept mit dem Netzbetreiber sind eingeschlossen. Eine Strombelieferung der einzelnen Mietparteien ist nicht Gegenstand dieses Auftrags.')]),
 ('ausbau','Innenausbau und Bodenbeläge',300000,[
 ('Trockenbau und Innenputz',100000,'Nichttragende Ausbaukonstruktionen, Installationsschächte und Oberflächen nach freigegebenem Ausbauplan. Schall- und brandschutzrelevante Konstruktionen werden mit den Fachnachweisen abgestimmt.'),
 ('Estrich und Bodenbeläge',90000,'Estrich einschließlich erforderlicher Trocknungs- und Belegreifemessungen sowie Bodenbeläge in acht Wohnungen und allgemeinen Verkehrsflächen nach Raumliste. Wohnung 07 erhält den im Auftrag benannten Eichenbelag. Ein Ersatzmaterial bedarf vorheriger schriftlicher Zustimmung.'),
 ('Innentüren',55000,'Wohnungseingangs- und Innentüren einschließlich Zargen, Beschlägen und Schließanlage. Erforderliche lichte Durchgänge und Bewegungsflächen dürfen durch Zargen oder Türanschläge nicht vermindert werden.'),
 ('Malerarbeiten und Endreinigung',55000,'Anstriche, Fugenarbeiten im eigenen Gewerk, Schutz und Reinigung bis zur Abnahme. Dauerelastische Fugen werden dokumentiert; Wartungspflichten der späteren Nutzer werden verständlich erläutert.')]),
 ('aufzug','Aufzuganlage',60000,[
 ('Anlage und Montage',45000,'Personenaufzug mit drei Haltestellen, nutzbarer Kabine 1,10 mal 1,40 m und lichter Türbreite 0,90 m nach abgestimmter Planung. Traglast 630 kg. Schacht, Unterfahrt und Überfahrt werden vor Fertigung aufgemessen.'),
 ('Steuerung und Notruf',8000,'Steuerung, automatische Türen, barrierefrei erreichbare Bedienelemente, Zweirichtungs-Kommunikation und Notrufanbindung. Laufende Notruf- und Wartungsentgelte werden in einem gesonderten Betriebsvertrag geregelt.'),
 ('Prüfung und Übergabe',7000,'Erforderliche Prüfung vor Inbetriebnahme durch die zuständige zugelassene Überwachungsstelle organisieren, Befunde beseitigen, Unterlagen und Einweisung übergeben. Die Prüfentscheidung trifft die Prüfstelle selbst.')]),
 ('aussen','Außenanlagen und Entwässerung',120000,[
 ('Wege und Stellplätze',60000,'Stufenlose Hauszugänge, acht Pkw-Stellplätze einschließlich eines gekennzeichneten barrierefreien Stellplatzes, befestigte Fahrradstellplätze und Abfallstandfläche. Gefälle und Anschlusshöhen nach freigegebenem Außenanlagenplan.'),
 ('Entwässerung',30000,'Schmutz- und Regenwasserleitungen bis zu den vereinbarten Übergabepunkten, Rückhaltung und gedrosselte Ableitung nach freigegebener Entwässerungsplanung. Keine Versickerung ohne nachgewiesene Eignung und behördliche Zulässigkeit.'),
 ('Grün und Spielbereich',30000,'Bepflanzung, Rasen, 30 m² Kleinkinderspielbereich mit Einfriedung zum Fahrbereich und Sitzgelegenheit. Fertigstellungspflege bis zur Abnahme und Nachpflegevereinbarung sind eingeschlossen. Geräteunterlagen und Prüfbericht werden übergeben.')]),
]
RECORDS = []
def add(n, name, date, issuer, title, sections, ext='pdf', recipient='bauherr', **extra):
    def normal(value):
        if isinstance(value,str):
            value=re.sub(r'(?<=[a-zäöüß])(?=\d)', ' ', value)
            value = re.sub(r'(?<=\d)(?=[a-zA-ZäöüÄÖÜß])', ' ', value)
            value = re.sub(r'((?:§|Absatz)\s*\d+)\s+([a-z])\b', r'\1\2', value)
            return re.sub(r'§\s*(\d+)', r'§ \1', value)
        return type(value)(normal(x) for x in value) if isinstance(value,(list,tuple)) else value
    sections=normal(sections)
    d=dict(number=n,filename=f'{n:03d}_{name}.{ext}',date=date,issuer=issuer,recipient=recipient,title=normal(title),sections=sections,**extra);RECORDS.append(d);return d

def documents():
    RECORDS.clear()
    add(30,'Vergabeterminplan','2027-10-01','architekt','Vergabetermine und Schnittstellen der sieben Bauaufträge',[
      'Die Ausführungsplanung liegt im freigegebenen Stand vom 24.09.2027 vor. Wir schlagen eine private Einzelvergabe in sieben Losen vor. Die Bauherrin finanziert das Gebäude aus Eigenkapital und Bankdarlehen. Förderbescheide oder besondere vergaberechtliche Verpflichtungen wurden uns nicht vorgelegt. Die Bauherrin entscheidet über jeden Vertrag selbst.',
      ('h','1 Termine und Verantwortliche'),('t',[['Vorgang','Termin','Verantwortlich'],['Versand des vollständigen LV','04.10.2027','Nora Feld'],['Fragen bis / gemeinsame Antwort','18.10. / 22.10.2027','Fachplaner und Architektur'],['Angebotseingang','29.10.2027','Maren Birk'],['Technische und rechnerische Prüfung','01. bis 05.11.2027','Architektur und TGA'],['Verhandlung und Entscheidung','08. bis 10.11.2027','Bauherrin mit Rechtsanwalt'],['Vertragsschluss','12.11.2027','Bauherrin und Unternehmen'],['Einrichtung / Baubeginn','01.12. / 06.12.2027','Steinwerk Hochbau'],['Gemeinsame förmliche Abnahmen','15.09.2028','Bauherrin und Unternehmen']],[180,150,165]),
      ('h','2 Unterlagen und Vollmacht'),'Das Leistungsverzeichnis umfasst die sieben Lose und ihre Schnittstellen. Planstände sind in den Vertragsanlagen bezeichnet. Nachträgliche Bieterantworten werden allen betroffenen Unternehmen im gleichen Wortlaut übermittelt. Frau Feld prüft technische und wirtschaftliche Angaben und erstellt den Vergabevorschlag. Sie erhält keine Abschlussvollmacht. Die rechtliche Vertragsgestaltung erfolgt aufgrund des unmittelbaren Mandats der Bauherrin durch die Kanzlei Leinebogen.',
      'Die Rohbaufirma stellt das Gerüst für ihren eigenen Leistungsumfang. Fassadenarbeiten und dafür benötigte Gerüste verbleiben im Hüllenlos. PV-Befestigung, Dachabdichtung und Leitungsdurchführungen sind vor Ausführung gemeinsam freizugeben. Ein niedriger Angebotspreis ersetzt den Nachweis der vollständigen Leistung und der personellen Verfügbarkeit nicht.'
    ],'docx')
    lv=[('h','1 Projekt und Angebotsgrundlagen'),'Gegenstand ist der schlüssige Ausbau eines Wohnhauses mit acht Mietwohnungen und 600 m² Wohnfläche. Der Auftrag ist in die nachfolgenden Lose geteilt. Jedes Unternehmen bietet sämtliche beschriebenen Leistungen seines Loses an und bezeichnet Abweichungen ausdrücklich in einem gesonderten Begleitschreiben. Das LV ist eine funktional und bauteilbezogen gegliederte Pauschalleistungsbeschreibung. Planmaße und Fachnachweise bleiben verbindlich; die pauschalen Positionen erlauben keine freie Änderung des vereinbarten Qualitätsstandards. Preise werden netto zuzüglich der gesetzlich geschuldeten Umsatzsteuer angeboten.',
      'Zu berücksichtigen sind drei Geschosse, kein Keller, ein Aufzug mit drei Haltestellen, acht barrierefreie Wohnungen einschließlich der rollstuhlgerechten Wohnung 01, die Wärmepumpenanlage und die vereinbarte PV-Anlage. Angrenzende Grundstücke und der öffentliche Gehweg dürfen ohne gesonderte Gestattung nicht als Lagerfläche genutzt werden. Die Ausführung erfolgt nach dem freigegebenen Planregister und den Baugenehmigungsunterlagen.']
    for li,(_,title,_,items) in enumerate(LOTS,2):
        lv.extend([('h',f'{li} {title}')])
        for j,(name,_,scope) in enumerate(items,1):
            lv.extend([('h',f'{li}.{j} {name}'),scope+' Abrechnungseinheit: eine vollständige Pauschalleistung. Die Vergütung ist durch den Bieter einzutragen.'])
    lv.extend([('h','9 Gemeinsame Vertragsvorbereitung'),'Die Angebotsbindung endet am 19.11.2027. Der Ausführungsterminplan ist mit dem Angebot zu bestätigen. Abschläge setzen einen nachvollziehbaren Leistungsstand voraus. Prüfungen, Freigaben und Bedenken sind mit konkretem Plan- und Bauteilbezug zu dokumentieren. Vor Ausführung zusätzlicher Leistungen ist deren Grundlage mit der Bauherrin zu klären; gesetzliche Rechte bleiben unberührt. Eine vom Planer ausgesprochene technische Empfehlung ist kein rechtsgeschäftlicher Zusatzauftrag.'])
    add(31,'Leistungsverzeichnis_sieben_Lose','2027-10-04','architekt','Leistungsverzeichnis für das Achtfamilienhaus',lv,'docx')
    for index,(actor,title,total,items) in enumerate(LOTS):
        n=32 if index==0 else 33+index
        rows=[['Position','Leistung','Pauschale netto EUR']]+[[f'{index+2}.{j}',name,euro(value)] for j,(name,value,_) in enumerate(items,1)]+[['','Summe netto',euro(total)]]
        add(n,'Angebot_'+actor,'2027-10-29',actor,'Angebot für '+title,[
          'Wir bieten die im Leistungsverzeichnis vom 04.10.2027 bezeichneten Leistungen unseres Loses vollständig an. Berücksichtigt sind die Ausführungsunterlagen im Planregister, die gemeinsamen Bieterantworten vom 22.10.2027 und die nachfolgend beschriebenen Abgrenzungen. Das Angebot bleibt bis zum 19.11.2027 bindend. Die vorgesehenen Termine können bei Beauftragung bis zum 12.11.2027 eingehalten werden.',
          ('h','1 Preis und Leistungsumfang'),('t',rows,[45,320,130]),
          ('h','2 Abgrenzung und Umsatzsteuer'),('Die Position Photovoltaik wird bei Vorliegen der gesetzlichen Voraussetzungen mit dem Nullsteuersatz abgerechnet. Für die übrigen Leistungen legen wir 19 Prozent Umsatzsteuer zugrunde. Die Voraussetzungen und die Rechnungsaufteilung werden vor Auftragserteilung mit der Bauherrin dokumentiert.' if actor=='elektro' else 'Die angebotenen Bauleistungen werden mit 19 Prozent Umsatzsteuer abgerechnet. Die Bauherrin hat erklärt, selbst keine nachhaltigen Bauleistungen zu erbringen. Eine Rechnung ohne Steuerausweis wird nicht allein aus ihrer Rechtsform als GmbH abgeleitet.'),
          'Die im LV genannten Leistungen der anderen Lose sind nicht in unserem Preis enthalten. Wir koordinieren eigene Anschlüsse und Durchführungen mit den betroffenen Unternehmen. Fremde Eingriffe werden vor dem Verdecken protokolliert. Etwaige technische Bedenken teilen wir der Bauherrin und der Objektüberwachung schriftlich mit.',
          ('h','3 Personal und Ausführung'),'Für das Projekt steht eine verantwortliche Bauleitung zur Verfügung. Nachunternehmer werden mit Gewerk und Ansprechpartner vor Arbeitsbeginn benannt. Wir liefern prüfbare Abschlagsaufstellungen mit Leistungszeitraum, Baustellenbezug und Leistungsstand. Das Angebot enthält keinen pauschalen Ausschluss der gesetzlichen Mängelrechte und keine Vertragsstrafe.'
        ])
    add(33,'Vergleichsangebot_Rohbau','2027-10-29','konkurrenz','Vergleichsangebot für Erdarbeiten und Rohbau',[
      'Unser Angebot umfasst das Rohbaulos gemäß Leistungsverzeichnis vom 04.10.2027. Die Preise beruhen auf dem vorgesehenen Baugrund und den freigegebenen Planunterlagen. Die im Bodengutachten beschriebenen Erkundungspunkte erfassen keine lückenlose Untersuchung jedes späteren Aushubbereichs. Bei abweichendem Befund unterbrechen wir nur die betroffene Arbeit und informieren die Bauherrin vor einer Mehrleistung.',
      ('t',[['Position','Netto EUR'],['Baustelleneinrichtung','44.000,00'],['Erdarbeiten','94.000,00'],['Beton und tragendes Mauerwerk','376.000,00'],['Rohbaunebenarbeiten','167.000,00'],['Gesamt netto','681.000,00'],['Umsatzsteuer 19 Prozent','129.390,00'],['Gesamt brutto','810.390,00']],[340,155]),
      'Der früheste Baubeginn ist der 17.01.2028. Die Baustelleneinrichtung könnte ab 10.01.2028 erfolgen. Einen Beginn im Dezember 2027 können wir aufgrund bestehender Bindungen nicht zusagen. Die Rohbauübergabe verschiebt sich dementsprechend um sechs Wochen. Unsere Angebotsbindung endet am 19.11.2027.',
      'Die im Leistungsverzeichnis enthaltenen Dokumentations- und Prüfleistungen sind berücksichtigt. Angebote Dritter, Förderbedingungen oder eine nachträgliche Änderung des Ausführungsstandards haben wir nicht eingepreist. Vertragsbedingungen der Bauherrin möchten wir vor einer verbindlichen Auftragsannahme in ihrer vollständigen Fassung prüfen.'
    ])
    add(40,'Vergabevermerk','2027-11-10','architekt','Vergabevorschlag und dokumentierte Entscheidung',[
      'Wir empfehlen die Vergabe der sieben Lose an die in der folgenden Tabelle genannten Unternehmen. Die bauherrenseitige Entscheidung ist am 10.11.2027 im Beisein von Maren Birk, Nora Feld und Rechtsanwalt Dr. Felix Groth protokolliert worden. Die fachliche Angebotsprüfung wurde durch Architektur, Tragwerks- und TGA-Planung jeweils für den eigenen Leistungsbereich ergänzt.',
      ('t',[['Los','Auftragnehmer','Netto EUR']]+[[title,ACTORS[a][0],euro(total)] for a,title,total,_ in LOTS],[175,215,105]),
      'Für das Rohbaulos liegen zwei unmittelbar vergleichbare Angebote vor. Steinwerk ist um 31.000,00 EUR netto günstiger und bestätigt den erforderlichen Dezemberbeginn. Massivbogen nennt den 17.01.2028. Die Bauherrin beauftragt Steinwerk nach Prüfung der Referenzen und der Personalbenennung. Aus der Terminabweichung wird keine vergaberechtliche Ausschlussentscheidung abgeleitet; es handelt sich um eine private Vertragsentscheidung.',
      'Die übrigen Lose wurden nach Marktansprache mit den jeweils beigefügten vollständigen Angeboten verhandelt. Die Entscheidung beruht auf Leistungsumfang, Schnittstellen und Kapazität, nicht auf einer behaupteten öffentlichen Ausschreibung. Eine besondere Bindung aus Fördermitteln liegt nicht vor. Die Hüllenfirma bestätigt das Schnittstellengespräch zu PV-Befestigung und Fensteranschlüssen.',
      'Die angebotenen Nettosummen werden zu den angebotenen Steuersätzen in die Kostenfortschreibung übernommen. Die rechtlichen Vertragsbedingungen werden von der unmittelbar beauftragten Kanzlei freigegeben. Frau Birk unterzeichnet jeden Vertrag selbst. Frau Feld erhält daraus keine Befugnis, Nachträge rechtsgeschäftlich anzunehmen.'
    ],'docx')
    add(41,'Direktmandat_Vertragsgestaltung','2027-11-08','bauherr','Unmittelbares Mandat für die sieben Bauverträge',[
      'Wir beauftragen Ihre Kanzlei unmittelbar mit der rechtlichen Ausgestaltung und Prüfung unserer sieben Bauverträge. Mandantin ist die Steinbogen Wohnen GmbH, vertreten durch mich. Frau Feld liefert die technischen Leistungsbeschreibungen, Planstände und wirtschaftlichen Angebotsergebnisse. Sie soll keine individuellen Rechtsklauseln im eigenen Architektenauftrag für uns entwerfen.',
      'Bitte prüfen Sie die Abgrenzung der Gewerke, die Vergütung einschließlich des unterschiedlichen Steuersatzes für die PV-Leistung, den Änderungsprozess und die Nachweise bei Abschlägen. Die Ausführung soll dem BGB-Bauvertragsrecht unterliegen. Eine pauschale Einbeziehung der VOB/B oder allgemeiner Bedingungen aus Angebotsschreiben ist nicht gewünscht. Für das Rohbaulos bitten wir um eine angemessene Mängelsicherheit nach Abnahme.',
      'Die Freigabe des endgültigen Vertragstextes erfolgt durch unsere Geschäftsführung nach Ihrer Beratung. Den Unternehmen darf der verbindliche Auftrag erst mit unserer Unterschrift erteilt werden. Bitte teilen Sie uns mit, wenn für Ihre rechtliche Prüfung weitere technische oder tatsächliche Angaben erforderlich sind. Fragen zu den Ausführungsdetails richten Sie mit uns in Kopie an Frau Feld.',
    ],'eml',recipient='anwalt')
    for i,(actor,title,total,items) in enumerate(LOTS):
        tax=round((total-45000)*.19,2) if actor=='elektro' else round(total*.19,2)
        add(42+i,'Bauvertrag_'+actor,'2027-11-12','bauherr','Bauvertrag für '+title,[
          f'Die Steinbogen Wohnen GmbH, vertreten durch Maren Birk, als Bestellerin und {ACTORS[actor][0]}, vertreten durch {ACTORS[actor][3]}, als Unternehmer schließen den folgenden Vertrag für das Wohnhaus Wohnhof Am Steinbogen 18 in Hildesheim. Die endgültige Fassung wurde von der unmittelbar durch die Bestellerin beauftragten Kanzlei Leinebogen Rechtsanwälte rechtlich bearbeitet.',
          ('h','1 Gegenstand und Unterlagen'),f'Der Unternehmer schuldet die vollständige und mangelfreie Ausführung des Loses {title}. Vertragsunterlagen sind dieser Vertrag, das Angebot vom 29.10.2027, das Leistungsverzeichnis vom 04.10.2027 mit den Bieterantworten vom 22.10.2027 und das freigegebene Planregister vom 24.09.2027. Widersprüche sind vor der betroffenen Ausführung schriftlich aufzuklären. Eine technische Planfreigabe ersetzt keine Genehmigung und keinen geänderten Vertrag.',
          'Geschuldet sind insbesondere die nachstehend genannten Positionen. Die jeweilige Leistungsbeschreibung des LV einschließlich Schnittstellen und Dokumentation ist Vertragsbestandteil.',
          ('t',[['Position','Pauschale netto EUR']]+[[name,euro(value)] for name,value,_ in items],[365,130]),
          ('h','2 Vergütung und Rechnungen'),f'Die vereinbarte Pauschalvergütung beträgt {euro(total)} EUR netto. Bei den vereinbarten Steuersätzen entfallen {euro(tax)} EUR auf Umsatzsteuer und damit {euro(total+tax)} EUR auf den Gesamtbetrag. Der gesetzlich geschuldete Steuersatz im Zeitpunkt der jeweiligen Leistung bleibt maßgeblich. '+('Die PV-Position von 45.000,00 EUR wird getrennt mit dem Nullsteuersatz ausgewiesen; die Bestellerin bestätigt die Installation auf ihrem Wohnhaus und ihre Stellung als Betreiberin.' if actor=='elektro' else 'Die Parteien gehen für die hier beschriebenen Leistungen von 19 Prozent Umsatzsteuer aus.'),
          'Abschläge werden auf Grundlage nachgewiesener vertragsgemäßer Leistungen mit einer nachvollziehbaren Aufstellung verlangt. Die Bestellerin zahlt berechtigte Abschläge innerhalb von 14 Kalendertagen nach Zugang der prüfbaren Aufstellung. Die Schlusszahlung setzt die vertraglichen und gesetzlichen Voraussetzungen, insbesondere Abnahme und prüffähige Schlussrechnung, voraus. Geleistete Abschläge und die darauf entfallende Umsatzsteuer sind vollständig abzusetzen. Ein Skonto ist nicht vereinbart.',
          ('h','3 Termine und Zusammenarbeit'),'Die Baustelleneinrichtung beginnt am 01.12.2027, der Rohbau am 06.12.2027. Die eigene Ausführung ist mit dem beigefügten Bauzeitenplan abzustimmen. Sämtliche Leistungen müssen bis zum gemeinsamen Abnahmetermin am 15.09.2028 fertiggestellt sein. Der Unternehmer weist auf erkennbare Behinderungen unverzüglich mit Ursache, betroffenen Arbeiten und voraussichtlicher Dauer hin und benennt mögliche Gegenmaßnahmen. Eine Anzeige begründet für sich allein noch keinen Anspruch auf zusätzliche Vergütung oder einen bestimmten neuen Termin.',
          ('h','4 Änderungen und zusätzliche Leistungen'),'Änderungen werden mit konkret bezeichnetem Leistungsinhalt, Auswirkungen auf Termine und einer nachvollziehbaren Preisermittlung vorbereitet. Die Bestellerin entscheidet durch ihre Geschäftsführerin. Die Objektüberwachung darf technische Fragen klären und Angebote bewerten; sie ist nicht zum Abschluss von Nachtragsvereinbarungen bevollmächtigt. Gesetzliche Änderungs- und Anordnungsrechte und die zugehörigen Vergütungsregeln bleiben unberührt. Bei unmittelbar drohenden Schäden sind erforderliche Sicherungsmaßnahmen zu ergreifen und unverzüglich zu dokumentieren.',
          ('h','5 Qualität und Nachweise'),'Der Unternehmer beachtet die vereinbarte Beschaffenheit, die einschlägigen öffentlich-rechtlichen Anforderungen und die anerkannten Regeln der Technik. Er dokumentiert verdeckte Arbeiten vor dem Verschließen, benennt die verwendeten Produkte und übergibt die notwendigen Prüf- und Betriebsunterlagen. Bedenken gegen Vorleistungen, Planunterlagen oder andere Schnittstellen teilt er so rechtzeitig mit, dass die Bestellerin reagieren kann. Die Mitwirkung der Planer entlastet ihn nicht pauschal von eigenen Vertragspflichten.',
          ('h','6 Abnahme und Mängel'),'Die Parteien vereinbaren eine gemeinsame förmliche Abnahme der vertragsgemäß fertiggestellten Leistung. Bekannte Mängel und Vorbehalte werden im Abnahmeprotokoll konkret bezeichnet. Die Rechte bei wesentlichen Mängeln bleiben unberührt. Für Mängelansprüche am Bauwerk gilt die gesetzliche Verjährung von fünf Jahren ab Abnahme, soweit nicht im konkreten Fall zwingende oder längere gesetzliche Regeln eingreifen. Wartungs- und Bedienhinweise sind bei Übergabe gesondert zu erläutern.',
          ('h','7 Sicherheit und Haftung'),('Nach Abnahme stellt der Unternehmer eine Mängelsicherheit in Höhe von 32.500,00 EUR durch eine selbstschuldnerische Bürgschaft eines in der Europäischen Union zugelassenen Kreditinstituts. Die Sicherheit ist nicht auf erstes Anfordern zu zahlen. Sie dient nur den gesicherten Mängelansprüchen aus diesem Vertrag und wird zurückgegeben, sobald nach Ablauf der maßgeblichen Frist keine gesicherten Ansprüche mehr bestehen. Ein doppelter Bareinbehalt wird nicht vereinbart.' if actor=='rohbau' else 'Eine besondere Vertragserfüllungs- oder Mängelbürgschaft ist für dieses Los nicht vereinbart. Gesetzliche Zurückbehaltungsrechte bleiben unberührt. Die Haftung richtet sich nach den gesetzlichen Vorschriften; ein pauschaler Ausschluss für Folgeschäden oder eine Begrenzung bei vorsätzlichem oder grob fahrlässigem Verhalten wird nicht vereinbart.'),
          ('h','8 Abschluss'),'Es gilt deutsches Recht. Die VOB/B wird nicht Vertragsbestandteil. Änderungen und Ergänzungen sollen zur Nachvollziehbarkeit in Textform dokumentiert werden; der Vorrang wirksamer Individualvereinbarungen bleibt unberührt. Die gesetzlichen Gerichtsstände bleiben bestehen. Beide Parteien bestätigen den Erhalt der bezeichneten Vertragsunterlagen.',
          'Hildesheim, 12.11.2027. Für die Bestellerin: gez. Maren Birk. Für den Unternehmer: gez. '+ACTORS[actor][3]+'.'
        ],'docx',recipient=actor,signer='Vertragsausfertigung für beide Parteien')
    add(51,'Baubesprechung_Bodenbefund','2028-02-02','architekt','Baubesprechung zum abweichenden Bodenbefund',[
      'Am 02.02.2028 haben Maren Birk, Nora Feld, Timo Wendt und Dr. Ute Venn die südöstliche Gründungsecke besichtigt. Beim Aushub wurde eine örtlich begrenzte wasserführende Feinsandschicht angetroffen. Die ursprünglichen Erkundungspunkte lagen außerhalb dieses Bereichs. Der Befund wird weder als allgemeiner Fehler des gesamten Baugrundberichts noch als Freigabe einer beliebigen Grundwasserabsenkung verstanden.',
      'Die betroffene Fläche von rund 24 m² bleibt bis zur abgestimmten Sicherung offen. Dr. Venn empfiehlt eine technisch bemessene Filter- und Dränpackung unter dem lokalen Anschlussbereich. Der vorhandene Entwässerungsanschluss darf dafür nicht ohne Abstimmung genutzt werden. Die erforderliche Ableitung erfolgt innerhalb des freigegebenen Baustellenentwässerungskonzepts.',
      'Steinwerk legt bis zum 04.02.2028 ein Nachtragsangebot mit Mengen, Arbeitsstunden und Materialansätzen vor. Frau Feld und die Tragwerksplanung prüfen die technische Einbindung. Nur Frau Birk entscheidet über den Zusatzauftrag. Die Arbeiten an der westlichen Bodenplattenzone können fortgesetzt werden. Ein allgemeiner Stillstand der gesamten Baustelle wird nicht festgestellt.',
      'Timo Wendt nennt zunächst fünf Arbeitstage Auswirkung auf die betroffene Zone. Eine Beschleunigung im März wird geprüft. Ein neuer Endtermin wird heute nicht vereinbart. Die Kostenfortschreibung wird erst nach der Auftragserteilung mit dem vereinbarten Betrag aktualisiert.'
    ],'docx')
    add(52,'Behinderungsanzeige_Rohbau','2028-02-02','rohbau','Behinderung im südöstlichen Gründungsbereich',[
      'Wir zeigen an, dass die im Besprechungsprotokoll beschriebene Feinsandschicht die planmäßige Herstellung der Gründung in der südöstlichen Ecke derzeit verhindert. Der betroffene Abschnitt umfasst Achsen C bis D / 3 bis 4. Die zwei eingesetzten Mitarbeiter und der Bagger werden soweit möglich in der westlichen Zone weiterbeschäftigt. Eine vollständige Stilllegung liegt nicht vor.',
      'Ohne Freigabe der ergänzenden Filterpackung können wir die Bewehrung in diesem Abschnitt nicht planmäßig schließen. Unsere erste Einschätzung beträgt fünf Arbeitstage Verzögerung. Ob daraus eine Verschiebung der gesamten Rohbauübergabe folgt, hängt von der Freigabe und den anschließenden Betoniertakten ab.',
      'Wir bitten um Entscheidung nach Vorlage unseres Angebots. Die Anzeige enthält noch keine abschließende Forderung wegen Mehrkosten oder Bauzeitverlängerung. Arbeitsstunden, Geräteeinsatz und Materialverbrauch werden getrennt erfasst. Bitte bestätigen Sie den Eingang und benennen Sie die Entscheidungsperson für den Zusatzauftrag.'
    ],'eml')
    add(53,'Nachtragsangebot_Filterpackung','2028-02-04','rohbau','Nachtragsangebot 01 für lokale Filter und Dränpackung',[
      'Auf Grundlage der Baustellenbesprechung vom 02.02.2028 und der technischen Ergänzung der Baugrundplanung bieten wir die örtlich begrenzte zusätzliche Filter- und Dränpackung an. Die Leistung war nach unserer Auslegung des vereinbarten Bodenbefunds nicht in der ursprünglichen Pauschale enthalten. Die Bestellerin hat diese Einordnung vor Auftragserteilung zu prüfen.',
      ('t',[['Leistung','Menge','Einheitspreis EUR','Netto EUR'],['Zusätzlicher Aushub und getrennter Abtransport','60 m³','85,00','5.100,00'],['Filtermaterial liefern und einbauen','45 m³','160,00','7.200,00'],['Dränleitung mit Anschluss im genehmigten System','30 m','95,00','2.850,00'],['Zusätzliche Arbeitsstunden und örtliche Prüfungen','57 h','50,00','2.850,00'],['Gesamt netto','','','18.000,00'],['Umsatzsteuer 19 Prozent','','','3.420,00'],['Gesamt brutto','','','21.420,00']],[255,65,90,85]),
      'Bei schriftlicher Beauftragung bis zum 05.02.2028 führen wir die Arbeiten vom 07. bis 11.02.2028 aus. Die Mengen werden gemeinsam aufgenommen. Die Vergütung wird für den beschriebenen Leistungsumfang als Pauschale von 18.000,00 EUR netto vereinbart. Nicht enthalten ist eine dauerhafte Grundwasserabsenkung außerhalb des vorhandenen Konzepts.',
      'Die Ausführung erlaubt nach unserer Terminabstimmung vom 04.02.2028 den Anschluss an den nächsten Betoniertakt. Den Abnahmetermin 15.09.2028 bestätigen wir bei unverzüglicher Freigabe weiterhin. Aus diesem Angebot ergibt sich kein Anspruch auf zusätzliche Beschleunigungsvergütung.'
    ])
    add(54,'Nachtragsauftrag_01','2028-02-05','bauherr','Auftrag für Nachtrag 01 zum Rohbauvertrag',[
      'Wir beauftragen die im Nachtragsangebot vom 04.02.2028 vollständig beschriebene örtliche Filter- und Dränpackung zum Pauschalpreis von 18.000,00 EUR netto zuzüglich 3.420,00 EUR Umsatzsteuer. Maßgeblich sind die dort abgegrenzten Arbeiten sowie die technische Ergänzung von Dr. Venn. Eine dauerhafte Grundwasserabsenkung oder weitere zusätzliche Arbeiten werden damit nicht beauftragt.',
      'Die Objektüberwachung dokumentiert den Einbau gemeinsam mit Ihrer Bauleitung vor dem Verdecken. Bitte legen Sie Materialnachweise, Fotos mit Bauteilbezug und das gemeinsame Mengenblatt vor. Die Rechnung ist als Nachtrag 01 getrennt von bereits abgerechneten Abschlägen auszuweisen.',
      'Sie haben den unveränderten Abnahmetermin 15.09.2028 bestätigt. Wir übernehmen die von Ihnen vorgeschlagene Ausführung vom 07. bis 11.02.2028. Eine darüber hinausgehende Bauzeit- oder Mehrkostenvereinbarung treffen wir nicht. Bei neuen tatsächlichen Hindernissen erwarten wir eine gesonderte konkrete Mitteilung.',
      'Diese Erklärung erfolgt durch mich als Geschäftsführerin. Eine frühere technische Abstimmung mit Frau Feld stellte noch keinen Zusatzauftrag dar.'
    ],'eml',recipient='rohbau')
    add(55,'Gemeinsames_Aufmass_Nachtrag','2028-02-11','architekt','Gemeinsames Aufmaß des Nachtrags 01',[
      'Das Aufmaß wurde am 11.02.2028 vor dem Verdecken durch Nora Feld und Timo Wendt aufgenommen. Dr. Venn war bei der Kontrolle der Filterabstufung anwesend. Die Lage entspricht dem örtlich abgegrenzten Bereich aus der Besprechung vom 02.02.2028. Grundlage der Abrechnung bleibt die am 05.02.2028 vereinbarte Pauschale.',
      ('t',[['Nachweis','Ansatz','Feststellung'],['Aushub','10,00 × 4,00 × 1,50 m','60,00 m³'],['Filterpackung','10,00 × 3,00 × 1,50 m','45,00 m³'],['Dränleitung','12,00 + 10,00 + 8,00 m','30,00 m'],['Ergänzende Arbeitszeit','3 Mitarbeiter × 19 Stunden','57,00 Stunden']],[165,170,160]),
      'Die Maße beziehen sich auf unterschiedliche Arbeitsbereiche. Aus der Filtermenge darf deshalb kein identischer Grundriss wie beim gesamten Aushub abgeleitet werden. Der örtliche Anschluss wurde am Nachmittag durch die Fachplanung kontrolliert. Eine vollständige Neuuntersuchung des Grundstücks fand nicht statt.',
      'Die Einbaukontrolle bestätigt die protokollierten Maße und den sichtbaren Arbeitsstand. Sie ist keine pauschale Anerkennung weiterer, nicht beauftragter Leistungen und keine Abnahme des gesamten Rohbaus. Unterschriften: gez. Nora Feld; gez. Timo Wendt; technischer Befund gez. Dr. Ute Venn.'
    ])
    add(56,'Gesamtinbetriebnahme_Technik','2028-09-08','tga','Gemeinsamer Inbetriebnahmetermin der Gebäudetechnik',[
      'Am 08.09.2028 haben die TGA-Planung, Wärmefluss Haustechnik, Lichtkreis Elektro und Hubpunkt Aufzüge den abgestimmten Inbetriebnahmetermin durchgeführt. Die folgenden Feststellungen betreffen die jeweils benannten Anlagen. Der Termin ersetzt weder die förmliche Abnahme der Bauverträge noch Prüfentscheidungen einer zugelassenen Überwachungsstelle.',
      ('t',[['Anlage','Feststellung','Unterlage'],['Wärmeerzeugung','Zwei Geräte je18kW, Kaskadenbetrieb und Umschaltung geprüft','Einstellblatt HLS-08'],['Heizkreise','Hydraulischer Abgleich abgeschlossen; Sollwerte wohnungsweise dokumentiert','Abgleichblatt HLS-09'],['Trinkwasser','Druckprüfung und Spülung dokumentiert; Temperaturhaltung kontrolliert','Prüfblatt HLS-10'],['Lüftung','Betriebsstufen je Wohnung eingeregelt','Messblatt L-08'],['Elektro','Verteilungen geprüft; Kennzeichnung nach Stromlaufplänen','Prüfbericht E-08'],['PV und Ladepunkte','36kWp; beide Ladepunkte und Lastmanagement funktionsfähig','Messkonzept PV-08'],['Aufzug','Prüfung vor Inbetriebnahme am07.09.2028 ohne offenen sicherheitsrelevanten Befund','Prüfbescheinigung A-08']],[90,275,130]),
      'Die Regelung der Wärmepumpen ist auf einen abgestimmten Heizbetrieb eingestellt. Der technische Betreiber erhält Einweisung und Wartungstermine. Ein späterer Wechsel von Einstellungen ohne Dokumentation ist zu vermeiden. Der jährliche Stromertrag der PV-Anlage wird nicht als garantierte Strommenge zugesagt.',
      'Die Aufzugsprüfung wurde durch die zugelassene Überwachungsstelle vorgenommen; die Montagefirma hat deren Bescheinigung im Anlagenordner hinterlegt. Der Notruf wurde im Beisein der späteren Verwaltung getestet. Vor Mietbeginn sind die tatsächlichen Zählerstände in den Wohnungsübergaben festzuhalten.'
    ])
    add(57,'Maengelanzeige_vor_Abnahme','2028-09-11','bauherr','Feststellungen aus der Vorbegehung',[
      'Bei der Vorbegehung am 10.09.2028 wurden drei noch zu erledigende Punkte festgestellt. Im Hausflur 1. OG schließt die Tür zum notwendigen Treppenraum nicht zuverlässig. An Wohnung 05 ist das Ablaufprofil der nördlichen Fensterbank zu kontrollieren. In Wohnung 07 ist entgegen der Ausstattungsfreigabe ein anderer Eichenbelag eingebaut worden.',
      'Die Türfunktion ist vor dem Abnahmetermin am 15.09.2028 herzustellen und gemeinsam nachzuprüfen. Dachraum soll den Fensterbankanschluss öffnen, den Befund dokumentieren und die vorgesehene Entwässerung herstellen. Innenraum Ausbau soll den abweichenden Belag genau benennen und ein Angebot für einen Austausch oder eine einvernehmliche Lösung vorlegen.',
      'Wir stimmen einer Abweichung beim Bodenbelag heute nicht zu. Ein Minderungsbetrag wird noch nicht festgelegt. Die Nutzung der Wohnung zu einer Besichtigung stellt keine Abnahme des Ausbaugewerks dar. Wir halten am vorgesehenen gemeinsamen Abnahmetermin fest, sofern die dann vorhandenen Befunde eine Abnahme erlauben.',
      'Bitte bestätigen Sie Zuständigkeit und Ausführungstermin bis morgen. Frau Feld dokumentiert die technische Nachprüfung; rechtsgeschäftliche Erklärungen erfolgen durch die Bauherrin.'
    ],recipient='ausbau')
    add(58,'Nachbesserungsstand','2028-09-14','architekt','Stand der Arbeiten vor dem Abnahmetermin',[
      'Die Tür im 1. OG wurde heute neu eingestellt. Bei drei unmittelbar aufeinanderfolgenden Funktionsprüfungen schloss sie vollständig. Dachraum hat das Ablaufprofil an Wohnung 05 geöffnet und neu angeschlossen. Der Wasserablauf wurde vor Ort kontrolliert; im geöffneten Anschluss lag kein sichtbarer Feuchteschaden vor.',
      'Der Bodenbelag der Wohnung 07 bleibt abweichend. Innenraum Ausbau hat erklärt, dass die technisch geeignete Ersatzqualität nach interner Materialverwechslung eingebaut worden sei. Frau Birk will zunächst ein Muster und den Preisunterschied prüfen. Es liegt noch keine Zustimmung zur Vertragsänderung vor.',
      'Für den morgigen Termin empfehle ich, die erledigten Punkte mit dem jeweiligen Bauteilbezug zu dokumentieren und den Belagsvorbehalt ausdrücklich aufzunehmen. Ob die Bestellerin abnimmt, entscheidet sie nach dem festgestellten Leistungsstand. Die heutige E-Mail enthält keine Abnahmeerklärung im Namen der Bauherrin.'
    ],'eml')
    add(59,'Foermliche_Abnahmen','2028-09-15','bauherr','Protokoll des gemeinsamen förmlichen Abnahmetermins',[
      'Am 15.09.2028 wurden die Leistungen der sieben Bauverträge im Wohnhof Am Steinbogen 18 gemeinsam besichtigt. Für die Bestellerin nahm Maren Birk teil, als beratende Objektüberwachung Nora Feld. Die nachfolgend genannten Unternehmen waren jeweils für ihr Gewerk vertreten. Jede Abnahmeerklärung bezieht sich nur auf die bezeichnete Vertragsleistung.',
      ('t',[['Vertrag','Erklärung und Vorbehalt']]+[[title,'Die Bestellerin nimmt die Leistung ab. '+('Der abweichende Eichenbelag der Wohnung07 bleibt als bekannter Mangel vorbehalten. Eine Vergütungsanpassung ist noch nicht vereinbart.' if actor=='ausbau' else 'Im heutigen Termin bestehen keine zusätzlich protokollierten offenen Mängel. Nicht erkennbare Mängel bleiben von dieser Feststellung unberührt.')] for actor,title,_,_ in LOTS],[200,295]),
      'Die am 11.09.2028 angezeigte Türfunktion und der sichtbare Fensterbankanschluss wurden erneut kontrolliert. Die dokumentierten Maßnahmen sind im sichtbaren Bereich erledigt. Die fachliche Prüfung ersetzt keine Zusage, dass verdeckte Mängel ausgeschlossen seien. Vorbehalte wegen einer Vertragsstrafe werden nicht aufgenommen, weil keine Vertragsstrafe vereinbart wurde.',
      'Die Parteien halten den heutigen Tag als Abnahmedatum ihrer jeweiligen Bauleistung fest. Die reguläre fünfjährige Mängelverjährung aus den hier geschlossenen BGB-Bauverträgen wird mit dem 15.09.2033 als vorläufigem Fristende im Register vermerkt. Spätere Anerkenntnisse, Verhandlungen oder sonstige fristrelevante Vorgänge sind gesondert zu prüfen. Für Architektenleistungen wird heute keine Abnahme erklärt.',
      'Die vollständigen Revisions- und Bedienunterlagen werden im Übergabetermin am 22.09.2028 an die Verwaltung ausgegeben. Der Rohbauunternehmer hat die vereinbarte Mängelbürgschaft vorgelegt. Die Bestellerin bestätigt den Erhalt, ohne damit über noch nicht bekannte Mängelansprüche zu verfügen.',
      'Unterschriften: gez. Maren Birk; Timo Wendt; Ina Mertens; Arne Thiel; Selin Voß; Jan Merz; Ralf Hanke; Mira Roth. Protokollführung: gez. Nora Feld.'
    ],'docx')
    add(60,'Uebergabe_Gebaeudeunterlagen','2028-09-22','architekt','Gebäudeübergabe und Unterlagenverzeichnis',[
      'Die Objektüberwachung übergibt der Bauherrin und ihrer Mietverwaltung den dokumentierten Stand des Wohnhauses. Der Mietbeginn ist für den 01.10.2028 vorgesehen. Die Übergabe von Unterlagen ist von der bereits erfolgten Abnahme der Bauleistungen sowie einer gesonderten Abnahme der Planerleistungen zu unterscheiden.',
      ('h','1 Bestandsstand'),'Die Ausführung umfasst acht Wohnungen mit zusammen 600 m² vereinbarter Wohnfläche, drei Geschosse und einen Aufzug. Die tatsächlichen Tür- und Bewegungsflächen wurden im Abschlussaufmaß dokumentiert. Die Dachfläche trägt 80 PV-Module zu je 450 Wp. Von den acht Pkw-Stellplätzen ist Stellplatz01 barrierefrei gekennzeichnet; alle Stellplätze sind vorverkabelt, zwei mit Ladepunkten ausgestattet. Fahrrad- und Spielbereiche entsprechen dem abschließenden Außenanlagenstand.',
      ('h','2 Übergebene Unterlagen'),('t',[['Bereich','Unterlagen und Zuständigkeit'],['Bauaufsicht','Genehmigung, Nebenbestimmungen, Baubeginn- und Fertigstellungsmitteilungen; Bauherrin'],['Planung','Freigegebene Planstände, ergänzte Ausführungsdetails, Revisionsstand; Konturfeld'],['Rohbau','Material- und Einbauunterlagen, dokumentierter Nachtrag01; Steinwerk'],['Gebäudehülle','Fensterlisten, Dach- und Anschlussdetails, Pflegehinweise; Dachraum'],['Gebäudetechnik','Inbetriebnahme, Einstellwerte, Zählerzuordnung, Bedienung; Planwerk und Fachfirmen'],['Aufzug','Prüfbescheinigung, Notruf und Betriebsanweisung; Hubpunkt'],['Außenanlagen','Entwässerung, Geräteunterlagen und Pflegehinweise; Grünkante'],['Kaufmännisch','Verträge, Rechnungen, Zahlungsbelege und fortgeschriebene Kosten; Bauherrin']],[120,375]),
      ('h','3 Noch laufende Vorgänge'),'Der Belagsvorbehalt für Wohnung07 wird außerhalb der Wohnungsübergabe mit dem Ausbauunternehmen geklärt. Ein zusätzlicher Rechnungs- und Zahlungsabgleich ist vorgesehen, da die Buchhaltung einen doppelten Zahlungslauf für eine Elektroabschlagsrechnung gemeldet hat. Das betrifft die finanzielle Abwicklung und wird nicht als weiterer Bauauftrag erfasst.',
      'Die Verwaltung erhält den Schlüsselplan und bestätigt die Übernahme der laufenden Betreiberorganisation. Technische Prüfungen und Wartungsleistungen werden nach den Anlagenanforderungen beauftragt. Die Regelung der Wärmepumpen darf nicht ohne Dokumentation verändert werden. Die Bedienunterlagen sind auch der Vertretung der Verwaltung zugänglich zu halten.'
    ])
    add(62,'Betrieb_und_Wartungsplan','2028-09-22','verwaltung','Betrieb und Wartung des Wohnhauses',[
      'Die Mietverwaltung übernimmt ab dem 01.10.2028 die Betreiberorganisation für das Wohnhaus. Die Geschäftsführerin bleibt für die erforderlichen Beauftragungen verantwortlich. Der folgende Plan legt Ansprechpartner und dokumentierte Abläufe fest. Er ersetzt weder Herstellerangaben noch verbindliche Prüfpflichten.',
      ('t',[['Anlage','Ablauf','Dokumentation'],['Wärmepumpen und Hydraulik','Jährliche Wartung, zusätzliche Prüfung bei auffälligem Verbrauch oder Regelungsänderung','Betriebsbuch und Einstellwerte'],['Trinkwasser und Warmwasser','Temperaturen, Störungen und einschlägige Untersuchungsanforderungen mit Fachfirma verfolgen','Mess- und Wartungsberichte'],['Aufzug','Notruf jederzeit betriebsbereit; Wartung und vorgeschriebene Prüfungen fristgerecht beauftragen','Prüf- und Notrufbuch'],['Rauchwarnmelder','Betriebsbereitschaft nach Landesrecht und vereinbarter Zuständigkeit sichern','Wohnungsbezogene Wartung'],['Dach und Entwässerung','Halbjährliche Sichtkontrolle sowie nach außergewöhnlichem Unwetter','Fotos und Reinigungsnachweise'],['PV und Ladepunkte','Störmeldungen bearbeiten und elektrische Prüfungen nach fachlicher Vorgabe','Anlagenprotokoll'],['Spielbereich','Regelmäßige Sichtkontrolle, Wartung und sicherheitsbezogene Prüfung','Kontrollbuch']],[105,270,120]),
      'Mietparteien melden Feuchte, Funktionsstörungen und Schäden zeitnah an die Verwaltung. Die Verwaltung dokumentiert Datum, Wohnung, Bauteil und erste Maßnahmen, ohne die Ursache vor fachlicher Prüfung festzulegen. Bei akuter Gefahr werden Sicherungsmaßnahmen veranlasst. Die normale Meldung an eine Fachfirma ersetzt keine Prüfung von Anspruchsfristen.',
      'Kosten der Verwaltung und Instandsetzung werden nicht als umlagefähige Betriebskosten behandelt. Laufende Betriebskosten werden nur im vertraglich und gesetzlich zulässigen Umfang abgerechnet. Die kaufmännische Zuordnung bleibt vom technischen Wartungsplan getrennt.'
    ])
    add(63,'Feuchtemeldung_Wohnung05','2030-11-04','mieter','Feuchte unter dem Wohnzimmerfenster',[
      'Unter dem nördlichen Wohnzimmerfenster der Wohnung05 ist seit dem Regen am Wochenende ein feuchter Streifen zu sehen. Wir haben den Bereich nicht überstrichen und ein Handtuch vorgelegt. Die Heizung läuft normal; das Fenster war während des Regens geschlossen. Uns ist nicht klar, ob das Wasser vom Anschluss oder von Kondensation kommt.',
      'Die Erscheinung liegt an demselben Fenster, dessen Anschluss vor unserem Einzug noch bearbeitet worden sein soll. Seit dem Einzug im Oktober2028 ist uns dort bisher keine sichtbare Feuchte aufgefallen. Die Reinigung der Außenseite haben wir nicht selbst vorgenommen. Am Fenster steht ein niedriger Beistelltisch, aber kein Schrank.',
      'Bitte vereinbaren Sie einen Besichtigungstermin. Dienstagvormittag und Donnerstag ab15Uhr wäre jemand zu Hause. Falls weitere Schäden drohen, können Sie uns telefonisch über die bei der Verwaltung hinterlegte Nummer erreichen. Wir möchten wissen, welche vorläufigen Maßnahmen sinnvoll sind und wann eine Prüfung erfolgt.'
    ],'eml',recipient='verwaltung')
    add(64,'Objektbegehung_Feuchte','2030-11-08','architekt','Objektbegehung zum Fensteranschluss der Wohnung05',[
      'Nora Feld hat am 08.11.2030 gemeinsam mit Ina Mertens, Lea Fricke und Sabine Hartung den gemeldeten Bereich besichtigt. Innen ist eine örtliche Verfärbung unter dem nördlichen Wohnzimmerfenster sichtbar. Der Befund stimmt nicht mit einem gleichmäßig an allen Fenstern auftretenden Kondensatbild überein. Eine abschließende Ursachenfeststellung ist aus der Sichtprüfung allein nicht möglich.',
      'Am äußeren Ablaufprofil befindet sich Laub. Nach dessen Entfernung zeigt der örtliche Wasserlauf weiterhin eine Verzögerung an der rechten Anschlussseite. Dachraum schlägt eine begrenzte Öffnung des Anschlussprofils vor. Die Verwaltung stellt die vorhandenen Reinigungsnachweise bereit. Aus dem Laubfund allein folgt weder ein sicherer Wartungsfehler der Mietpartei noch ein Nachweis mangelhafter Bauausführung.',
      'Die Bauherrin beauftragt die Ursachenklärung unmittelbar bei Dachraum. Die heutige fachliche Bewertung erfolgt im Rahmen der vereinbarten Objektbetreuung. Eine fortlaufende örtliche Überwachung einer späteren Mängelbeseitigung ist damit nicht als zusätzliche Architektenleistung beauftragt.',
      'Die reguläre Ausgangsfrist für den Hüllenvertrag bleibt ausgehend von der Abnahme15.09.2028 im Fristenregister sichtbar. Für eine behauptete Hemmung oder einen Neubeginn reicht der Versand einer Mängelmeldung nicht aus. Die spätere Korrespondenz ist der anwaltlichen Prüfung zugänglich zu machen.'
    ],'docx')
    add(65,'Rueckmeldung_Fensteranschluss','2030-11-19','huelle','Ergebnis der örtlichen Öffnung und Wiederherstellung',[
      'Wir haben das rechte Anschlussprofil am Fenster der Wohnung05 am18.11.2030 in Anwesenheit der Verwaltung geöffnet. Im überdeckten Bereich war eine zu hoch geführte Dichtstoffraupe sichtbar. Sie wurde entfernt und der Anschluss entsprechend dem abgestimmten Detail wiederhergestellt. Der anschließende Wasserlauf war frei.',
      'Die Arbeiten führen wir ohne gesonderte Vergütung aus. Wir bestätigen den beschriebenen tatsächlichen Befund und die ausgeführten Maßnahmen. Eine darüber hinausgehende rechtliche Erklärung zu anderen Bauteilen oder zu sämtlichen Anspruchsfristen ist damit nicht verbunden. Bitte führen Sie die Verwaltungskorrespondenz und den Befund im Projektarchiv zusammen.',
      'Die innere Oberfläche soll zunächst trocknen. Frau Hartung hat einer Nachkontrolle nach vier Wochen zugestimmt. Sollten erneut Feuchtespuren auftreten, bitten wir um Mitteilung mit Datum und Wetterlage. Eine weitere Ortsüberwachung durch die Architektin haben wir nicht bestellt.'
    ],'eml')
    add(66,'Vorfristbegehung_2033','2033-08-10','architekt','Begehung vor dem regulären Fristende der Bauverträge',[
      'Am10.08.2033 erfolgte die im Architektenvertrag vorgesehene Objektbegehung vor Ablauf der regulären Mängelverjährung der Bauverträge. Teilgenommen haben Nora Feld, Maren Birk und Lea Fricke. Die Verwaltung stellte Wartungsberichte, Meldungen der Mietparteien und den Vorgang zum Fenster der Wohnung05 bereit.',
      ('t',[['Bauteil','Feststellung','Weiteres Vorgehen'],['Rohbau','Keine auffälligen neuen Risse in den zugänglichen Bereichen','Keine zusätzliche Untersuchung aus dem heutigen Sichtbefund'],['Dach und Fassade','Keine neue Feuchtemeldung; Wartungen dokumentiert','Wartung fortführen'],['Fenster Wohnung05','Nach Bearbeitung2030 keine erneute Meldung; Innenfläche trocken','Vorgang gesondert rechtlich würdigen'],['Innenausbau Wohnung07','Belagsabweichung2028 durch Vereinbarung und Gutschrift erledigt','Vereinbarung im Archiv belassen'],['Technik und Aufzug','Betriebs- und Prüfunterlagen liegen im Verwaltungsordner','Betreiberpflichten laufen weiter'],['Außenanlagen','Übliche Gebrauchsspuren ohne neue konkrete Schadensmeldung','Pflege und Kontrollen fortführen']],[110,225,160]),
      'Die Begehung erfasst die zugänglichen Bereiche und die bereitgestellten Informationen. Sie ist keine zerstörende Untersuchung sämtlicher Bauteile. Die Bauherrin soll neu gemeldete Umstände umgehend rechtlich prüfen lassen. Das reguläre Ausgangsdatum15.09.2033 wird nicht ungeprüft auf den Vorgang mit der Nachbesserung2030 übertragen; dessen rechtliche Wirkung ist gesondert zu bewerten.',
      'Für das Rohbaulos sind aus den verfügbaren Vorgängen derzeit keine offenen konkreten Mängelansprüche ersichtlich. Die Mängelbürgschaft kann nach Prüfung zum regulären Fristende zur Rückgabe vorbereitet werden. Für andere Gewerke ist keine solche Bürgschaft vereinbart. Die Rückgabe einer Rohbausicherheit bedeutet keinen Verzicht auf Ansprüche gegen andere Unternehmen.'
    ])
    add(67,'Rueckgabe_Rohbausicherheit','2033-09-18','bauherr','Rückgabe der Bürgschaft für das Rohbaulos',[
      'Nach Auswertung der Vorfristbegehung vom10.08.2033 und der zwischenzeitlichen Meldungen geben wir die Mängelbürgschaft LB-SW-2028-325 über32.500,00EUR für das Rohbaulos zurück. Bis zum heutigen Stand sind keine offenen gesicherten Ansprüche aus diesem Vertrag konkret festgestellt oder angezeigt worden.',
      'Die Erklärung bezieht sich ausschließlich auf die bezeichnete Sicherheit des Rohbauunternehmens. Sie enthält keinen allgemeinen Erlass von Ansprüchen aus anderen Bauverträgen und keine abschließende rechtliche Einordnung des Fensteranschlussvorgangs von2030. Die Verwaltungsunterlagen werden weiter aufbewahrt.',
      'Bitte bestätigen Sie den Empfang der Bürgschaftsurkunde. Die Rückgabe wird im Sicherheitenregister der Bauherrin vermerkt. Die Objektüberwachung hat die fachlichen Befunde geliefert; die Entscheidung über die Rückgabe trifft die Bauherrin selbst.',
      'Die Planerleistungen werden gesondert abgeschlossen. Der heutige Vorgang ist weder eine rückwirkende Abnahme des Architektenvertrags noch eine Änderung der laufenden Betreiber- und Wartungsorganisation.'
    ],'docx',recipient='rohbau')
    add(68,'Abschluss_Objektbetreuung','2033-09-20','architekt','Abschluss der beauftragten Objektbetreuung',[
      'Die beauftragten Leistungen der Objektbetreuung sind nach der Vorfristbegehung, der fachlichen Auswertung und der Mitwirkung bei der Rückgabe der Rohbausicherheit abgeschlossen. Die Abrechnung der letzten Honorarstufe erfolgt getrennt. Die Bauherrin erhält die fortgeschriebene Dokumentation und die Hinweise zu noch rechtlich zu bewertenden Einzelvorgängen.',
      'Die Betreuung umfasste die fachliche Bewertung gemeldeter Mängel, die erforderlichen Begehungen und die vereinbarte Mitwirkung bei Sicherheiten. Eine vollständige Überwachung späterer Sanierungsarbeiten war nicht zusätzlich beauftragt. Die Begehung von2030 und die Auswertung der Unternehmerantwort wurden im vorhandenen Auftrag dokumentiert.',
      'Die reguläre fünfjährige Betrachtung der Bauverträge ist nicht mit der Verjährung sämtlicher Ansprüche gegen Planer gleichzusetzen. Insbesondere ist eine Abnahme der Architektenleistungen gesondert zu dokumentieren. Der Abschlussbericht erklärt selbst keine Abnahme durch die Bauherrin.',
      'Der dokumentierte Fensteranschlussvorgang2030 bleibt mit seinen tatsächlichen Erklärungen im Archiv. Für dessen rechtliche Fristwirkung wird auf die gesonderte anwaltliche Prüfung verwiesen. Laufende Mietverhältnisse, Wartungen und Betreiberpflichten gehen unabhängig vom Ende der Objektbetreuung weiter.'
    ])
    add(146,'Maengelbuer gschaft_Rohbau'.replace(' ',''),'2028-09-05','bank','Mängelbürgschaft für das Rohbaulos',[
      'Bürgschaftsurkunde LB-SW-2028-325. Auf Antrag der Steinwerk Hochbau GmbH übernehmen wir gegenüber der Steinbogen Wohnen GmbH eine selbstschuldnerische Bürgschaft bis zu32.500,00EUR zur Sicherung der nach dem Bauvertrag vom12.11.2027 gesicherten Mängelansprüche für das Rohbaulos des Wohnhauses Wohnhof Am Steinbogen18.',
      'Die Bürgschaft ist keine Bürgschaft auf erstes Anfordern. Der Umfang richtet sich nach dem gesicherten Vertrag und den bestehenden gesicherten Ansprüchen. Die Einrede der Vorausklage wird ausgeschlossen. Andere gesetzliche Einwendungen und Einreden bleiben im rechtlich zulässigen Umfang erhalten.',
      'Die Urkunde ist nach Wegfall des Sicherungszwecks an uns zurückzugeben. Ein festes automatisches Erlöschensdatum, das bestehende gesicherte Ansprüche unabhängig von ihrem Stand abschneiden würde, wird nicht vereinbart. Eine doppelte Barsicherheit ist nach Mitteilung der Vertragsparteien nicht bestellt.',
      'Diese Urkunde betrifft ausschließlich die Mängelsicherheit des Rohbauvertrags. Sie ist weder eine Finanzierungszusage für die Bauherrin noch eine Sicherheit für die anderen sechs Bauverträge. Die Bürgschaft wird durch unsere zeichnungsberechtigten Mitarbeitenden ausgefertigt.'
    ],recipient='bauherr')
    add(147,'Belagsvereinbarung_Wohnung07','2028-10-15','bauherr','Vereinbarung zum Bodenbelag der Wohnung07',[
      'Die Steinbogen Wohnen GmbH und Innenraum Ausbau GmbH einigen sich nach Bemusterung des eingebauten Belags darauf, dass dieser in Wohnung07 verbleibt. Die Abweichung von der ursprünglich vereinbarten Eichenqualität wird durch eine Herabsetzung der Vergütung um2.500,00EUR netto zuzüglich475,00EUR Umsatzsteuer ausgeglichen.',
      'Innenraum Ausbau erteilt eine entsprechende Rechnungskorrektur über insgesamt2.975,00EUR und erstattet den Betrag auf das Projektkonto der Bauherrin. Die Rechnungskorrektur bezeichnet die betroffene Schlussrechnung und den Leistungsbezug. Bereits geleistete Zahlungen werden nicht als neuer Bauaufwand gebucht.',
      'Mit der Vereinbarung wird nur die bezeichnete Materialabweichung abgegolten. Ansprüche wegen anderer Mängel, etwa fehlerhafter Verlegung oder später erkennbarer Schäden, werden nicht pauschal ausgeschlossen. Die übrigen Vertragsbedingungen bleiben bestehen.',
      'Die Mietpartei der Wohnung07 wurde über das verbleibende Material informiert. Der Mietvertrag wird dadurch nicht einseitig geändert. Für die Bauherrin: gez. Maren Birk. Für Innenraum Ausbau: gez. Jan Merz.'
    ],'docx',recipient='ausbau')
    add(148,'Fertigstellungsmitteilung','2028-09-22','bauherr','Mitteilung über die Fertigstellung und vorgesehene Nutzung',[
      'Wir teilen mit, dass die genehmigten Baumaßnahmen am Achtfamilienhaus abgeschlossen sind. Die Nutzung der acht Wohnungen ist ab01.10.2028 vorgesehen. Der freigegebene Revisionsstand, die Bestätigungen der verantwortlichen Fachleute und die gemäß Nebenbestimmungen geforderten Unterlagen werden mit dem zugeordneten Verwaltungsvorgang eingereicht.',
      'Die bauliche Ausführung umfasst die genehmigten acht Wohnungen, die barrierefreien Erschließungswege einschließlich Aufzug sowie die vorgesehenen Außenanlagen. Der barrierefreie Pkw-Stellplatz ist gekennzeichnet. Spiel- und Fahrradflächen sind hergestellt. Die elektrische Vorverkabelung aller acht Pkw-Stellplätze und die beiden Ladepunkte sind dokumentiert.',
      'Die technischen Anlagen sind in Betrieb genommen und der Verwaltung übergeben. Die erforderliche Aufzugsprüfung vor Inbetriebnahme ist dokumentiert. Die laufenden Betreiberpflichten bleiben unabhängig von dieser Mitteilung bestehen.',
      'Die Mitteilung enthält keine Erklärung der Bauaufsicht, dass sämtliche Ausführungsdetails von ihr geprüft oder abgenommen worden seien. Bitte ordnen Sie die Unterlagen dem genehmigten Vorhaben zu und teilen Sie uns mit, falls aus dem Verwaltungsvorgang noch konkret bezeichnete Unterlagen fehlen.'
    ],'docx',recipient='bauamt')
    add(153,'Abnahme_Architektenleistungen','2033-09-25','bauherr','Abnahme der abgeschlossenen Architektenleistungen',[
      'Die Steinbogen Wohnen GmbH erklärt gegenüber Konturfeld Architektur PartG mbB die Abnahme der nach dem Architektenvertrag und den dokumentierten Stufenabrufen geschuldeten, nunmehr abgeschlossenen Leistungen. Maren Birk und Nora Feld haben den Abschlussbericht vom20.09.2033, die übergebenen Projektunterlagen und den Stand der Objektbetreuung gemeinsam erörtert.',
      'Eine frühere Teilabnahme von Architektenleistungen wurde in dieser Akte nicht vereinbart oder erklärt. Die förmlichen Bauabnahmen vom15.09.2028 betrafen ausschließlich die sieben ausführenden Unternehmen. Die heutige Erklärung wird nicht auf dieses Datum zurückbezogen.',
      'Im heutigen Termin werden keine konkret bezeichneten offenen Restleistungen aus dem beauftragten Leistungsumfang festgestellt. Nicht bekannte oder nicht erkennbare Mängelansprüche werden damit nicht ausgeschlossen. Die tatsächlichen Unterlagen zum Fensteranschlussvorgang2030 bleiben unverändert im Projektarchiv.',
      'Die letzte Honorarstufe kann auf Grundlage der abgeschlossenen Leistungen abgerechnet werden. Die Bauherrin prüft die Schlussrechnung einschließlich bereits gezahlter Abschläge gesondert. Die heutigen Unterschriften bestätigen die vorstehende Erklärung und den Erhalt des Protokolls. Für die Bauherrin gez.Maren Birk; für das Architekturbüro gez.Nora Feld.'
    ],'docx',recipient='architekt')
    add_leases()
    return list(RECORDS)

TENANTS=[('Lena und Paul Rehm',68,'EG links'),('Derya Aydin',75,'EG Mitte'),('Jonas und Eva Lenz',82,'EG rechts'),('Mika Petersen',68,'1.OG links'),('Sabine und Martin Hartung',75,'1.OG Mitte'),('Nora und David Klein',82,'1.OG rechts'),('Tessa Brandt',75,'2.OG links'),('Leon und Amira Winter',75,'2.OG rechts')]
def add_leases():
    for idx,(name,area,position) in enumerate(TENANTS,1):
        rent=area*13.5;cold=area*1.8;heat=area*.9;total=rent+50+cold+heat;key=f'mieter{idx:02d}'
        ACTORS[key]=(name,f'Wohnhof Am Steinbogen 18, Wohnung {idx:02d}, 31134 Hildesheim',f'wohnung{idx:02d}@haushalt.example',name)
        add(153+idx,f'Vorvertragliche_Auskunft_WE{idx:02d}','2028-08-25','bauherr',f'Auskunft vor Abschluss des Mietvertrags für Wohnung {idx:02d}',[
          f'Vor Ihrer Unterzeichnung des vorgesehenen Mietvertrags teilen wir Ihnen für die Wohnung {idx:02d} im Wohnhof Am Steinbogen18 mit: Die Wohnung wird erstmals nach dem01.10.2014 genutzt und vermietet. Der Neubau wird im September2028 fertiggestellt. Die erste Wohnnutzung und die erste Vermietung sind ab01.10.2028 vorgesehen. Eine frühere Wohnnutzung oder frühere Vermietung hat nicht stattgefunden.',
          'Diese Auskunft erfolgt in Textform vor Vertragsschluss für die Neubauausnahme nach §556f Satz1 BGB und die hierzu vorgesehene vorvertragliche Information nach §556g Absatz1a Satz1 Nummer3 BGB. Ob und in welchem Umfang am Ort und zum Vertragszeitpunkt eine Mietpreisbegrenzung gilt, bleibt davon zu unterscheiden.',
          f'Die angebotene Wohnungsnettomiete beträgt {euro(rent)}EUR monatlich bei{area}m² vereinbarter Wohnfläche. Die vorgesehenen weiteren Entgelte und Vorauszahlungen entnehmen Sie dem gesonderten Vertragsentwurf. Sie können vor einer Unterzeichnung Rückfragen stellen und die tatsächlichen Angaben zum Erstbezug prüfen.',
          'Diese Nachricht ist eine Information im Vorfeld des Vertragsschlusses. Sie nimmt Ihre Annahmeerklärung nicht vorweg und verpflichtet Sie noch nicht zum Abschluss des Mietvertrags. Bitte bewahren Sie sie zusammen mit dem später gegebenenfalls unterzeichneten Vertrag auf.'
        ],'eml',recipient=key)
        add(129+idx,f'Mietvertrag_WE{idx:02d}','2028-09-01','bauherr',f'Wohnraummietvertrag für Wohnung {idx:02d}',[
          f'Die Steinbogen Wohnen GmbH, vertreten durch Maren Birk, vermietet an {name} die Wohnung {idx:02d} im Wohnhof Am Steinbogen18 in Hildesheim. Die Parteien schließen einen unbefristeten Wohnraummietvertrag mit Beginn am01.10.2028.',
          ('h','1 Mietgegenstand'),f'Vermietet wird die Wohnung {position} mit einer vereinbarten Wohnfläche von {area}m² einschließlich der im Übergabeprotokoll bezeichneten Räume. Mitvermietet wird Pkw-Stellplatz{idx:02d}. Die Wohnung wird ausschließlich zu Wohnzwecken überlassen. Gemeinschaftliche Fahrrad-, Abfall- und Spielflächen können im vorgesehenen Umfang mitbenutzt werden. Eine Änderung der vereinbarten Nutzung bedarf der erforderlichen Zustimmung und öffentlich-rechtlichen Zulässigkeit.',
          ('h','2 Miete und Vorauszahlungen'),('t',[['Bestandteil','Monatlich EUR'],['Wohnungsnettomiete',euro(rent)],['Pkw-Stellplatz',euro(50)],['Vorauszahlung kalte Betriebskosten',euro(cold)],['Vorauszahlung Heizung und Warmwasser',euro(heat)],['Gesamtzahlung',euro(total)]],[345,150]),
          'Die laufende Miete ist nach den gesetzlichen Vorschriften zu Beginn des Monats, spätestens bis zum dritten Werktag, zu entrichten. Die Vermieterin teilt die Bankverbindung vor Mietbeginn gesondert mit. Die vereinbarte Wohnungsnettomiete entspricht13,50EUR je Quadratmeter. Es wird weder eine Index- noch eine Staffelmiete vereinbart. Spätere Mietänderungen richten sich nach den gesetzlichen Voraussetzungen.',
          ('h','3 Betriebskosten'),'Die Mietpartei trägt die tatsächlich anfallenden, umlagefähigen Betriebskosten im Sinne von §2 Betriebskostenverordnung, soweit die betreffende Einrichtung oder Leistung vorhanden ist. Dazu gehören insbesondere laufende öffentliche Lasten, Wasser und Entwässerung, Heizung und Warmwasser, Aufzug, Straßenreinigung und Müll, Gebäudereinigung, Gartenpflege, Allgemeinbeleuchtung, Sach- und Haftpflichtversicherung sowie umlagefähige Hauswarttätigkeiten. Verwaltungs-, Instandhaltungs- und Instandsetzungskosten werden nicht umgelegt. Sonstige Betriebskosten werden nicht ohne konkrete Vereinbarung zusätzlich verlangt.',
          'Die Abrechnung erfolgt jährlich für das Kalenderjahr. Die Vermieterin beachtet die gesetzliche Abrechnungsfrist. Kalte Betriebskosten werden nach Wohnfläche verteilt, soweit ein zulässiger Verbrauchs- oder Verursachungsmaßstab vorgeht. Heiz- und Warmwasserkosten werden zu70Prozent nach erfasstem Verbrauch und zu30Prozent nach dem hierfür maßgeblichen Flächenmaßstab verteilt, soweit zwingende gesetzliche Vorgaben keine andere Behandlung erfordern. Die Vorauszahlungen können nach den gesetzlichen Voraussetzungen angepasst werden.',
          ('h','4 Sicherheit'),f'Die Mietsicherheit beträgt {euro(rent*3)}EUR. Sie entspricht drei Wohnungsnettomieten ohne Betriebskostenvorauszahlungen. Die Mietpartei darf in drei gleichen monatlichen Raten zahlen. Die erste Rate ist zu Beginn des Mietverhältnisses, die folgenden Raten zusammen mit den unmittelbar folgenden Mietzahlungen fällig. Die Vermieterin legt die Geldsicherheit getrennt von ihrem Vermögen nach den gesetzlichen Vorgaben an. Die Erträge stehen der Mietpartei zu und erhöhen die Sicherheit.',
          ('h','5 Übergabe und Gebrauch'),'Die Wohnung wird im gesonderten Übergabeprotokoll mit Zustand, Schlüsseln und Zählerständen dokumentiert. Gesetzliche Mängelrechte werden durch eine bloße Zustandsbeschreibung nicht pauschal ausgeschlossen. Die Mietpartei behandelt die Räume pfleglich, meldet Mängel zeitnah und ermöglicht notwendige Arbeiten nach rechtzeitiger Abstimmung. In dringenden Gefahrenfällen gelten die gesetzlichen Mitwirkungspflichten. Ein allgemeines jederzeitiges Betretungsrecht wird nicht vereinbart.',
          ('h','6 Instandhaltung und Veränderungen'),'Die Vermieterin trägt die gesetzliche Instandhaltungspflicht. Es wird keine formularmäßige Übertragung von Schönheitsreparaturen oder Kleinreparaturkosten vereinbart. Bauliche Veränderungen sind vorab abzustimmen; gesetzliche Ansprüche auf Erlaubnis bleiben unberührt. Übliche Kleintierhaltung bleibt zulässig. Andere Tierhaltung wird anhand der konkreten Umstände und der berechtigten Interessen beurteilt.',
          ('h','7 Kündigung und Rückgabe'),'Für Kündigung und Beendigung gelten die gesetzlichen Voraussetzungen, Fristen und Formanforderungen. Ein Zeitmietgrund, ein Kündigungsausschluss und ein pauschaler Räumungsverzicht werden nicht vereinbart. Nach wirksamer Beendigung ist die Wohnung mit allen überlassenen Schlüsseln zurückzugeben. Die Abrechnung über die Mietsicherheit erfolgt nach Prüfung der gesicherten Ansprüche innerhalb des rechtlich zulässigen Zeitraums.',
          ('h','8 Schlussvereinbarungen'),'Mehrere als Mietpartei genannte Personen schließen den Vertrag gemeinsam. Der mitvermietete Stellplatz gehört zu diesem Mietverhältnis. Die PV-Anlage begründet keinen gesonderten Stromliefervertrag mit der Mietpartei; für den Wohnungsstrom wählt sie ihren Versorger selbst. Eine Entgeltvereinbarung für die Nutzung eines Ladepunkts bedarf einer gesonderten Regelung.',
          f'Hildesheim,01.09.2028. Für die Vermieterin gez.Maren Birk. Für die Mietpartei gez.{name}. Beide Seiten erhalten eine Vertragsausfertigung.'
        ],'docx',recipient=key,signer='Vertragsausfertigung')
        add(137+idx,f'Uebergabe_WE{idx:02d}','2028-09-29','verwaltung',f'Übergabeprotokoll Wohnung {idx:02d}',[
          f'Am29.09.2028 wurde die Wohnung {idx:02d} ({position}, {area}m²) an {name} übergeben. Der vertragliche Mietbeginn bleibt der01.10.2028. Anwesend waren die Mietpartei und Lea Fricke für die Vermieterin. Die Übergabe dient der Zustandsfeststellung und ersetzt nicht die Abnahme eines Bauvertrags.',
          ('t',[['Bereich','Feststellung'],['Räume und Oberflächen','Räume besenrein, Fenster und Türen gemeinsam betätigt. '+('Der vorhandene Eichenbelag wurde gezeigt; die Vermieterin klärt dessen abweichende Qualität mit dem Ausbauunternehmen.' if idx==7 else 'Im sichtbaren Bereich keine zusätzlich protokollierten Beschädigungen.')],['Sanitär und Heizung','Armaturen und WC geprüft, Thermostate erklärt, keine sichtbare Leckage'],['Schlüssel','3 Wohnungs-/Haustürschlüssel und2 Briefkastenschlüssel'],['Stromzähler',f'SW-E-{idx:02d}; Stand {12+idx*3},0kWh'],['Kaltwasser',f'SW-K-{idx:02d}; Stand {1.2+idx*.1:.1f}m³'],['Warmwasser',f'SW-W-{idx:02d}; Stand {0.6+idx*.1:.1f}m³'],['Wärmezähler',f'SW-H-{idx:02d}; Stand {0.040+idx*.003:.3f}MWh'],['Stellplatz',f'Pkw-Platz{idx:02d} gezeigt; Zugang und Zuordnung erläutert']],[130,365]),
          'Die Mietpartei erhält Hinweise zur Bedienung der Lüftung, zur Meldung von Störungen und zur Erreichbarkeit der Verwaltung. Die gesetzlichen Mängelrechte bleiben unberührt. Eine spätere Ursache von Feuchte oder Funktionsstörungen wird durch die heutige Besichtigung nicht vorweggenommen.',
          f'Unterschriften: gez.Lea Fricke; gez.{name}. Das Protokoll wird beiden Seiten in gleicher Fassung ausgehändigt.'
        ],'pdf',recipient=key)

def tabular_originals():
    CASE.mkdir(parents=True,exist_ok=True)
    rows=[['Vorgang','Beginn','Ende','Verantwortlich','Abhängigkeit']]
    rows += [
      ['Baustelleneinrichtung','2027-12-01','2027-12-03','Steinwerk','Freigabe Baufeld'],
      ['Erdarbeiten und Gründung','2027-12-06','2028-02-18','Steinwerk','Baugrund und Tragwerk'],
      ['Rohbau Geschosse','2028-02-21','2028-04-28','Steinwerk','Gründung'],
      ['Dach und Gebäudehülle','2028-04-03','2028-06-16','Dachraum','Abschnittsweise Rohbaufreigabe'],
      ['TGA Rohinstallation','2028-04-10','2028-06-30','Wärmefluss und Lichtkreis','Durchführungen abgestimmt'],
      ['Innenausbau','2028-06-05','2028-08-31','Innenraum','Witterungsschutz und Trocknung'],
      ['Aufzug','2028-07-03','2028-08-25','Hubpunkt','Schachtaufmaß'],
      ['Außenanlagen','2028-07-17','2028-09-08','Grünkante','Schwerlastverkehr beendet'],
      ['Inbetriebnahme','2028-09-04','2028-09-08','Planwerk und Fachfirmen','Prüfunterlagen'],
      ['Vorbegehung','2028-09-10','2028-09-10','Konturfeld','Fertigstellungsanzeigen'],
      ['Förmliche Abnahmen','2028-09-15','2028-09-15','Bauherrin','Abnahmereife'],
      ['Wohnungsübergaben','2028-09-29','2028-09-29','Mietverwaltung','Nutzbarkeit und Zählerdaten'],
    ]
    with (CASE/'049_Bauzeitenplan.csv').open('w',newline='',encoding='utf-8-sig') as f:csv.writer(f).writerows(rows)
    diary=[['Datum','Witterung','Personal','Arbeiten und Befund','Veranlassung','Zeichnung']]
    diary += [
      ['2027-12-01','trocken 5°C','4','Bauzaun und Container gesetzt; Zugang vom Gehweg getrennt','Zugang täglich sichern','T.Wendt/N.Feld'],
      ['2027-12-06','bedeckt 4°C','6','Aushub westlicher Abschnitt begonnen; Leitungsmarkierungen vorhanden','Baugrundabgleich beim Aushub','T.Wendt'],
      ['2027-12-16','Regen 3°C','5','Bodenlager abgedeckt; offene Gräben gesichert','Keine Betonage bei ungeeigneter Witterung','T.Wendt'],
      ['2028-01-12','trocken 2°C','7','Vorbereitung Sauberkeitsschicht; Tragwerk prüft Aussparungen','Protokoll vor Betonage','T.Wendt/N.Feld'],
      ['2028-02-02','Regen 6°C','6','Feinsandschicht südöstlich angetroffen; Teilbereich offen','Baugrundplanung und Bauherrin informiert','T.Wendt/N.Feld'],
      ['2028-02-07','trocken 7°C','3','Beauftragte Filterpackung begonnen; westliche Arbeiten fortgeführt','Getrennte Stundenaufzeichnung','T.Wendt'],
      ['2028-02-11','trocken 8°C','3','Nachtrag01 gemeinsam aufgemessen; Anschluss kontrolliert','Vor Verdecken dokumentiert','T.Wendt/N.Feld'],
      ['2028-02-21','bedeckt 8°C','8','Rohbau EG; Schal- und Bewehrungsstand abgeglichen','Aussparungen TGA beachtet','T.Wendt'],
      ['2028-03-09','trocken 10°C','8','Decke EG betoniert; Betonlieferscheine im Rohbauordner','Nachbehandlung dokumentieren','T.Wendt'],
      ['2028-03-23','bedeckt 9°C','8','Rohbau1OG; Schachtmaße kontrolliert','Aufzugfirma erhält Maßblatt','T.Wendt/N.Feld'],
      ['2028-04-03','trocken 12°C','10','Dacharbeiten erster Abschnitt begonnen; Abstimmung PV','Keine ungeprüften Durchdringungen','I.Mertens'],
      ['2028-04-28','trocken 16°C','8','Rohbauabschnitt abgeschlossen; Mauerwerk und Öffnungen sichtbar geprüft','Übergabe an Folgegewerke','T.Wendt/N.Feld'],
      ['2028-05-12','Regen 14°C','11','Fenster eingesetzt; Anschlussfugen in Arbeit','Stichproben vor Verkleidung','I.Mertens/N.Feld'],
      ['2028-06-05','trocken 20°C','12','Trockenbau und Leitungsführung; Abschottungen noch offen','Kennzeichnung je Durchdringung','J.Merz/E.Sand'],
      ['2028-06-16','trocken 22°C','9','Gebäudehülle geschlossen; PV-Unterkonstruktion abgestimmt','Dachprotokoll ergänzen','I.Mertens/S.Voß'],
      ['2028-06-30','bedeckt 19°C','10','TGA-Rohinstallation fertig; Druckprüfung angekündigt','Vor Estrich dokumentieren','A.Thiel'],
      ['2028-07-17','trocken 24°C','7','Außenanlagen begonnen; Stellplatz01 abgesteckt','Bewegungsfläche freihalten','M.Roth'],
      ['2028-08-10','trocken 23°C','12','Beläge eingebaut; WE07 Musterabweichung noch nicht erkannt','Endkontrolle je Wohnung','J.Merz'],
      ['2028-08-25','trocken 21°C','5','Aufzugmontage beendet; Prüfungstermin07.09.','Betrieb erst nach erforderlicher Prüfung','R.Hanke'],
      ['2028-09-08','trocken 18°C','8','Gemeinsame Inbetriebnahme; Anlagenprotokolle geordnet','Einweisung Verwaltung','E.Sand/N.Feld'],
      ['2028-09-10','bedeckt 17°C','4','Vorbegehung: Tür, FensterbankWE05, BelagWE07','Konkrete Mängelmitteilung','N.Feld'],
      ['2028-09-14','trocken 19°C','4','Tür und Fensteranschluss bearbeitet; Belag offen','Vorbehalt im Abnahmeprotokoll','N.Feld'],
      ['2028-09-15','trocken 18°C','9','Förmliche Abnahmen; BelagsvorbehaltWE07','Protokoll von Parteien gezeichnet','M.Birk/N.Feld'],
    ]
    with (CASE/'050_Bautagebuch.csv').open('w',newline='',encoding='utf-8-sig') as f:csv.writer(f).writerows(diary)

def image_originals():
    def page(name,title,subtitle,lines):
        im=Image.new('RGB',(1500,1500),'#f2f4f5');draw=ImageDraw.Draw(im)
        draw.rectangle((0,0,1500,150),fill='#243b4a');draw.text((52,36),title,font=screen_font(36,True),fill='white')
        draw.text((52,99),subtitle,font=screen_font(24),fill='#dbe5eb')
        y=192
        for speaker,stamp,body in lines:
            wrapped=[]
            for paragraph in body.split('\n'):wrapped.extend(textwrap.wrap(paragraph,86) or [''])
            height=90+len(wrapped)*32
            draw.rounded_rectangle((48,y,1452,y+height),radius=9,fill='white',outline='#c9d1d6',width=2)
            draw.text((72,y+18),speaker,font=screen_font(26,True),fill='#203341')
            draw.text((1080,y+20),stamp,font=screen_font(22),fill='#526574')
            for j,line in enumerate(wrapped):draw.text((72,y+62+j*32),line,font=screen_font(26),fill='#17242c')
            y+=height+24
        draw.text((52,1450),'SW-HI-26-08 · Projektarchiv Steinbogen Wohnen',font=screen_font(20),fill='#526574')
        meta=PngImagePlugin.PngInfo();meta.add_text('Author','Klotzkette');meta.add_text('Description',title)
        im.save(CASE/name,pnginfo=meta)
    page('151_Planstandportal_2027-09-24.png','Projektablage Wohnhof Am Steinbogen','Planregister · gespeicherte Ansicht vom 24.09.2027 16:42',[
      ('Nora Feld · Ausführung','24.09. 16:42','LP01 / GP01 / GP02 / SP01: koordinierter Stand nach Genehmigung. BF01 und TE01 gehören zum Anlagenverzeichnis. Ausgabe an die ausführenden Firmen über die Vergabeunterlagen.'),
      ('Detailplanung AP02','21.08. 14:18','Schwellenanschluss und Deckendurchbruch: zur Ausführung freigegeben. Bauteilmaße vor Ort kontrollieren. Anschluss und Durchdringung vor dem Verdecken dokumentieren.'),
      ('Planregister zur Vergabe','24.09. 16:35','Die Abgabe 24.09.2027 umfasst den beschriebenen Ausführungsstand. Frühere Koordinationsfassungen bleiben im Archiv. Ein geänderter Plan ersetzt keinen erforderlichen Nachtragsauftrag.'),
      ('Maren Birk · Versand','24.09. 16:39','Vergabeunterlagen können mit diesem Register versandt werden. Vertragsunterschriften erfolgen durch die Geschäftsführung. Technische Rückfragen bitte gesammelt über Frau Feld.')])
    page('152_Bauleiterchat_2028-02-02.png','Baustelle Wohnhof Am Steinbogen','Gespeicherter Gesprächsverlauf · 02.02.2028',[
      ('Timo Wendt','02.02. 08:17','Im südöstlichen Bereich tritt Wasser in die feine Sandschicht. Wir lassen diese Ecke offen und sichern den Aushub. Zwei Leute arbeiten zunächst im Westen weiter.'),
      ('Nora Feld','02.02. 08:24','Bitte genaue Lage aufnehmen. Frau Venn kommt zum Termin. Keine zusätzliche dauerhafte Wasserhaltung beginnen, bevor Konzept und Zulässigkeit geklärt sind.'),
      ('Maren Birk','02.02. 09:02','Ich bin zur Besprechung da. Bitte ein getrenntes Angebot für die konkret nötigen Arbeiten. Meine Entscheidung folgt nach technischer und preislicher Prüfung.'),
      ('Timo Wendt','02.02. 09:11','Verstanden. Der Bagger bleibt heute vor Ort. Nicht alle Beschäftigten stehen still. Ich schreibe die tatsächlich betroffenen Stunden getrennt auf.')])

if __name__=='__main__':
    image_originals()
    build_records(documents())
    tabular_originals()
    print(f'{len(RECORDS)} Originaldokumente und zwei CSV-Dateien geschrieben.')
