"""Technische Betriebs- und Übergabeunterlagen des Hildesheimer Wohnhauses.

Sachprüfung der dokumentierten Verfahren (27.09.2026):
REHAU, RAUTITAN technische Information, Abschnitt 08.02.02, formstabile
Metallverbundrohre: https://www.rehau.com/downloads/516056/technische-information-rautitan.pdf
DKE/UK221.1, Mindestinhalte eines Prüfberichts: Ergebnisse für alle Stromkreise,
bewertungsrelevante Werte, keine Verpflichtung zur Wiedergabe jedes Einzelwerts:
https://www.dke.de/de/arbeitsfelder/core-safety/normenhinweise/dke-uk-221-1-zu-mindestinhalte-eines-pruefberichts
Die Quellen plausibilisieren das Verfahren, nicht die frei entworfenen Projektmesswerte.
"""
import csv
from bauwirtschaft_hildesheim_common import ACTORS, CASE, build_records, euro

ACTORS['pruefstelle']=('Vertikalsicher Prüfgesellschaft mbH','Prüfhof 8, 30159 Hannover','aufzug@vertikalsicher.example','Dr. Anton Lahr, zugelassene Überwachungsstelle')

def record(n,name,date,actor,title,sections):
    return dict(number=n,filename=f'{n:03d}_{name}.pdf',date=date,issuer=actor,recipient='bauherr',title=title,sections=sections)

def documents():
    return [
      record(61,'Auflagen_und_Schlussunterlagen','2028-09-22','architekt','Stand der Genehmigungsauflagen und Schlussunterlagen',[
        'Für die Fertigstellungsmitteilung werden die nachstehenden Unterlagen dem Genehmigungsvorgang zugeordnet. Die Liste unterscheidet den vorgelegten Nachweis von einer eigenen behördlichen Prüfung. Der Umfang der Baugenehmigung wird nicht auf außerhalb ihres Prüfprogramms liegende Ausführungsfragen ausgedehnt.',
        ('t',[['Gegenstand','Vorgelegte Unterlage','Stand'],['Genehmigung und Planänderungen','022 sowie freigegebene Pläne und 150','Ausführung mit Genehmigungsstand abgeglichen'],['Barrierefreie Erschließung','017, 024, 150 und Abschlussaufmaß','Aufzug, R-Wohnung und stufenlose Zugänge hergestellt'],['Außenanlagen','028 und Unternehmerdokumentation','30m² Spielbereich, Fahrrad- und Pkw-Flächen hergestellt'],['Energie und Heizung','016, 162, 163','Ergebnisbericht, Einstell- und Prüfblätter vorhanden'],['Elektro PV Ladepunkte','165, 166','Prüf- und Inbetriebnahmeberichte vorhanden'],['Aufzug','167','Prüfung vor Inbetriebnahme ohne offenen sicherheitsrelevanten Befund'],['Betreiberorganisation','062 und 168; Register169 folgt','Wartungszuständigkeit übergeben; Zählerablesung und Register zur Wohnungsübergabe am29.09.2028']],[115,185,195]),
        'Der tatsächliche Brandschutz- und Rettungswegstand wurde mit den verantwortlichen Fachleuten vor der Nutzung begangen. Zufahrten und anleiterbare Bereiche bleiben frei. Nutzungsänderungen, zusätzliche Terrassen oder nachträgliche Einbauten sind nicht durch diese Schlussunterlagen freigegeben.',
        'Die Unterlagen werden der Bauherrin und ihrer Mietverwaltung ausgehändigt. Die Bauherrin veranlasst die erforderlichen Mitteilungen an die Bauaufsicht. Diese Aufstellung erklärt keine behördliche Schlussabnahme und keinen Verzicht auf noch nicht erkennbare Mängel.'
      ]),
      record(162,'Energie_Ergebnisbericht','2028-09-05','energie','Ergebnisbericht zur Energieplanung und Heizleistung',[
        'Der Bericht dokumentiert den fortgeschriebenen Energiestand des Wohnhauses nach den freigegebenen Gebäude- und Anlagendaten. Er fasst das Ergebnis der Fachplanung für die Übergabe zusammen. Die Ergebnisgrößen beziehen sich auf das gesamte Gebäude; Wohnfläche, energetische Bezugsfläche und Bruttogrundfläche dürfen nicht gleichgesetzt werden.',
        ('t',[['Größe','Ansatz'],['Wohnfläche','600,00m²'],['Energetische Bezugsfläche des Rechenmodells','720,00m²'],['Bruttogrundfläche','820,00m²'],['Referenz Primärenergiebedarf','95,00kWh/(m²·a)'],['Projekt Primärenergiebedarf','39,40kWh/(m²·a)'],['55Prozent des Referenzwerts','52,25kWh/(m²·a)'],['Projektwert für das gesamte Gebäude','28.368kWh/a'],['Vereinbarte Wärmepumpenanlage','Kaskade aus2Geräten mit je18kW nominaler Heizleistung'],['PV-Anlage','80Module je450Wp,36kWp']],[330,165]),
        'Die angesetzte Heizlast der Wohnungen beträgt zusammen27,20kW. Der zugehörige Anlagenabgleich berücksichtigt die erforderlichen Zuschläge und die Warmwasserbereitung. Die Nennleistung von36kW ist keine Behauptung einer bei jeder Außenlufttemperatur unveränderten Geräteleistung. Der Betriebspunkt und die Leistungskennlinien gehören zur Geräteauswahl der TGA-Planung.',
        'Die ausgewiesenen Werte sind Ergebnisgrößen des datierten Fachplanungsstands. Sie ersetzen weder die vollständigen Rechendateien noch einen Energieausweis. Für Änderungen an Hülle, Nutzung oder Anlagen ist die Berechnung fortzuschreiben. Die endgültige gesetzliche Einordnung richtet sich nach dem für Bauantrag und Ausführung maßgeblichen zeitlichen Recht.'
      ]),
      record(163,'HLS_Einstellung_und_Pruefung','2028-09-06','hls','Einstellblatt HLS08 und Prüfblätter HLS09 bis HLS10',[
        'Am06.09.2028 wurden die hydraulischen Einstellungen und die dokumentierten Prüfungen der Heizungs- und Sanitärinstallation abgeschlossen. Verantwortlich ist Arne Thiel. Die Werte gelten für den beschriebenen Anlagenzustand vor Bezug und werden nach Beginn des regulären Betriebs auf Grundlage der Messwerte überprüft.',
        ('h','HLS09: Wohnungsweise hydraulische Einstellung'),
        ('t',[['Wohnung','Heizlast kW','Volumenstrom l/h','Wärmezähler'],['01','3,10','533','SW-H-01'],['02','3,40','585','SW-H-02'],['03','3,70','636','SW-H-03'],['04','3,10','533','SW-H-04'],['05','3,40','585','SW-H-05'],['06','3,70','636','SW-H-06'],['07','3,40','585','SW-H-07'],['08','3,40','585','SW-H-08'],['Gesamt','27,20','4.678','Acht getrennte Messstellen']],[80,110,130,175]),
        'Die Sollwerte beruhen auf dem abgeglichenen Netz und einer Auslegungsspreizung von5K. Der gerundete Gesamtvolumenstrom stimmt mit27,20kW geteilt durch1,163kWh/(m³·K) und5K überein. Die Warmwasserladung wird vorrangig gesteuert. Die Heizkurve ist zunächst auf32°C Vorlauf bei0°C Außentemperatur und auf38°C bei der vorgesehenen niedrigen Auslegungstemperatur eingestellt.',
        'Die Verwaltung erhält die Einstellwerte und den Wartungskontakt. Sie soll Störungen und spätere Regelungsänderungen im Betriebsbuch festhalten. Eine rein sommerliche Inbetriebnahme bestätigt noch nicht das Verhalten in jeder späteren Heizsituation.',
        ('page',),('h','Prüfblatt HLS10: Dichtheit und Inbetriebnahme am06.09.2028'),
        'Prüfer: Arne Thiel. Druckmessgerät WF-DP-28, Anzeigeauflösung0,1bar, Funktionskontrolle vor Beginn. Die nachstehenden Werte betreffen die abschließende Prüfung der bezeichneten zugänglichen Rohrnetzabschnitte vor Bezug. Armaturen und Geräte, deren zulässiger Prüfdruck niedriger liegt, waren für die Rohrnetzprüfung getrennt. Die Prüfung bewertet keine unzugänglichen Einzelverbindungen durch bloße Sichtkontrolle.',
        ('t',[['Abschnitt / Medium','Zeiten / Temperatur','Druck Anfang / Ende','Befund'],['Heizungsverteilung und Heizkreise; aufbereitetes Füllwasser','08:00 bis10:00; Wasser20°C, Raum21°C','3,0 /3,0bar','Kein erkennbarer Druckverlust; zugängliche Anschlüsse trocken'],['Kaltwasser Rohrnetz; gefiltertes Trinkwasser','10:30 bis11:10; Wasser18°C, Raum21°C','11,0 /11,0bar','Anpassung10min; danach30min Prüfung ohne Nachpumpen'],['Warmwasser und Zirkulation, kalt geprüft; gefiltertes Trinkwasser','11:30 bis12:10; Wasser19°C, Raum21°C','11,0 /11,0bar','Anpassung10min; danach30min Prüfung ohne Nachpumpen']],[145,145,90,115]),
        'Das Trinkwasserrohrnetz ist als formstabiles Metallverbundsystem ausgeführt. Der Prüfablauf umfasst den Druckaufbau, zehn Minuten Anpassung, Wiederherstellung des Anfangsdrucks und die anschließende halbstündige Beobachtung. Die aufgezeichneten Werte sind anlagenbezogene Messdaten; sie sind keine allgemeine Prüfanweisung für andere Rohrsysteme oder angeschlossene Geräte.',
        'Nach der Prüfung wurden Prüfeinrichtungen entfernt, die getrennten Betriebsarmaturen wieder angeschlossen und die Trinkwasserleitungen abschnittsweise gespült. Um14:30Uhr betrug die Temperatur am Warmwasseraustritt61°C und am Zirkulationsrücklauf56°C. Eine mikrobiologische Untersuchung ist durch diese Temperaturmessung nicht nachgewiesen. Die Verwaltung übernimmt ab diesem Tag den dokumentierten Wasserwechsel bis zum Einzug; die Bauherrin beauftragt die für den späteren Betrieb einschlägigen Untersuchungen gesondert.',
        'Heizkreisfüllung, Entlüftung und Betriebsdruck wurden nach der Druckprüfung wiederhergestellt. Die zugänglichen Anschlüsse wurden abschließend kontrolliert. Festgestellter Zustand: keine sichtbare Leckage. Für Wärmefluss: gez.Arne Thiel; zur Übernahme der Betriebsorganisation: gez.Lea Fricke.'
      ]),
      record(164,'Lueftung_Messblatt','2028-09-06','hls','Messblatt L08 zur Wohnungslüftung',[
        'Die nachfolgend angegebenen Luftmengen wurden am06.09.2028 nach Einregulierung der Wohnungslüftung dokumentiert. Die Zuluft- und Abluftsummen beziehen sich auf die jeweilige Wohnung in der vereinbarten normalen Betriebsstufe. Messgerätekennzeichen WF-LM-08, Funktionskontrolle vor Messbeginn durchgeführt.',
        ('t',[['Wohnung','Soll m³/h','Zuluft gemessen','Abluft gemessen'],['01','80','80','79'],['02','90','89','90'],['03','100','100','99'],['04','80','80','81'],['05','90','91','90'],['06','100','99','100'],['07','90','90','89'],['08','90','89','90']],[80,120,145,150]),
        'Die Messwerte werden auf die vereinbarten Sollwerte und den jeweiligen Messzustand bezogen. Die Einstellung der erhöhten Bedarfsstufe wurde zusätzlich an den Bedienelementen erprobt. Die Filter sind zugänglich und wurden der Verwaltung gezeigt. Eine nachträgliche Verdeckung der Zu- oder Abluftöffnungen durch Einbauten ist zu vermeiden.',
        'Es wurden keine die Nutzung ausschließenden Funktionsstörungen festgestellt. Beschwerden über Geräusche oder Zugerscheinungen nach Bezug sind mit Ort, Betriebsstufe und Zeit zu erfassen. Eine spätere Änderung der Nutzung oder der Innenraumaufteilung ist mit dem Lüftungskonzept abzugleichen. Die Unterlage gehört zum technischen Übergabesatz und ist keine pauschale Garantie für sämtliche späteren Betriebsbedingungen.'
      ]),
      record(165,'Elektro_Pruefbericht','2028-09-07','elektro','Prüfbericht E08 zu den elektrischen Anlagen',[
        'Die Prüfung der bezeichneten elektrischen Anlagen wurde am07.09.2028 durch Selin Voß durchgeführt. Dieser Bericht enthält das Stromkreisverzeichnis, die dokumentierten Prüfbedingungen und die für die Bewertung zusammengefassten Messwerte. Er erfasst die acht Wohnungsverteilungen und die nachfolgend bezeichneten Allgemeinstromkreise. Anlagenkennzeichen LK-HI-28-08; Netzsystem TN-S ab Hauptverteilung; Nennspannung230/400V. Messgerät LK-IT-28, Funktionskontrolle vor Beginn durchgeführt.',
        ('t',[['Verteilung','Isolationsmessung MΩ','RCD Auslösezeit ms','Feststellung'],['WE01','größer200','22','Schutzleiterzuordnung geprüft'],['WE02','größer200','21','Beschriftung ergänzt'],['WE03','größer200','23','Ohne offenen Befund'],['WE04','größer200','20','Ohne offenen Befund'],['WE05','größer200','24','Ohne offenen Befund'],['WE06','größer200','21','Ohne offenen Befund'],['WE07','größer200','22','Ohne offenen Befund'],['WE08','größer200','20','Ohne offenen Befund'],['Allgemein','größer200','23','Potentialausgleich kontrolliert']],[85,125,120,165]),
        'Die Isolationsmessung erfolgte mit500V Gleichspannung an den spannungsfreien Leitungen bei getrennten Verbrauchsmitteln und abgetrennten empfindlichen Betriebsmitteln. Angegeben ist je Verteilung der niedrigste ermittelte Wert. Der RCD-Wert bezeichnet die längste gemessene Auslösezeit der zugeordneten30mA-Schutzeinrichtungen bei einfachem Bemessungsdifferenzstrom in den geprüften Halbwellenlagen. Die Werte sind zusammen mit den nachfolgenden Schutzleiter- und Schleifenmessungen bewertet worden.',
        'Vorhandene Beschriftungsmängel der VerteilungWE02 wurden vor Abschluss korrigiert. Die Besichtigung umfasste Leiterzuordnung, Kennzeichnung, zugängliche Klemmstellen, Schutzorgane und Potentialausgleich. Schalterfunktionen und die Zuordnung der Abschaltorgane wurden erprobt. Die Prüfung von PV-Erzeugung und Ladepunkten ist zusätzlich im Bericht PV08 dokumentiert. Spätere Einbauten sind nicht erfasst.',
        ('page',),('h','Stromkreisverzeichnis und bewertete Messwerte'),
        'In jeder Wohnung bestehen die Stromkreise01bis09 nach der folgenden Zuordnung. Das vollständige Kennzeichen lautet beispielsweise WE05-07. Jeder bezeichnete Stromkreis wurde besichtigt, erprobt und gemessen. Schutzleiterdurchgängigkeit, Polarität und Zuordnung waren in allen bezeichneten Stromkreisen gegeben. Die Gruppenwerte darunter nennen jeweils den höchsten gemessenen Widerstand und erlauben die Zuordnung zum geprüften Verteiler.',
        ('t',[['Endnummer','Versorgung','Leitungsschutz','Differenzstromschutz'],['01','Licht Wohnen / Flur','B10A','TypA,30mA'],['02','Licht Schlafen / Bad','B10A','TypA,30mA'],['03','Steckdosen Wohnen','B16A','TypA,30mA'],['04','Steckdosen Schlafräume','B16A','TypA,30mA'],['05','Küche Arbeitssteckdosen','B16A','TypA,30mA'],['06','Herdanschluss, dreiphasig','B16A, dreipolig','TypA,30mA'],['07','Geschirrspüler','B16A','TypA,30mA'],['08','Waschmaschine','B16A','TypA,30mA'],['09','Wohnungslüftung','B10A','TypA,30mA']],[65,215,105,110]),
        ('t',[['Geprüfte Stromkreise','RPE höchstens Ω','Schleife Zs höchstens Ω','Bewertung'],['WE01-01bis09','0,19','0,72','Kein offener Befund'],['WE02-01bis09','0,20','0,74','Nach Beschriftungskorrektur ohne offenen Befund'],['WE03-01bis09','0,21','0,76','Kein offener Befund'],['WE04-01bis09','0,22','0,78','Kein offener Befund'],['WE05-01bis09','0,23','0,80','Kein offener Befund'],['WE06-01bis09','0,24','0,82','Kein offener Befund'],['WE07-01bis09','0,26','0,86','Kein offener Befund'],['WE08-01bis09','0,26','0,86','Kein offener Befund']],[160,90,105,140]),
        ('page',),('h','Allgemeinverteilung und Anlagenanschlüsse'),
        ('t',[['Kennzeichen / Versorgung','Schutzorgan','RPE Ω','Zs Ω','Prüfergebnis'],['A01 Treppenhauslicht','B10A / Typ A, 30mA','0,18','0,68','Ohne offenen Befund'],['A02 Außenlicht','B10A / Typ A, 30mA','0,24','0,81','Ohne offenen Befund'],['A03 Servicesteckdosen','B16A / Typ A, 30mA','0,20','0,74','Ohne offenen Befund'],['A04 Kommunikationsanlage','B10A / Typ A, 30mA','0,16','0,62','Ohne offenen Befund'],['A05 Technikraumlicht','B10A / Typ A, 30mA','0,14','0,58','Ohne offenen Befund'],['A06 Reinigung / Verwaltung','B16A / Typ A, 30mA','0,19','0,71','Ohne offenen Befund'],['T01 Wärmepumpe1, Zuleitung','C25A, dreipolig','0,09','0,30','Zuleitung und Abschaltung geprüft'],['T02 Wärmepumpe2, Zuleitung','C25A, dreipolig','0,09','0,31','Zuleitung und Abschaltung geprüft'],['T03 Aufzug, Zuleitung','C16A, dreipolig','0,13','0,37','Zuleitung und Abschaltung geprüft']],[175,130,50,50,90]),
        'BeiT01bisT03 reicht der dokumentierte Umfang bis zu den Anschlussklemmen der jeweiligen Anlage. Die internen Herstellerstromkreise werden damit nicht zu allgemeinen Hausstromkreisen erklärt. Die anlagenspezifische Inbetriebnahme ist in163und167 dokumentiert. Der für die Allgemeinstromkreise angegebene RCD-Sammelwert gilt fürA01bisA06; er ist keine Aussage, sämtliche AbgängeT01bisT03 hätten identische RCD-Typen.',
        'Die gemessenen Schleifenwerte wurden mit den jeweiligen Schutzorganen und der erforderlichen Abschaltung abgeglichen. Für den ungünstigsten Wohnungsstromkreis beträgt der rechnerische Fehlerstrom bei230V und0,86Ω rund267A; fürT02 bei230V und0,31Ω rund742A. Diese Berechnungen gehören zu der dokumentierten Bewertung des konkreten Anlagenstands; sie ersetzen weder Leitungsbemessung noch eine Prüfung nach einer späteren Änderung.',
        'Die Ergebnisbewertung für die hier bezeichneten Stromkreise lautet: kein offener Befund, der im dokumentierten Prüfungsumfang der vorgesehenen Nutzung entgegensteht. Schutzleiter und Potentialausgleich wurden wieder angeschlossen und abschließend kontrolliert. Der Bericht bestätigt keine unveränderten Bedingungen für spätere Einbauten und keine Abnahme anderer Gewerke. Verantwortliche Elektrofachkraft: gez.Selin Voß.'
      ]),
      record(166,'PV_Ladepunkte_Inbetriebnahme','2028-09-07','elektro','Prüfbericht PV08 und Inbetriebnahme der Ladepunkte',[
        'Die PV-Anlage besteht aus80Modulen mit je450Wp, verteilt auf vier Strings mit je20Modulen. Die installierte Nennleistung beträgt36kWp. Die belegte Modulfläche beträgt160m² bei300m² Gesamtdachfläche des Gebäudes einschließlich beider Dachniveaus. Betreiberin und Leistungsempfängerin ist die Steinbogen Wohnen GmbH.',
        ('t',[['String','Module','Nennleistung kWp','Leerlaufspannung V'],['1','20','9,00','824'],['2','20','9,00','821'],['3','20','9,00','825'],['4','20','9,00','822'],['Gesamt','80','36,00','Vier getrennte Stringmessungen']],[85,105,155,150]),
        'Die Spannungen wurden am selben Vormittag bei vergleichbarer Einstrahlung gemessen. Polarität, Schutzmaßnahmen, Kennzeichnung und Abschaltmöglichkeit wurden kontrolliert. Das abgestimmte Messkonzept sieht Allgemeinstromversorgung und Überschusseinspeisung vor. Es besteht kein Mieterstromliefervertrag mit den einzelnen Wohnungsnutzern. Anmeldung und Zählerzuordnung führt die Betreiberin mit dem Netzbetreiber fort.',
        'Alle acht Pkw-Stellplätze sind vorverkabelt. Zwei Ladepunkte mit jeweils bis zu11kW sind installiert, einer am barrierefreien Stellplatz01. Das Lastmanagement begrenzt den gleichzeitigen Bezug nach der verfügbaren Anschlussleistung. Im Funktionstest wurden beide Ladepunkte einzeln und gemeinsam angefordert; die Leistungsaufteilung reagierte auf die simulierte weitere Hauslast.',
        'Die Unterlage dokumentiert die Inbetriebnahme. Sie garantiert keinen bestimmten Jahresertrag und ersetzt keine laufenden Prüf- und Wartungsaufgaben. Allgemeine Dach-, Elektro- und Ladeleistungen sind von der gesonderten begünstigten Lieferung und Montage der PV-Anlage in der Abrechnung getrennt.'
      ]),
      record(167,'Aufzug_Pruefbescheinigung','2028-09-07','pruefstelle','Prüfbescheinigung A08 vor Inbetriebnahme des Aufzugs',[
        'Geprüft wurde die von Hubpunkt Aufzüge GmbH errichtete Aufzuganlage im Wohnhof Am Steinbogen18, Anlagenkennzeichen HP-HI-28-08. Betreiberin ist die Steinbogen Wohnen GmbH. Die Prüfung vor Inbetriebnahme erfolgte am07.09.2028 durch Dr. Anton Lahr für die bezeichnete Überwachungsstelle.',
        ('t',[['Anlagendaten','Feststellung'],['Nennlast','630kg'],['Haltestellen','Drei, EG bis2.OG'],['Nutzbare Kabine','1,10m mal1,40m'],['Lichte Türbreite','0,90m'],['Notruf','Zweirichtungsverbindung getestet'],['Türen und Verriegelung','Funktion im Prüfablauf kontrolliert'],['Befreiung und Notbetrieb','Vorgehen mit Montagefirma und Verwaltung erprobt'],['Ergebnis','Kein offener sicherheitsrelevanter Mangel im geprüften Umfang']],[220,275]),
        'Die Anlage kann nach dem dokumentierten Ergebnis bestimmungsgemäß in Betrieb genommen werden. Der Betreiber hat die laufenden Pflichten einschließlich Wartung, Notrufbereitschaft, erforderlicher Kontrollen und fristgerechter wiederkehrender Prüfungen zu organisieren. Änderungen an der Anlage sind vor ihrer Nutzung fachlich und rechtlich einzuordnen.',
        'Die Bescheinigung betrifft die Aufzugsanlage und den bezeichneten Prüfungsumfang. Sie ist keine Baugenehmigung und keine Abnahme sämtlicher Bauleistungen. Die Prüfunterlagen werden im Anlagenbuch aufbewahrt; eine Ausfertigung erhält die Betreiberin.'
      ]),
      record(168,'Wartungsvereinbarung_Technik','2028-09-22','bauherr','Wartungsvereinbarung für Wärmepumpen und Lüftung',[
        'Steinbogen Wohnen GmbH beauftragt Wärmefluss Haustechnik GmbH ab01.10.2028 mit der laufenden Wartung der zwei Wärmepumpen, der zugehörigen Regelung und der Wohnungslüftung. Der Vertrag beginnt nach der Bauabnahme. Er ist ein gesonderter Betriebsvertrag und erweitert nicht rückwirkend die vereinbarte Bauvergütung.',
        'Die erste planmäßige Wartung findet im September2029 statt. Die jährliche Vergütung beträgt1.800,00EUR netto zuzüglich gesetzlicher Umsatzsteuer. Enthalten sind die vereinbarte Sicht- und Funktionskontrolle, die Überprüfung dokumentierter Einstellwerte, die Reinigung der nach Herstellerangaben zugänglichen Anlagenteile sowie ein schriftlicher Wartungsbericht. Ersatzteile und darüber hinausgehende Reparaturen werden nur nach gesonderter Abstimmung berechnet.',
        'Die Firma meldet erkennbare Betriebsstörungen und empfiehlt erforderliche zusätzliche Prüfungen mit konkretem Anlass. Gesetzlich erforderliche Betreiberprüfungen bleiben von der technischen Wartung zu unterscheiden. Die Verwaltung stellt Zugang und vorhandene Betriebsdaten bereit. Der Vertrag verschiebt keine Mängelansprüche aus dem Bauvertrag und schließt sie nicht aus.',
        'Die Vereinbarung läuft zunächst bis30.09.2029 und verlängert sich jeweils um ein Jahr, sofern sie nicht mit einer Frist von drei Monaten zum jeweiligen Laufzeitende gekündigt wird. Das Recht zur außerordentlichen Kündigung aus wichtigem Grund bleibt bestehen. Für die Bauherrin gez.Maren Birk; für Wärmefluss gez.Arne Thiel.'
      ]),
    ]

def build():
    # Einheitliche lesbare Trennung von Zahlen und Einheiten.
    records=[]
    import re
    def norm(x):
        if isinstance(x,str):
            x=re.sub(r'(?<=\d)(?=[a-zA-ZäöüÄÖÜß])',' ',re.sub(r'(?<=[a-zäöüß])(?=\d)',' ',x))
            x=re.sub(r'(?<=[a-zäöüß])(?=(?:WE|T|A)\d)',' ',x)
            x=re.sub(r'(?<=[A-Za-z])([,;])(?=\S)',r'\1 ',x)
            return x.replace('TypA30','Typ A, 30').replace('TypA','Typ A').replace('gez.','gez. ')
        return type(x)(norm(y) for y in x) if isinstance(x,(tuple,list)) else x
    for d in documents():d['sections']=norm(d['sections']);records.append(d)
    build_records(records)
    rows=[['Wohnung','Stromzähler','Strom_kWh','Kaltwasserzähler','Kaltwasser_m3','Warmwasserzähler','Warmwasser_m3','Wärmezähler','Wärme_MWh','Ablesedatum']]
    for n in range(1,9):rows.append([f'{n:02d}',f'SW-E-{n:02d}',f'{12+n*3:.1f}',f'SW-K-{n:02d}',f'{1.2+n*.1:.1f}',f'SW-W-{n:02d}',f'{.6+n*.1:.1f}',f'SW-H-{n:02d}',f'{.040+n*.003:.3f}','2028-09-29'])
    with (CASE/'169_Zaehlerregister_Bezug.csv').open('w',encoding='utf-8-sig',newline='') as f:csv.writer(f).writerows(rows)

if __name__=='__main__':build()
