"""Drei fiktive Berliner Versammlungsakten; nur Datenspezifikation."""
from berlin_bildungsakten_daten import D,E,T,X
PLUGIN='berliner-versammlungsrecht'
CASES=[]
CASES.append(dict(slug='berlin-versammlung-fahrradkorso',title='Klingelzeichen für sichere Schulwege',plugin=PLUGIN,date='02.10.2026',client='Initiative Klingelzeichen, vertreten durch Selma Aydin',summary='Eine Nachbarschaftsinitiative plant einen ruhigen Fahrradkorso. Eine veraltete Baustelleninformation, unterschiedliche Routenversionen und ein Lieferfenster beschäftigen Leitung und Behörde.',assignment='Selma möchte ein freundliches bestimmtes Änderungsschreiben zur angeordneten Route. Ein gerichtlicher Eilantrag soll nur vorbereitet werden, falls die Behörde nicht rechtzeitig abhilft.',attachments={'03_Anzeige_gesendet.eml':['02_Anzeige_Entwurf.docx'],'17_Freigabe_Bauleitung.eml':['16_Bauleitung_Freigabe.docx']},documents=[
D('01_Auftrag_Selma.docx','Fahrradkorso am 10. Oktober','02.10.2026','Selma Aydin\nInitiative Klingelzeichen, Berlin','Rechtsanwältin Jule Morgen\nKanzlei am Kanal', '''Sehr geehrte Frau Morgen,

wir möchten am Samstag, dem 10. Oktober, mit ungefähr achtzig Menschen auf Fahrrädern für sichere Schulwege werben. Viele Kinder fahren mit ihren Eltern mit. Es geht um die fehlende sichere Querung an der Schillerpromenade und nicht um eine sportliche Ausfahrt. Die Redebeiträge sollen zusammen etwa zwanzig Minuten dauern. Ich leite die Versammlung; mein Nachbar Eberhard Pfützenreuter kümmert sich um die Ordnerinnen und Ordner.

Gestern kam ein Bescheid, der unseren Weg auf einen entfernten Straßenabschnitt verlegt. Als Grund wird eine Baustelle genannt. Die Bauleitung hat uns heute schriftlich bestätigt, dass die Fahrbahn am kommenden Mittwoch wieder vollständig offen sein soll. Ich weiß nicht, ob diese Mitteilung der Polizei bereits vorliegt. Der Baustellenplan in unserem ersten Mailanhang war noch älter.

Bitte entwerfen Sie zunächst ein freundliches, aber klares Schreiben, mit dem wir die ursprüngliche Strecke wieder erreichen können. Falls die Behörde nicht rechtzeitig reagiert, möchten wir wissen, was ein Eilantrag kosten würde und welche Unterlagen dafür noch fehlen. Bitte reichen Sie heute noch nichts bei Gericht ein.

Wir haben bisher keine öffentliche Ankündigung geändert. Die Eltern sollen eine verlässliche Strecke bekommen. Eine Route durch enge Seitenstraßen mit Gegenverkehr halte ich praktisch für schwieriger. Die Uhrzeit könnten wir dagegen um eine halbe Stunde nach hinten verschieben. Unser Anliegen direkt an der Querungsstelle zu zeigen, bleibt uns besonders wichtig. Den Ordnerplan habe ich noch nicht endgültig bestätigt.

Mit freundlichen Grüßen
Selma Aydin'''),
D('02_Anzeige_Entwurf.docx','Anzeige Klingelzeichen','18.09.2026','Selma Aydin\nInitiative Klingelzeichen','Polizei Berlin\nVersammlungsbehörde', '''Hiermit zeige ich für Samstag, den 10.10.2026, eine öffentliche Versammlung unter freiem Himmel zum Thema „Sichere Schulwege im Schillerkiez“ an. Die Sammlung beginnt um 14.00 Uhr an der Ecke Herrfurthstraße und Schillerpromenade. Nach einer zehnminütigen Begrüßung soll ein Fahrradkorso auf der Schillerpromenade bis zur Leinestraße und auf derselben Achse zurück stattfinden. Für die Abschlusskundgebung am Ausgangspunkt sind weitere zehn Minuten vorgesehen. Um 15.30 Uhr soll die Versammlung beendet sein.

Wir rechnen mit achtzig Personen. Es nehmen voraussichtlich auch Kinder auf eigenen Fahrrädern, in Kindersitzen und in Lastenrädern teil. Die Fahrgeschwindigkeit soll Schrittgeschwindigkeit nicht wesentlich überschreiten. Niemand wird zum schnellen Fahren aufgefordert. Die Wortbeiträge behandeln zwei konkrete Querungssituationen auf dem Weg zur Schule und die Nutzung des Straßenraums durch Familien.

Veranstalterin und Leiterin bin ich, Selma Aydin. Meine Anschrift lautet Bürgerstraße 18, 12347 Berlin. Schriftlich erreichen Sie mich unter selma@klingelzeichen.example. Für Rückfragen zur Strecke steht auch Eberhard Pfützenreuter unter organisation@klingelzeichen.example zur Verfügung. Er ist bislang nicht als Ersatzleiter benannt.

Vorgesehen sind acht gekennzeichnete Ordnerinnen und Ordner. Ein kleines batteriebetriebenes Megafon wird ausschließlich bei den beiden Kundgebungen benutzt. Musikverstärkung, Verkaufsstände und Aufbauten sind nicht vorgesehen. Einen aktualisierten Streckenplan reichen wir nach dem Gespräch über die Baustelle nach. Die erste öffentliche Einladung soll am Montag, dem 21. September, um 18.00 Uhr versandt werden. Bitte bestätigen Sie den Eingang unserer Anzeige und nennen Sie uns einen Termin für die Abstimmung.'''),
E('03_Anzeige_gesendet.eml','Anzeige Klingelzeichen 10.10.2026','2026-09-18T15:04:00+02:00','Selma Aydin <selma@klingelzeichen.example>','Versammlungsstelle <anzeige@polizei-berlin.example>','Sehr geehrte Damen und Herren,\n\nanbei unsere Anzeige. Die Einladung ist für Montagabend vorgesehen. Ich kann dienstags zwischen 11 und 13 Uhr gut telefonieren.\n\nMit freundlichen Grüßen\nSelma Aydin'),
E('04_Eingang_Behoerde.eml','VK-26-1010-72 Eingang','2026-09-18T15:11:00+02:00','Versammlungsstelle <anzeige@polizei-berlin.example>','Selma Aydin <selma@klingelzeichen.example>','Ihre Anzeige ist eingegangen und wird unter VK-26-1010-72 bearbeitet. Diese Nachricht bestätigt ausschließlich den Eingang. Die Abstimmung zur Strecke folgt gesondert. Bitte verwenden Sie das Geschäftszeichen bei Ergänzungen.'),
T('05_Chat_Einladung.txt','Chat der Initiative','21.09.2026','21.09.2026 17:31 Selma: Der Entwurf ist fertig. Noch nicht weiterleiten.\n21.09.2026 18:02 Eberhard: Jetzt steht der Aufruf auf unserer Seite.\n21.09.2026 18:05 Noor: In der Elterngruppe ist der Link auch angekommen.\n21.09.2026 18:09 Selma: Danke. Achtet bitte darauf: Samstag 10. Oktober, nicht schon nächstes Wochenende.\n21.09.2026 18:12 Noor: Im kleinen Bild fehlt das Wort Rückweg. Ich korrigiere den Text darunter, das Bild tausche ich morgen.'),
D('06_Streckenkonzept.docx','Strecke und kommunikative Stationen','23.09.2026','Initiative Klingelzeichen','Interne Organisation und Versammlungsstelle', '''Unser Korso bezieht sich auf zwei Schulwegquerungen an der Schillerpromenade. Die erste Station liegt am Ausgangspunkt bei der Herrfurthstraße. Dort berichtet eine Mutter darüber, dass ihr Kind zwischen parkenden Lieferwagen die Fahrbahn schlecht einsehen kann. An der zweiten Station in Richtung Leinestraße wollen zwei Jugendliche ihre selbst gezeichnete Karte erläutern. Die genaue Halteposition stimmen wir so ab, dass Einfahrten und Rettungswege frei bleiben.

Die Gruppe fährt gemeinsam in ruhigem Tempo. Es gibt keinen sportlichen Wettbewerb und keine unangekündigten Abzweigungen. Wir erwarten etwa achtzig Fahrräder und rechnen für längere Lastenräder mit zusätzlichem Platz. Die Ordner helfen beim Zusammenbleiben und geben Rückmeldungen an die Leitung. Verkehrsregelnde Maßnahmen gegenüber anderen Verkehrsteilnehmern übernehmen sie nicht selbständig.

Die in einer ersten Skizze eingezeichnete Passage durch die Kienitzer Straße ist nicht mehr vorgesehen. Dieses Blatt trug noch die Kennzeichnung Fassung 0.3. Maßgeblich ist jetzt die gerade Strecke auf der Schillerpromenade mit Rückkehr zum Ausgangspunkt. Der Korso soll nicht durch die engen Nebenstraßen geführt werden, weil dort Begegnungen mit entgegenkommenden Autos und parkenden Fahrzeugen schwieriger einzuschätzen sind.

Falls die Querung während einer Anlieferung kurzzeitig frei bleiben muss, können wir eine Wartephase vor dem Beginn vereinbaren. Eine Verschiebung des Starts auf 14.30 Uhr erscheint uns organisatorisch möglich. Dafür müssten wir die Eltern rechtzeitig informieren. Die beiden Wortbeiträge und der Bezug zu den Querungsstellen sollen erhalten bleiben. Ein bloßes Treffen auf einem weit entfernten Platz würde das Anliegen deutlich anders vermitteln.'''),
E('07_Einladung_Kooperation.eml','Abstimmung am 29. September','2026-09-25T10:20:00+02:00','Versammlungsstelle <anzeige@polizei-berlin.example>','Selma Aydin <selma@klingelzeichen.example>','Sehr geehrte Frau Aydin,\n\nbitte kommen Sie am 29. September um 11 Uhr zur telefonischen Abstimmung. Nach dem bislang vorliegenden Bauplan ist ein Teil der Schillerpromenade bis 12. Oktober gesperrt. Außerdem besteht samstags ein Lieferfenster. Können Sie eine alternative Strecke benennen?\n\nVersammlungsstelle'),
D('08_Notiz_Kooperationsgespraech.docx','Telefonat zur Route','29.09.2026','Selma Aydin','Persönliche Ablage', '''Das Gespräch begann um 11.04 Uhr und dauerte ungefähr dreißig Minuten. Eberhard hörte über Lautsprecher mit. Die Mitarbeiterin der Versammlungsstelle nannte eine Sperrung bis zum 12. Oktober. Ich sagte, dass auf dem Schild an der Baustelle inzwischen der 7. Oktober stehe. Ein Foto hatte ich während des Gesprächs nicht vorliegen. Die Mitarbeiterin bat um eine schriftliche Mitteilung der Bauleitung.

Als Alternative wurde ein Abschnitt rund achthundert Meter vom geplanten Beginn entfernt genannt. Ich erklärte, dass dort die beiden betroffenen Schulwegquerungen nicht sichtbar seien. Eberhard brachte eine kürzere Schleife auf der ursprünglichen Achse ins Gespräch. Darüber wurde noch keine Einigung erzielt. Die Mitarbeiterin kündigte an, die zuständige Verkehrsdienststelle zu beteiligen. Ein weiterer Anruf wurde nicht fest vereinbart.

Zur Lautstärke sagte ich, dass wir ein kleines Megafon und keine Musik benutzen wollen. Die Mitarbeiterin bat darum, das Gerät von den Hauseingängen weg auszurichten. Eine bestimmte Dezibelzahl wurde nicht genannt. Über eine verbindliche Begrenzung der Zahl der Teilnehmenden wurde ebenfalls nicht gesprochen. Die erwarteten achtzig Personen sind unsere Schätzung, keine Anmeldegrenze.

Zum Lieferfenster konnte niemand genaue Zeiten nennen. Ich bot einen Beginn um 14.30 Uhr an, sofern die Familien davon rechtzeitig erfahren. Eine Zusage dazu gab es nicht. Am Ende sagte ich ausdrücklich, dass wir die Ausweichroute erst innerhalb der Gruppe besprechen müssten. Ich habe weder die ursprüngliche Strecke zurückgenommen noch einen Verzicht auf eine rechtliche Prüfung erklärt. Wir wollten zunächst die neue Baustelleninformation beschaffen.'''),
D('09_Bescheid_Route.docx','Beschränkung der angezeigten Versammlung','01.10.2026','Polizei Berlin\nVersammlungsbehörde','Selma Aydin\nBürgerstraße 18, 12347 Berlin', '''Zur angezeigten Versammlung VK-26-1010-72 wird folgende Regelung getroffen: Die Nutzung des in der Anzeige bezeichneten Abschnitts der Schillerpromenade wird untersagt. Die Versammlung ist auf dem in Anlage R bezeichneten Ausweichabschnitt als ortsfeste Kundgebung durchzuführen. Die übrigen angezeigten Zeiten bleiben unverändert. Die sofortige Vollziehung dieser Regelung wird angeordnet.

Die Regelung beruht auf § 14 Absatz 1 des Versammlungsfreiheitsgesetzes Berlin. Nach dem hier vorliegenden Bauzeitenplan vom 12. September besteht die Fahrbahnsperrung bis zum 12. Oktober. Zusammen mit dem samstäglichen Lieferverkehr steht auf der geplanten Strecke kein ausreichender Raum für einen Fahrradkorso zur Verfügung. Ein kurzfristiges Anhalten der Anlieferungen wurde mit dem verantwortlichen Betrieb bislang nicht verbindlich vereinbart. Aus Sicht der beteiligten Stelle drohen unübersichtliche Begegnungen im verbliebenen Verkehrsraum.

Die Ausweichfläche liegt ungefähr achthundert Meter südöstlich des angekündigten Ausgangspunkts. Dort können die Wortbeiträge gehalten und die mitgebrachten Karten gezeigt werden. Die Regelung ist nach gegenwärtiger Einschätzung erforderlich, um die geschilderten Gefahren zu vermeiden. Eine spätere Freigabe der Baustelle wurde angekündigt, aber bisher nicht belegt. Der Schutz der Teilnehmenden und die Freihaltung der verbleibenden Zufahrt erfordern eine Entscheidung vor der Veranstaltung.

Die sofortige Vollziehung wird wegen dieser konkreten Gefahrenlage und der zeitnah bevorstehenden Versammlung angeordnet. Ein Abwarten des Rechtsbehelfsverfahrens würde die erforderliche Umplanung offenlassen. Gegen diesen Bescheid kann innerhalb eines Monats nach Bekanntgabe Widerspruch bei der Polizei Berlin eingelegt werden. Ein Antrag auf Wiederherstellung der aufschiebenden Wirkung kann beim Verwaltungsgericht Berlin gestellt werden.

Versammlungsbehörde, schriftliche Ausfertigung ohne Unterschriftsabbildung''',reference='VK-26-1010-72'),
E('10_Zugang_Bescheid.eml','VK-26-1010-72 Bescheid','2026-10-01T16:42:00+02:00','Versammlungsstelle <anzeige@polizei-berlin.example>','Selma Aydin <selma@klingelzeichen.example>','Sehr geehrte Frau Aydin,\n\nder Bescheid wird Ihnen auf dem vereinbarten elektronischen Weg übermittelt. Bitte bestätigen Sie den Eingang. Die bezeichnete Ausweichfläche ist der in der heutigen PDF-Skizze markierte Abschnitt.\n\nVersammlungsstelle'),
X('11_Routen_und_Ablauf.xlsx','Planungsstände und Ablauf',[dict(name='Ablauf',headers=['Teil','Beginn','Ende','Minuten','Stand'],widths=[30,15,15,16,40],formats={'B':'hh:mm','C':'hh:mm','D':'0'},rows=[['Begrüßung','=TIME(14,0,0)','=TIME(14,10,0)','=ROUND((C2-B2)*1440,0)','Anzeige vom 18. September'],['Korso','=C2','=TIME(15,20,0)','=ROUND((C3-B3)*1440,0)','Rückweg enthalten'],['Abschluss','=C3','=TIME(15,30,0)','=ROUND((C4-B4)*1440,0)','Ende weiterhin 15.30 Uhr'],['Gesamt',None,None,'=SUM(D2:D4)','Ursprünglicher Zeitplan']],expected={'D5':90},perturbations=[{'input':'C4','value':15.75/24,'output':'D5','expected':105}]),dict(name='Ordner',headers=['Bereich','Geplant','Bestaetigt','Offen','Hinweis'],widths=[32,15,16,15,48],formats={'B':'0','C':'0','D':'0'},rows=[['Spitze',2,2,'=B2-C2','Eberhard und Noor'],['Mitte',4,3,'=B3-C3','Eine Rückmeldung fehlt'],['Schluss',2,1,'=B4-C4','Eine Person nur bis 15 Uhr'],['Gesamt','=SUM(B2:B4)','=SUM(C2:C4)','=SUM(D2:D4)','Keine verbindliche Mindestvorgabe']],expected={'D5':2})]),
D('12_Ordnerbriefing_Entwurf.docx','Entwurf für das Ordnergespräch','30.09.2026','Eberhard Pfützenreuter','Helfergruppe Klingelzeichen', '''Wir treffen uns am Veranstaltungstag vierzig Minuten vor dem Beginn am angekündigten Sammelpunkt. Bitte bestätigen Sie vorher, ob Sie bis zum Ende bleiben können. Die endgültige Strecke ist noch in Abstimmung. Dieser Entwurf soll deshalb erst nach Selmas Rückmeldung an die gesamte Gruppe geschickt werden. Niemand soll eine nicht bestätigte Route eigenständig veröffentlichen.

Unsere Aufgabe ist es, die Teilnehmenden zu informieren, die Gruppe zusammenzuhalten und Selma auf Probleme hinzuweisen. Wir tragen gut sichtbare Westen mit der Bezeichnung Ordnerin oder Ordner. Wir geben anderen Verkehrsteilnehmern keine eigenmächtigen Verkehrszeichen und halten keine Fahrzeuge mit körperlichem Einsatz an. Eine notwendige Regelung des Verkehrs stimmen wir über Selma mit den eingesetzten Polizeikräften ab.

Die Spitze wartet, wenn Kinder oder langsamere Personen zurückbleiben. Der Schluss meldet größere Lücken. Bitte achten Sie darauf, dass niemand versehentlich einem gewöhnlichen Radfahrer folgt, der nicht zu unserer Gruppe gehört. Auf Anwohnerinnen, Fußgänger und Zugänge nehmen wir Rücksicht. Bei medizinischen Problemen wird die Hilfe über den üblichen Notruf und die vor Ort zuständigen Einsatzkräfte organisiert. Ein freier Zugang muss erhalten bleiben.

Wenn jemand den Ablauf erheblich stört, sprechen Sie zunächst ruhig mit der Person und informieren die Leitung. Entscheidungen über einen Ausschluss trifft Selma; wir wollen keine eigenmächtigen körperlichen Auseinandersetzungen. Fotos von Kindern veröffentlichen wir nicht als bloße Organisationsnachricht. Für unsere interne Dokumentation reichen kurze sachliche Notizen zu Ort und Zeit. Zwei zugesagte Personen fehlen noch im Plan. Falls die offenen Positionen nicht besetzt werden, müssen wir die Organisation vor Beginn nochmals durchgehen.'''),
T('13_Chat_Ordnerwechsel.txt','Ordnergruppe am 2. Oktober','02.10.2026','02.10.2026 08:05 Noor: Ich bin sicher dabei und kann auch hinten fahren.\n02.10.2026 08:17 Eberhard: Dann fehlt hinten nur noch jemand für nach 15 Uhr.\n02.10.2026 08:25 Balthasar: Ich hatte bis 15.30 zugesagt, habe aber einen Termin übersehen. Bis 15 geht.\n02.10.2026 08:31 Selma: Bitte noch nichts am veröffentlichten Beginn ändern. Die spätere Startzeit ist nur ein Angebot.\n02.10.2026 08:42 Eberhard: Verstanden. Mein alter Plan mit acht Bestätigungen war zu optimistisch.'),
E('14_Lieferbetrieb.eml','Samstagslieferung am 10. Oktober','2026-10-02T09:30:00+02:00','Kiezkiste Logistik <planung@kiezkiste.example>','Selma Aydin <selma@klingelzeichen.example>','Guten Morgen Frau Aydin,\n\nunsere beiden Lieferwagen brauchen die Zufahrt zwischen 13.30 und voraussichtlich 14.15 Uhr. Ein Ende um 14.00 Uhr kann ich nicht garantieren. Ab 14.30 Uhr ist nach unserem Plan keine Anlieferung mehr vorgesehen. Bitte verstehen Sie dies nicht als Zusage, dass wir die gesamte Straße sperren können.\n\nFreundliche Grüße\nOttilie Karg'),
D('15_Ortsbesichtigung.docx','Beobachtungen an der Baustelle','02.10.2026','Noor Schätzle und Eberhard Pfützenreuter','Initiative Klingelzeichen', '''Wir haben den betroffenen Straßenabschnitt heute zwischen 8.10 und 8.35 Uhr gemeinsam besichtigt. Auf einem Bauhinweisschild war als geplantes Ende Mittwoch, der 7. Oktober, angegeben. Die alte Angabe 12. Oktober war überklebt. Das Schild allein sagt uns allerdings nicht, ob sämtliche Restarbeiten dann abgeschlossen sind oder nur die Fahrbahn wieder frei wird. Wir haben keine verkehrsrechtliche Freigabe vor Ort gesehen.

Die Baustelle nimmt derzeit einen Teil der Fahrbahn ein. Auf dem verbleibenden Streifen begegneten sich während unseres Aufenthalts ein Lieferwagen und zwei Fahrräder. Ein großer Korso wäre in dieser Situation aus unserer Sicht unübersichtlich. Wir möchten gerade nicht behaupten, dass die heutige Baustellenlage unproblematisch ist. Unser Anliegen bezieht sich auf den Zustand am Veranstaltungstag nach der angekündigten Freigabe.

An der Zufahrt des Lieferbetriebs stand ein Mitarbeiter, der uns an das Organisationsbüro verwies. Er konnte den Samstagsplan nicht verbindlich bestätigen. Gegenüber liegt ein Hauseingang, den wir in jedem Fall freihalten wollen. Der Gehweg war heute wegen abgestellter Baugeräte stellenweise schmal. Eine abschließende Aussage zur verfügbaren Breite nach dem Rückbau können wir ohne erneute Besichtigung nicht machen.

Wir haben vier Fotos für die interne Planung aufgenommen. Auf zwei Bildern sind zufällig Passanten erkennbar; diese Bilder haben wir nicht in die Gruppe eingestellt. Die brauchbaren Bilder zeigen das Hinweisschild und den Bauzaun. Wir können die Originale bei Bedarf gesondert zur Verfügung stellen. Für das Schreiben an die Behörde wäre uns eine belastbare Erklärung der Bauleitung lieber als eine eigene Vermessung mit dem Handy.'''),
D('16_Bauleitung_Freigabe.docx','Geplante Verkehrsfreigabe','02.10.2026','Baukoordination Pflasterstern GmbH','Initiative Klingelzeichen und beteiligte Stellen', '''Sehr geehrte Frau Aydin,

nach dem aktuellen Bauablauf werden die Arbeiten auf der Fahrbahn des von Ihnen angefragten Abschnitts der Schillerpromenade bis Mittwoch, den 7. Oktober, um 18.00 Uhr abgeschlossen. Die Baustelleneinrichtung auf der Fahrbahn soll bis zu diesem Zeitpunkt entfernt sein. Der ältere Plan vom 12. September mit einer Sperrung bis zum 12. Oktober ist insoweit überholt. Der Asphaltauftrag ist beendet; es stehen noch Markierungs- und Räumarbeiten aus.

Diese Mitteilung beschreibt unseren gegenwärtigen verbindlichen Arbeitsplan. Unvorhersehbare Witterungsereignisse oder eine gesonderte Anordnung der Straßenverkehrsbehörde können Änderungen erforderlich machen. Wir werden eine solche Abweichung unverzüglich mitteilen. Eine eigene verkehrsrechtliche Erlaubnis für Ihre Veranstaltung erteilen wir mit diesem Schreiben nicht. Die Abnahme des wieder geöffneten Bereichs erfolgt mit der zuständigen Stelle.

Auf dem östlichen Gehweg bleiben voraussichtlich bis zum 12. Oktober zwei kleinere Arbeitsbereiche mit Schutzabsperrung bestehen. Diese betreffen nicht die Fahrbahn, können aber den verfügbaren Fußweg einschränken. Bitte berücksichtigen Sie dies bei einem Sammelpunkt und bei eventuellen Zuschauerflächen. Unsere Restarbeiten sind für den Samstag nicht eingeplant.

Für eine Rückfrage der Polizei oder der zuständigen Verkehrsbehörde steht unser Koordinationsbüro unter bauleitung@pflasterstern.example zur Verfügung. Wir haben die aktualisierte Terminmitteilung heute auch an die bisher im Bauverteiler enthaltenen Ansprechpartner gesandt. Ob Ihre zuständige Versammlungsstelle zu diesem Verteiler gehört, wissen wir nicht. Gerne bestätigen wir nach Abschluss der Räumung nochmals den tatsächlichen Zustand.

Mit freundlichen Grüßen
Baukoordination Pflasterstern GmbH'''),
E('17_Freigabe_Bauleitung.eml','Aktueller Bauablauf im Anhang','2026-10-02T11:12:00+02:00','Baukoordination <bauleitung@pflasterstern.example>','Selma Aydin <selma@klingelzeichen.example>','Sehr geehrte Frau Aydin,\n\nanbei die erbetene schriftliche Mitteilung. Wichtig ist die Unterscheidung zwischen Fahrbahn und östlichem Gehweg. Eine vollständige Räumung sämtlicher Gehwegbereiche bis Mittwoch sagen wir nicht zu.\n\nBaukoordination'),
E('18_Nachtrag_Mandantin.eml','Bitte zuerst die Strecke klären','2026-10-02T12:04:00+02:00','Selma Aydin <selma@klingelzeichen.example>','Jule Morgen <post@kanzlei-kanal.example>','Sehr geehrte Frau Morgen,\n\nich habe den Bescheid gestern um 17.10 Uhr geöffnet und den Eingang bestätigt. Die Anlage R ist die schon besprochene Ausweichfläche. Ich kann die PDF bei Bedarf gesondert senden. Bitte verwenden Sie in Ihrem Schreiben nur die Route aus dem Konzept vom 23. September. Die Kienitzer Straße aus dem alten Bild soll nicht wieder auftauchen.\n\nFreundliche Grüße\nSelma Aydin')]))
CASES.append(dict(slug='berlin-versammlung-spontane-mahnwache',title='Licht für die Kiezbibliothek',plugin=PLUGIN,date='30.09.2026',client='Malou Hagedorn und Farid Ben Youssef',summary='Nach einer überraschenden Schließungsnachricht treffen sich Nachbarn vor einer Bibliothek. Ein älterer Chat betrifft ein anderes Treffen. Nach der Mahnwache geht es um eine Personalienkontrolle und die Frage, ob eine Kamera gespeichert hat.',assignment='Die Mandanten wünschen zunächst ein sachliches Auskunfts- und Sicherungsschreiben. Eine Beschwerde oder Klage ist noch nicht beauftragt. Die tatsächliche Entstehung der Mahnwache soll anhand der Nachrichten aufgeklärt werden.',attachments={'04_Mail_an_Polizei.eml':['03_Anlass_und_Einladung.docx'],'17_Antwort_Kanzlei.eml':['16_Zeugin_Erinnerung.docx']},documents=[
D('01_Auftrag_Mahnwache.docx','Klärung der Ereignisse vor der Bibliothek','30.09.2026','Malou Hagedorn und Farid Ben Youssef','Rechtsanwältin Jule Morgen', '''Sehr geehrte Frau Morgen,

am vergangenen Samstag haben wir uns vor der Kiezbibliothek getroffen, nachdem am Mittag deren vorübergehende Schließung bekannt wurde. Wir wollten zeigen, wie wichtig dieser Ort für Kinder, ältere Menschen und unsere Nachbarschaft ist. Es blieb ruhig, und nach etwa einer Stunde gingen alle wieder auseinander. Wir möchten keinen Streit mit den dort eingesetzten Polizeikräften anfangen, aber einige Vorgänge verstehen wir nicht.

Farid musste seinen Ausweis zeigen, nachdem ein Beamter ihn wegen eines Gegenstands in seiner Tasche angesprochen hatte. Es handelte sich um einen zusammengeklappten Kerzenhalter. Außerdem stand ein Fahrzeug mit einer Kamera in der Nähe. Uns wurde später gesagt, es seien nur Übersichtsbilder gewesen. Ob die Bilder gespeichert wurden und ob jemand über die Maßnahme informiert worden ist, wissen wir nicht.

Bitte prüfen Sie zuerst die Unterlagen und entwerfen Sie ein sachliches Schreiben, mit dem wir Auskunft erhalten und nötige Unterlagen für eine spätere Prüfung sichern können. Eine Klage möchten wir derzeit nicht einreichen. Uns ist wichtig, dass Sie den älteren Chat nicht falsch verstehen: Für Mittwoch war bereits ein Leseabend im Café geplant, die Kundgebung am Samstag stand damals aber noch nicht fest.

Ich, Malou, habe die Nachricht über den heutigen Anlass in mehrere Gruppen geschickt. Farid hat vor Ort die Redebeiträge koordiniert, ohne dass wir vorher eine Leitung förmlich bestimmt hätten. Bitte fragen Sie uns, wenn dieser Unterschied wichtig ist. Wir möchten keine unzutreffende Darstellung abgeben. Eine Kontaktperson bei der Polizei haben wir nur aus der Eingangsbestätigung unserer kurzen E-Mail.

Mit freundlichen Grüßen
Malou Hagedorn und Farid Ben Youssef'''),
D('02_Schliessungsinformation.docx','Information an die Nutzerinnen und Nutzer','26.09.2026','Bibliothek am Pappelbogen\nInformationsdienst','Besucherinnen und Besucher', '''Die Bibliothek am Pappelbogen bleibt ab Montag, dem 28. September, vorübergehend geschlossen. Bei einer technischen Untersuchung am Freitag wurden Schäden an der Elektroinstallation festgestellt. Bis zur Prüfung und Instandsetzung kann der sichere Betrieb nicht gewährleistet werden. Die Entscheidung wurde heute Vormittag nach Rücksprache mit der Gebäudeverwaltung getroffen. Einen festen Wiedereröffnungstermin können wir noch nicht nennen.

Ausgeliehene Medien müssen während der Schließung nicht vor Ort zurückgegeben werden. Leihfristen werden angepasst; hierzu erhalten betroffene Nutzerinnen und Nutzer eine gesonderte Nachricht. Reservierte Medien können teilweise in der Zweigstelle am Kanal abgeholt werden. Bitte warten Sie die persönliche Abholbestätigung ab. Eine allgemeine Verlagerung sämtlicher Bestände ist kurzfristig nicht möglich.

Unser Team weiß, dass die Lernplätze und die offenen Angebote für viele Menschen wichtig sind. Der angekündigte Kinderlesenachmittag fällt zunächst aus. Wir prüfen, ob einzelne Angebote in nahe gelegene Räume verlegt werden können. Dazu gibt es noch keine abschließenden Vereinbarungen. Die Information auf unserer Internetseite wird ergänzt, sobald ein verlässlicher Arbeitsplan vorliegt.

Das Gebäude ist während der Schließung nicht öffentlich zugänglich. Bitte stellen Sie keine Gegenstände vor die Eingangstür und halten Sie die Zufahrt für die beauftragten Firmen frei. Die Rückgabebox bleibt bis auf Weiteres geschlossen. Fragen richten Sie bitte an information@pappelbogen-bibliothek.example. Die Nachricht wurde am Samstag um 11.40 Uhr auf unserer Internetseite veröffentlicht und gleichzeitig an den Verteiler des Freundeskreises geschickt.

Bibliothek am Pappelbogen, Informationsdienst'''),
D('03_Anlass_und_Einladung.docx','Licht für unsere Bibliothek','26.09.2026','Malou Hagedorn','Nachbarschaftsgruppen', '''Liebe Nachbarinnen und Nachbarn,

heute Vormittag haben wir erfahren, dass unsere Bibliothek ab Montag zunächst geschlossen bleibt. Wir verstehen, dass Sicherheitsmängel behoben werden müssen. Zugleich möchten wir öffentlich sichtbar machen, wie wichtig die Lernplätze, die Vorlesestunden und der offene Treffpunkt für unseren Kiez sind. Wir bitten um eine schnelle Reparatur und um einen erreichbaren Ersatzort für die Angebote.

Wer Zeit hat, kommt heute um 17.00 Uhr für ungefähr eine Stunde auf den öffentlichen Gehwegbereich vor der Bibliothek. Bitte bringen Sie ein Buch mit, aus dem Sie einen kurzen Satz über das Lesen vortragen möchten. LED-Lichter sind willkommen. Offene Flammen möchten wir wegen der Enge und der vielen Kinder vermeiden. Wir stellen keine Tische oder Verkaufsstände auf und blockieren weder den Eingang noch den Gehweg.

Es handelt sich um ein zusätzliches Treffen aus dem heutigen Anlass. Der bereits für Mittwoch im Café geplante Leseabend bleibt davon unabhängig. Niemand muss an beiden Treffen teilnehmen. Für heute gibt es keine fertige Rednerliste; wir sprechen vor Ort miteinander. Ich werde versuchen, die Versammlungsstelle direkt zu informieren, damit es keine unnötigen Missverständnisse gibt.

Bitte leiten Sie diese Nachricht mit dem vollständigen Text weiter. Eine verkürzte Formulierung wie „Bibliothek besetzen“ trifft unser Anliegen nicht und stammt nicht von uns. Wir bleiben draußen und möchten ruhig auf die Situation aufmerksam machen. Falls der Platz zu eng wird, verständigen wir uns vor Ort über eine vernünftige Aufstellung. Die Nachricht geht heute um 12.15 Uhr erstmals in unsere Gruppen.

Viele Grüße
Malou'''),
E('04_Mail_an_Polizei.eml','Kurzfristige Mahnwache heute 17 Uhr','2026-09-26T12:19:00+02:00','Malou Hagedorn <malou@leselicht.example>','Versammlungsstelle <anzeige@polizei-berlin.example>','Sehr geehrte Damen und Herren,\n\nwegen der erst heute um 11.40 Uhr bekanntgegebenen Bibliotheksschließung laden wir für 17 Uhr zu einer ruhigen Mahnwache vor der Bibliothek am Pappelbogen ein. Der Text ist beigefügt. Wir erwarten etwa dreißig Personen. Ich heiße Malou Hagedorn und wohne in der Pappelallee 62, Berlin. Sie erreichen mich über diese Adresse; ich bleibe heute abrufbereit. Bitte teilen Sie mir mit, welche Angaben Sie noch benötigen.\n\nMit freundlichen Grüßen\nMalou Hagedorn'),
E('05_Automatische_Antwort.eml','Eingang Ihrer Nachricht','2026-09-26T12:20:00+02:00','Versammlungsstelle <anzeige@polizei-berlin.example>','Malou Hagedorn <malou@leselicht.example>','Ihre Nachricht ist eingegangen. Bei kurzfristigen Änderungen wenden Sie sich zusätzlich telefonisch an die Versammlungsstelle. Die Eingangsbestätigung ersetzt keine weitere Abstimmung. Bitte nennen Sie bei Ergänzungen das Thema und den geplanten Veranstaltungsort, damit wir Ihre Nachrichten zuordnen können.'),
T('06_Chat_vor_dem_Anlass.txt','Planung Leseabend','23.09.2026','23.09.2026 19:08 Farid: Für Mittwoch haben wir sechs Plätze im Café. Jede Person bringt einen Lieblingssatz mit.\n23.09.2026 19:14 Malou: Gut. Ich frage die Bibliothek, ob jemand aus dem Team kommt.\n23.09.2026 19:17 Friedolin: Sollen wir draußen sein?\n23.09.2026 19:21 Malou: Nein, das ist ein kleiner Austausch im Café, keine Aktion auf dem Gehweg.\n23.09.2026 19:23 Farid: Dann reserviere ich den Tisch für 18 Uhr. Noch keine öffentliche Einladung.'),
D('07_Telefonnotiz_Anzeige.docx','Telefonat mit der Versammlungsstelle','26.09.2026','Malou Hagedorn','Eigene Ablage', '''Ich rief um 12.27 Uhr bei der auf der Internetseite genannten Nummer an. Nach einigen Minuten sprach ich mit einer Mitarbeiterin und schilderte die kurzfristige Schließungsnachricht. Ich erwähnte, dass die Einladung bereits wenige Minuten zuvor in unseren Gruppen verschickt worden war. Die Mitarbeiterin fragte nach Thema, genauer Stelle, Teilnehmerzahl und einer erreichbaren Person vor Ort.

Ich nannte dreißig erwartete Personen und sagte, dass wir vor dem Gebäude auf dem Gehweg bleiben wollten. Ein Aufzug sei nicht geplant. Für die Dauer gab ich 17.00 bis 18.00 Uhr an. Ich erklärte auch, dass wir nur LED-Lichter und Bücher mitbringen. Sie bat mich, darauf zu achten, dass der Durchgang ausreichend breit bleibe und die Gebäudetür nicht verstellt werde. Eine bestimmte Breite wurde in diesem Telefonat nicht genannt.

Auf die Frage nach der Leitung sagte ich, dass ich selbst komme, Farid aber die Wortmeldungen sammeln könne. Ich war mir nicht sicher, ob wir dafür vorher etwas Besonderes erklären müssen. Die Mitarbeiterin sagte, die Einsatzkräfte könnten uns vor Ort ansprechen. Einen schriftlichen Bescheid kündigte sie nicht an. Ich habe keine ausdrückliche Erlaubnis zugesagt bekommen und auch nicht darum gebeten.

Das Gespräch endete gegen 12.39 Uhr. Ich notierte mir leider weder den Namen noch eine Durchwahl. Die Eingangsbestätigung unserer Mail liegt vor. Am Nachmittag leitete ich eine kürzere Erinnerung weiter, deren Wortlaut sich nicht mehr vollständig in meiner Ablage findet. Sie nannte weiterhin 17 Uhr. Eine frühere Nachricht, in der bereits am Freitag zur Mahnwache aufgerufen worden wäre, kenne ich nicht.'''),
E('08_Bibliothek_Rueckmeldung.eml','Ihre Nachricht zur Mahnwache','2026-09-26T14:08:00+02:00','Bibliothek <information@pappelbogen-bibliothek.example>','Malou Hagedorn <malou@leselicht.example>','Liebe Frau Hagedorn,\n\nvielen Dank für Ihre Unterstützung. Bitte beachten Sie, dass die Zufahrt heute noch für eine technische Besichtigung benötigt wird. Die Bibliothek tritt nicht als Veranstalterin Ihres Treffens auf. Der für Mittwoch geplante Leseabend war uns bekannt; von der Mahnwache haben wir erst aus Ihrer heutigen Mail erfahren.\n\nMit freundlichen Grüßen\nBibliothek am Pappelbogen'),
D('09_Ablaufnotiz_Malou.docx','Erinnerung an den Samstagnachmittag','27.09.2026','Malou Hagedorn','Kanzleiablage', '''Ich kam am Samstag gegen 16.45 Uhr zur Bibliothek. Zunächst standen etwa zehn Personen dort. Um 17.10 Uhr zählte ich ungefähr siebenunddreißig Menschen, darunter einige Kinder. Farid bat die Gruppe, näher an die Gebäudeseite zu rücken, damit Fußgänger vorbeikommen konnten. Wir standen nicht auf der Fahrbahn. Ein Fahrzeug fuhr einmal durch die Zufahrt; dafür rückten wir ohne Streit auseinander.

Zwei uniformierte Polizeikräfte sprachen mich kurz nach 17 Uhr an. Ich sagte, dass ich die Nachricht verschickt habe und Farid die Redebeiträge sammelt. Es ging zunächst um den freien Durchgang. Einer der Beamten erklärte später, man müsse für die Übersicht eine Kamera benutzen. Ich verstand nicht, ob er dabei mit mir oder mit einer Kollegin sprach. Eine ausdrückliche Information über Speicherung oder Löschung habe ich nicht gehört.

Gegen 17.25 Uhr wurde Farid etwas abseits der Gruppe angesprochen. Ich konnte das Gespräch nicht vollständig verstehen. Ich sah seinen Ausweis in der Hand des Beamten und später den zusammengeklappten Metallhalter. Farid kam nach wenigen Minuten zurück. Er wirkte verärgert, blieb aber bei uns. Die Wortbeiträge gingen weiter, und gegen 18.03 Uhr bedankte er sich bei allen.

Niemand erklärte uns nach meiner Erinnerung, dass die Versammlung aufgelöst sei. Eine Durchsage über einen Lautsprecher hörte ich nicht. Danach verabschiedeten wir uns in kleinen Gruppen. Zwei ältere Nachbarinnen blieben noch auf der Bank sitzen. Als ich um 18.15 Uhr ging, stand das Kamerafahrzeug noch auf der anderen Straßenseite. Ob es während unserer gesamten Zusammenkunft auf uns gerichtet war, kann ich nicht sicher sagen.'''),
D('10_Erinnerung_Farid.docx','Personalienkontrolle und Kerzenhalter','28.09.2026','Farid Ben Youssef','Rechtsanwältin Jule Morgen', '''Sehr geehrte Frau Morgen,

ich hatte für unsere Lichteraktion einen zusammenklappbaren Metallhalter mitgebracht. Er lag in meiner offenen Stofftasche. Ursprünglich wollte ich daran mehrere LED-Leuchten befestigen. Ich habe keine echten Kerzen benutzt. Während einer Wortmeldung trat ein Polizeibeamter zu mir und fragte, was in der Tasche sei. Ich zog den Halter heraus und klappte ihn ein Stück auf. Danach sollte ich meinen Ausweis vorzeigen.

Der Beamte sagte sinngemäß, der Gegenstand könne auch anders verwendet werden und er müsse meine Personalien prüfen. Ich fragte, ob ich etwas falsch gemacht hätte. Eine genaue Vorschrift oder einen konkreten Tatvorwurf nannte er nach meiner Erinnerung nicht. Ich kann aber nicht ausschließen, dass ich wegen der Aufregung einen Teil der Antwort überhört habe. Das Gespräch dauerte nach der Uhr meines Telefons ungefähr sechs Minuten.

Mein Ausweis wurde angesehen und über Funk wurden Angaben durchgegeben. Ich weiß nicht, ob weitere Daten notiert oder gespeichert worden sind. Der Halter blieb bei mir. Ich wurde weder durchsucht noch festgehalten, soweit ich darunter eine körperliche Sicherung verstehe. Ob ich einfach hätte weggehen dürfen, habe ich nicht gefragt. Danach konnte ich zur Gruppe zurückkehren und den Abschluss moderieren.

Bitte formulieren Sie zunächst eine Nachfrage. Ich möchte wissen, welcher Anlass dokumentiert wurde und welche personenbezogenen Daten nun vorhanden sind. Wenn eine Bildaufnahme meine Kontrolle zeigt, möchte ich diese für eine sachliche Aufklärung nicht vorschnell verlieren. Zugleich möchte ich nicht, dass solche Bilder ohne Grund dauerhaft gespeichert werden. Bitte erklären Sie uns, wie man diese beiden Anliegen sinnvoll zusammenbringt.

Mit freundlichen Grüßen
Farid'''),
X('11_Chronologie_und_Beobachtungen.xlsx','Zeitpunkte und Beobachtungsgrundlagen',[dict(name='Zeitlinie',headers=['Vorgang','Uhrzeit','Minuten seit Anlass','Quelle'],widths=[38,16,22,50],formats={'B':'hh:mm','C':'0'},rows=[['Schließungsnachricht','=TIME(11,40,0)',0,'Webhinweis Bibliothek'],['Erste Einladung','=TIME(12,15,0)','=ROUND((B3-$B$2)*1440,0)','Gesendete Nachricht'],['E-Mail an Polizei','=TIME(12,19,0)','=ROUND((B4-$B$2)*1440,0)','Mailkopf'],['Telefonende','=TIME(12,39,0)','=ROUND((B5-$B$2)*1440,0)','Malous Notiz'],['Beginn','=TIME(17,0,0)','=ROUND((B6-$B$2)*1440,0)','Ablaufplan']],expected={'C3':35,'C6':320},perturbations=[{'input':'B3','value':12.5/24,'output':'C3','expected':50}]),dict(name='Zaehlungen',headers=['Zeitpunkt','Erwachsene','Kinder','Gesamt','Grundlage'],widths=[20,18,16,16,55],formats={'B':'0','C':'0','D':'0'},rows=[['16:50 Uhr',9,3,'=B2+C2','Malou: grob gezählt'],['17:10 Uhr',29,8,'=B3+C3','Malou: einmal durchgezählt'],['17:40 Uhr',25,6,'=B4+C4','Friedolin: unsichere Schätzung']],expected={'D3':37})]),
E('12_Nachfrage_Veranstalterin.eml','Frage zur Kamera am Samstag','2026-09-28T09:16:00+02:00','Malou Hagedorn <malou@leselicht.example>','Versammlungsstelle <anzeige@polizei-berlin.example>','Sehr geehrte Damen und Herren,\n\nbei unserer Mahnwache am 26. September stand eine Kamera gegenüber. Können Sie bitte sagen, ob Aufzeichnungen entstanden sind? Farid möchte auch den Grund für die Überprüfung seiner Personalien erfahren. Wir reichen eine Vollmacht bei Bedarf nach.\n\nMit freundlichen Grüßen\nMalou Hagedorn'),
D('13_Notiz_Kamera.docx','Wahrnehmungen von Friedolin Knödel','28.09.2026','Friedolin Knödel','Malou und Farid', '''Ich stand während der Mahnwache meistens bei der Bank auf der Nordseite. Von dort konnte ich das Fahrzeug mit dem Kameramast sehen. Ich kenne solche Geräte technisch nicht und kann nicht beurteilen, ob eine Aufnahme gespeichert oder nur auf einen Bildschirm übertragen wurde. Die Kamera schwenkte nach meiner Erinnerung mindestens einmal, möglicherweise weil ein Lieferwagen in die Zufahrt fuhr.

Um 17.18 Uhr machte ich ein Foto von der Gruppe. Auf diesem Bild ist das Fahrzeug am Rand zu erkennen. Das Foto enthält keine Nahaufnahme der Kameraanzeige. Ich habe es Malou gezeigt, aber nicht öffentlich hochgeladen. Auf Wunsch kann ich die Originaldatei mit ihrem Zeitstempel zur Verfügung stellen. Der Zeitstempel meines Telefons war an diesem Tag automatisch eingestellt.

Bei Farids Kontrolle stand ich zu weit weg, um das gesamte Gespräch zu verstehen. Ich hörte einmal das Wort Personalien. Ich sah weder, dass jemand Farids Tasche vollständig leerte, noch dass der Metallhalter weggenommen wurde. Später trug Farid ihn wieder selbst. Die Kontrolle war beendet, bevor die letzte Nachbarin ihren Text vorlas. Farid blieb bis zum Ende bei der Gruppe.

Ich habe in unserem Chat geschrieben, es sei „alles gefilmt“ worden. Das war eine spontane Vermutung und keine technische Beobachtung. Nach Malous Rückfrage möchte ich das genauer sagen: Eine Kamera war da und zeitweise auf unsere Seite gerichtet; über Speicherung weiß ich nichts. Bitte übernehmen Sie meinen ursprünglichen Satz nicht als gesicherte Tatsache. Mir ist wichtig, dass die Bibliothek wieder öffnet. Die Frage nach der Kamera sollte ohne übertriebene Vorwürfe geklärt werden.'''),
T('14_Chat_nach_Mahnwache.txt','Nachbesprechung im Freundeskreis','28.09.2026','27.09.2026 10:04 Friedolin: Die haben alles gefilmt, sah jedenfalls so aus.\n27.09.2026 10:11 Malou: Weißt du das sicher oder war nur eine Kamera zu sehen?\n27.09.2026 10:28 Friedolin: Nur gesehen. Speichern kann ich nicht beurteilen.\n28.09.2026 08:15 Farid: Bitte keine Fotos von meiner Kontrolle ins Netz. Ich möchte erst wissen, was dokumentiert wurde.\n28.09.2026 08:23 Malou: Einverstanden. Ich frage schriftlich nach.\n28.09.2026 08:35 Farid: Das Café-Treffen am Mittwoch bleibt ein eigener Termin.'),
E('15_Zwischenantwort_Polizei.eml','Ihre Anfrage zur Mahnwache','2026-09-29T14:35:00+02:00','Versammlungsstelle <anzeige@polizei-berlin.example>','Malou Hagedorn <malou@leselicht.example>','Sehr geehrte Frau Hagedorn,\n\nnach vorläufiger Rückfrage waren Übersichtsbilder zur Einsatzübersicht vorgesehen. Eine abschließende Prüfung zur tatsächlichen Nutzung des Geräts und zu etwaigen gespeicherten Daten steht noch aus. Für personenbezogene Auskünfte zu Herrn Ben Youssef benötigen wir dessen eigene Anfrage oder eine entsprechende Vollmacht. Bitte geben Sie den Ort und den Zeitraum der Kontrolle möglichst genau an.\n\nVersammlungsstelle'),
D('16_Zeugin_Erinnerung.docx','Beobachtung des Durchgangs','29.09.2026','Ottilie Schramm','Farid Ben Youssef', '''Ich kam um etwa 17.15 Uhr mit meinem Rollator zur Bibliothek, weil ich die Schließungsnachricht zunächst nicht gesehen hatte. Die Gruppe stand nahe an der Hausseite. Eine Frau half dabei, zwei Personen ein Stück zur Seite zu bitten, damit ich vorbeikam. Ich hatte nicht den Eindruck, dass mir absichtlich der Weg versperrt wurde. An der engsten Stelle musste ich allerdings langsam fahren.

Später blieb ich beim Lesen der kurzen Texte stehen. Es wurde ein kleines tragbares Gerät benutzt, dessen Lautstärke ich als normal empfand. Ich bin keine Sachverständige für Schallmessungen. Ein Lieferwagen fuhr in die Einfahrt, während die Gruppe kurz auseinanderging. Ich kann die genaue Uhrzeit nicht mehr nennen. Ein Fahrer winkte zum Dank; mehr habe ich dazu nicht wahrgenommen.

Farid wurde auf der anderen Seite der Gruppe angesprochen. Ich sah, dass er einen länglichen Gegenstand aus der Tasche holte. Erst hinterher erklärte er mir, dass dies ein Halter für LED-Lichter war. Ich kann daher nicht aus eigener Wahrnehmung sagen, was der Polizeibeamte zuvor gesehen hatte. Ich hörte keine Drohung und sah keinen Streit. Ich war aber nicht nah genug, um den vollständigen Gesprächsinhalt zu bestätigen.

Nach dem letzten Beitrag bedankte sich Farid. Einige Menschen klatschten und gingen anschließend nach Hause. Ich saß noch einige Minuten auf der Bank. Eine polizeiliche Auflösung habe ich nicht gehört. Wegen meines Hörgeräts kann ich leise Gespräche über größere Entfernung schlecht verstehen. Meine Angaben beziehen sich deshalb nur auf das, was ich tatsächlich sah und hörte, und nicht auf eine vollständige Übersicht über den ganzen Einsatz.'''),
E('17_Antwort_Kanzlei.eml','Erinnerung von Frau Schramm','2026-09-30T08:02:00+02:00','Farid Ben Youssef <farid@leselicht.example>','Jule Morgen <post@kanzlei-kanal.example>','Sehr geehrte Frau Morgen,\n\nim Anhang ist die Notiz von Frau Schramm. Ich bevollmächtige Sie, Auskünfte zu meiner Kontrolle und zu meinen dabei verarbeiteten Daten anzufordern. Für einen gerichtlichen Schritt sprechen Sie bitte nochmals mit mir. Ich möchte auch, dass ein vorhandenes Video zur Prüfung nicht einfach verschwindet, ohne dass daraus eine dauerhafte Nutzungserlaubnis gemacht wird.\n\nMit freundlichen Grüßen\nFarid Ben Youssef'),
E('18_Letzter_Nachtrag.eml','Zeit der ersten Einladung','2026-09-30T09:18:00+02:00','Malou Hagedorn <malou@leselicht.example>','Jule Morgen <post@kanzlei-kanal.example>','Sehr geehrte Frau Morgen,\n\nich habe nochmals nachgesehen: Die erste Nachricht zur Mahnwache war wirklich am Samstag um 12.15 Uhr. Der ältere Chat vom Mittwoch gehört zum Caféabend. Ein lokaler Blog nennt unser Treffen spontan; ich weiß nicht, ob das rechtlich das richtige Wort ist. Bitte verwenden Sie die genauen Zeiten statt dieser Bezeichnung.\n\nFreundliche Grüße\nMalou Hagedorn')]))
CASES.append(dict(slug='berlin-versammlung-kiezcamp',title='Drei Tage Platz für Begegnung',plugin=PLUGIN,date='02.10.2026',client='Initiative Bankgespräch, vertreten durch Yasmin Wippermann',summary='Eine Initiative plant ein dreitägiges Gesprächscamp zur Nutzung eines Platzes. Diskutiert werden Nachtpräsenz, vier Schlafzelte und eine nebenbei angebotene Unterkunft für Besucher einer anderen Veranstaltung.',assignment='Yasmin möchte ein konsistentes Campkonzept und eine ausformulierte Antwort auf die angekündigte Infrastrukturbegrenzung. Eine Unterbringung fremder Demonstrationsgäste soll nicht ohne Rücksprache als Bestandteil des Camps versprochen werden.',attachments={'04_Anzeige_Mail.eml':['03_Anzeige_Camp.docx'],'17_Konzeptkorrektur.eml':['16_Beschluss_Orga.docx']},documents=[
D('01_Auftrag_Camp.docx','Unser Gesprächscamp am Brunnenplatz','02.10.2026','Yasmin Wippermann\nInitiative Bankgespräch','Rechtsanwältin Jule Morgen', '''Sehr geehrte Frau Morgen,

unsere Initiative möchte vom 16. bis zum 18. Oktober auf dem Brunnenplatz darüber sprechen, wie der Platz künftig genutzt werden soll. Einige Bänke und ein kleines Nachbarschaftsbeet sollen im Zuge eines Umbaus wegfallen. Wir möchten drei Tage lang zeigen, wie Begegnung dort aussehen kann, und dazu Gespräche, Lesungen und eine kleine Ausstellung veranstalten. Eine ständige Ansprechbarkeit auch über Nacht war von Anfang an Teil unserer Idee.

Die Versammlungsstelle hält vier Schlafzelte und eine gemeinsame Küche für möglicherweise zu viel. Eine endgültige Entscheidung liegt noch nicht vor. Wir sollen bis zum 6. Oktober genauer erklären, wie die Einrichtungen mit unserem Programm zusammenhängen. Zugleich hat Balthasar einer befreundeten Gruppe acht Schlafplätze zugesagt, obwohl diese Menschen tagsüber an einer anderen Demonstration teilnehmen wollen. Ich habe das erst gestern gesehen und halte die Zusage für ein Missverständnis.

Bitte helfen Sie uns, ein ehrliches und nachvollziehbares Konzept zu schreiben. Es soll weder eine allgemeine Übernachtungsstelle werden noch sollen unsere Helfer nachts im Regen stehen. Wir möchten wissen, welche Angaben wir belegen müssen und welche Teile wir gegebenenfalls freiwillig reduzieren können. Ein Gericht soll im Moment nicht angerufen werden.

Unsere Gruppe ist klein und nicht als Verein organisiert. Ich habe die Anzeige eingereicht, aber Ottilie und Balthasar haben an der Planung mitgearbeitet. Bitte sprechen Sie die Vertretung im Entwurf klar an. Ein Gebührenbescheid oder eine verbindliche Zusage des Bezirksamts liegt uns nicht vor. Die alten und neuen Programme unterscheiden sich; ich möchte sie nicht unbemerkt vermischen.

Mit freundlichen Grüßen
Yasmin Wippermann'''),
D('02_Ursprungskonzept.docx','Gesprächscamp Fassung 1','21.09.2026','Initiative Bankgespräch','Interne Planung', '''Das Gesprächscamp soll den Brunnenplatz für drei Tage als Ort öffentlichen Austauschs sichtbar machen. Unser gemeinsames Thema lautet „Platz für Begegnung statt bloßer Durchgang“. Wir setzen uns für Sitzgelegenheiten, zugängliche Wege und eine nichtkommerzielle Nutzung des Platzes ein. Der konkrete Umbauentwurf liegt noch nicht vollständig öffentlich aus. Wir wollen deshalb Fragen sammeln und unterschiedliche Vorstellungen aus der Nachbarschaft zusammenführen.

Tagsüber soll ein offenes Gesprächszelt kurze moderierte Runden ermöglichen. An Stellwänden zeigen wir Zeichnungen, die Besucher selbst ergänzen können. Eine kleine Lesung und zwei Gesprächsrunden am Abend beziehen sich auf den Alltag älterer Menschen und Familien. Essen und Trinken werden nicht verkauft. Eine Teestation soll das längere Verweilen unterstützen, ohne ein eigenständiges Bewirtungsangebot zu bilden.

Für die Nächte sind vier kleine Zelte vorgesehen. Jeweils zwei Personen sollen ansprechbar bleiben; weitere Helfer ruhen sich aus und wechseln später ab. Die genaue Zahl der gleichzeitig notwendigen Schlafplätze haben wir noch nicht durchgerechnet. Einige Personen wohnen in der Nähe und könnten zeitweise nach Hause gehen. Bei Regen brauchen wir einen trockenen Rückzugsort, möchten aber keine großen zusätzlichen Flächen belegen.

Balthasar klärt Toiletten und Wasser. Ottilie spricht mit den Anwohnern. Yasmin führt die Korrespondenz mit der Versammlungsstelle. Wir wollen den Platz sauber hinterlassen und das Material am Sonntagabend vollständig abbauen. Die Zufahrt zur angrenzenden Einrichtung bleibt frei. Eine Nutzung des gesamten Platzes ist nicht beantragt. Die Fläche auf unserer ersten Zeichnung beträgt ungefähr sechzig Quadratmeter, ist aber noch nicht vermessen.'''),
D('03_Anzeige_Camp.docx','Anzeige Gesprächscamp Bankgespräch','23.09.2026','Yasmin Wippermann\nInitiative Bankgespräch','Polizei Berlin\nVersammlungsbehörde', '''Hiermit zeige ich eine öffentliche Versammlung unter freiem Himmel auf dem Brunnenplatz in Berlin an. Sie soll am Freitag, dem 16. Oktober, um 14.00 Uhr beginnen und am Sonntag, dem 18. Oktober, um 18.00 Uhr enden. Thema ist „Platz für Begegnung statt bloßer Durchgang“. Das mehrtägige Konzept verbindet öffentliche Gesprächsrunden, eine von Besuchern ergänzte Ausstellung und eine durchgehende Mahnwache am geplanten Umbauort.

Ich, Yasmin Wippermann, übernehme die Leitung und bin unter yasmin@bankgespraech.example erreichbar. Meine Anschrift lautet Seestraße 117, 13353 Berlin. Gemeinsam mit Ottilie Karg und Balthasar Knödel organisiere ich die Veranstaltung. Wir erwarten tagsüber gleichzeitig etwa dreißig Personen, bei einzelnen Gesprächsrunden bis zu fünfzig. Nachts soll die Gruppe wesentlich kleiner sein. Eine genaue Aufstellung reichen wir nach.

Geplant sind ein offenes Gesprächszelt, vier kleine Schlafzelte, eine Teestation und zwei mobile Toiletten. Wir möchten dafür den auf der beigefügten Beschreibung markierten Randbereich des Platzes nutzen. Die Hauptquerung und die Zufahrt zur Einrichtung bleiben frei. Musikverstärkung ist nicht vorgesehen. Für Wortbeiträge möchten wir ein kleines Akkugerät verwenden, soweit die Verständlichkeit dies erfordert.

Die erste öffentliche Einladung ist für den 26. September vorgesehen. Wir bitten um ein Kooperationsgespräch, insbesondere zu Nachtpräsenz, Toiletten und Rettungswegen. Es soll kein kommerzieller Markt und kein allgemeiner Campingplatz entstehen. Die bereits verfasste Programmskizze ist als vorläufiger Stand gekennzeichnet. Änderungen teilen wir unverzüglich mit. Die Bestellung der Infrastruktur haben wir bisher nur angefragt und noch nicht endgültig ausgelöst.'''),
E('04_Anzeige_Mail.eml','Gesprächscamp 16. bis 18. Oktober','2026-09-23T10:02:00+02:00','Yasmin Wippermann <yasmin@bankgespraech.example>','Versammlungsstelle <anzeige@polizei-berlin.example>','Sehr geehrte Damen und Herren,\n\nim Anhang finden Sie unsere Anzeige. Für einen Gesprächstermin sind wir nächste Woche flexibel. Die Einladung soll erst am Samstag erscheinen.\n\nMit freundlichen Grüßen\nYasmin Wippermann'),
E('05_Eingangsantwort.eml','VC-26-1016-18','2026-09-23T10:11:00+02:00','Versammlungsstelle <anzeige@polizei-berlin.example>','Yasmin Wippermann <yasmin@bankgespraech.example>','Ihre Anzeige wird unter VC-26-1016-18 bearbeitet. Bitte reichen Sie ein Programm mit Zeitfenstern und eine Erklärung der vorgesehenen Nachtnutzung nach. Zu den Angaben über private Kontaktdaten weiterer Helfender benötigen wir derzeit keine Ergänzung.'),
D('06_Programmstand.docx','Programmentwurf für drei Tage','25.09.2026','Ottilie Karg','Initiative Bankgespräch', '''Am Freitag soll das Camp um 14 Uhr mit einer kurzen Erläuterung unseres Anliegens beginnen. Danach öffnen wir die Ausstellung mit Zeichnungen des Platzes. Um 16 Uhr ist ein Gespräch darüber vorgesehen, welche Sitzgelegenheiten unterschiedliche Menschen benötigen. Um 18 Uhr liest Friedolin aus gesammelten Erinnerungen der Nachbarschaft. Gegen 20 Uhr folgt eine ruhige Runde über die Nutzung des Platzes am Abend. Verstärkte Beiträge nach 21 Uhr sind nicht vorgesehen.

Am Samstag möchten wir von 10 bis 12 Uhr mit Familien Wege auf dem Platz markieren, ohne dauerhaft Farbe oder feste Gegenstände auf dem Boden anzubringen. Nachmittags sind zwei moderierte Gespräche geplant: zuerst mit älteren Bewohnern, danach mit Menschen, die auf barrierearme Wege angewiesen sind. Zwischen diesen Terminen bleibt das Gesprächszelt offen. Die Stellwände werden fortlaufend ergänzt. Eine Teilnahme ist ohne Anmeldung möglich.

Am Sonntag sammeln wir ab 10 Uhr die Vorschläge und formulieren offene Fragen an die zuständigen Stellen. Um 15 Uhr wollen wir eine gemeinsame Abschlussrunde anbieten. Danach beginnt der Rückbau. Spätestens um 18 Uhr endet die Versammlung; das Material soll bis 19 Uhr abgeholt werden. Die genaue rechtliche Einordnung der zusätzlichen Abbauzeit müssen wir noch klären.

Für die Nachtstunden steht bislang nur „stille Mahnwache und Gespräche bei Bedarf“ im Plan. Wir sollten genauer beschreiben, wer tatsächlich vor Ort bleibt und wie ein inhaltlicher Zusammenhang sichtbar wird. Ein ständiges Beschallungsprogramm ist nicht gewollt. Die bloße Bewachung von Kisten ist auch nicht unser öffentliches Anliegen. Balthasar hat externe Gäste erwähnt; diese sind in diesem Programm nicht berücksichtigt.'''),
T('07_Chat_Schlafplaetze.txt','Ausschnitt Organisationschat','29.09.2026','28.09.2026 20:10 Balthasar: Die Gruppe aus Halle sucht für ihre Demo in Mitte noch acht Schlafplätze. Ich habe gesagt, unsere Zelte könnten reichen.\n28.09.2026 20:18 Ottilie: Sind die denn auch bei unserem Programm?\n28.09.2026 20:24 Balthasar: Tagsüber eher nicht. Vielleicht am Sonntag kurz. Ich dachte, helfen wäre nett.\n29.09.2026 07:40 Yasmin: Das haben wir nicht beschlossen. Bitte keine weiteren Zusagen. Unsere vier Zelte waren für eigene Nachtwechsel gedacht.\n29.09.2026 08:15 Balthasar: Ich kläre das. Habe bisher nur mündlich gesprochen, nichts verbindlich gebucht.'),
E('08_Gaestegruppe.eml','Übernachten bei euch?','2026-09-29T09:12:00+02:00','Kulturgruppe Hallenlicht <kontakt@hallenlicht.example>','Balthasar Knödel <balthasar@bankgespraech.example>','Lieber Balthasar,\n\nvielen Dank für das nette Angebot. Wir wären acht Erwachsene von Samstagabend bis Sonntagfrüh. Tagsüber sind wir bei unserer Kundgebung in Mitte. Sollen wir Schlafsäcke mitbringen? Eine feste Zusage brauchen wir bis Freitag, sonst suchen wir eine Jugendherberge.\n\nViele Grüße\nJana und Team'),
D('09_Notiz_Kooperation.docx','Gespräch über Infrastruktur','30.09.2026','Yasmin Wippermann','Initiative und Kanzleiablage', '''Am Kooperationsgespräch nahmen Ottilie und ich teil. Balthasar war wegen seiner Arbeit verhindert. Die Versammlungsstelle fragte besonders nach der Anzahl der Schlafzelte, der Dauer der Nachtpräsenz und dem Zusammenhang der Teestation mit dem politischen Anliegen. Wir erklärten, dass der Platz nicht zu einer Unterkunft für beliebige Besucher werden solle. Die inzwischen bekannte Anfrage aus Halle erwähnte ich, weil ich sie nicht verschweigen wollte.

Die Mitarbeiterin bat darum, die verschiedenen Funktionen getrennt zu beschreiben. Sie hielt ein offenes Gesprächszelt und die Ausstellung zunächst für nachvollziehbar. Bei vier Schlafzelten sah sie Klärungsbedarf. Sie fragte, ob die Nachtwache tatsächlich ein eigener Ausdruck unseres Protests sei oder hauptsächlich der Materialbewachung diene. Wir konnten dazu noch keinen fertigen Schichtplan vorlegen.

Auch der Begriff Küche war unklar. In der ersten Skizze stand Gemeinschaftsküche, obwohl nach unserem derzeitigen Plan nur heißes Wasser in isolierten Behältern und mitgebrachte belegte Brote vorgesehen sind. Es soll nicht gekocht und kein Gasgerät betrieben werden. Ottilie sagte zu, dies im Konzept deutlich zu korrigieren. Die Toiletten sollen über einen mobilen Anbieter bereitgestellt werden; die Lieferung ist noch nicht bestätigt.

Als möglicher nächster Schritt wurde eine Reduzierung auf zwei Schlafzelte und einen kleineren Nachtkreis angesprochen. Das war noch keine verbindliche Einigung. Wir dürfen bis zum 6. Oktober schriftlich ergänzen. Die Versammlungsstelle kündigte danach eine Entscheidung an. Ein sofort vollziehbarer Bescheid wurde weder ausgehändigt noch per Mail angekündigt. Wir haben erklärt, dass wir das Anliegen tagsüber jedenfalls weiterverfolgen möchten und vor einer grundlegenden Änderung nochmals intern beraten.'''),
E('10_Anhoerung_Infrastruktur.eml','VC-26-1016-18 Ergänzungen bis 6. Oktober','2026-09-30T15:26:00+02:00','Versammlungsstelle <anzeige@polizei-berlin.example>','Yasmin Wippermann <yasmin@bankgespraech.example>','Sehr geehrte Frau Wippermann,\n\nbitte erläutern Sie bis 6. Oktober, 12 Uhr, das Nachtprogramm, die personelle Belegung und die Funktion jedes Zelts. Nach gegenwärtigem Stand erwägen wir eine Beschränkung der Schlafinfrastruktur auf zwei kleine Zelte. Eine abschließende Entscheidung ist damit nicht getroffen. Zur externen Gästegruppe und zur angekündigten Küche bitten wir um klare Angaben.\n\nVersammlungsstelle'),
X('11_Flaeche_und_Nachtplan.xlsx','Infrastruktur und gleichzeitige Belegung',[dict(name='Flaeche',headers=['Gegenstand','Anzahl','Breite m','Laenge m','Flaeche qm','Stand'],widths=[30,13,15,15,18,40],formats={'B':'0','C':'0.0','D':'0.0','E':'0.0'},rows=[['Gesprächszelt',1,3,4,'=B2*C2*D2','offen'],['Schlafzelt',4,2,2.5,'=B3*C3*D3','ursprünglicher Antrag'],['Teestation',1,1.5,2,'=B4*C4*D4','kein Gas'],['Toiletten',2,1.2,1.2,'=B5*C5*D5','Lieferung offen'],['Stellwände',2,0.8,2,'=B6*C6*D6','Fußfläche'],['Gesamt',None,None,None,'=SUM(E2:E6)','Wege nicht enthalten']],expected={'E7':41.08},perturbations=[{'input':'B3','value':2,'output':'E7','expected':31.08}]),dict(name='Nachtplan',headers=['Schicht','Ansprechbar','Ruhend','Personen','Bemerkung'],widths=[32,18,16,18,42],formats={'B':'0','C':'0','D':'0'},rows=[['Freitag 22 bis 2',2,2,'=B2+C2','vier eigene Helfer'],['Samstag 2 bis 6',2,2,'=B3+C3','Wechsel derselben vier'],['Samstag 22 bis 2',2,2,'=B4+C4','vier eigene Helfer'],['Sonntag 2 bis 6',2,2,'=B5+C5','externe Gäste nicht enthalten']],expected={'D2':4})]),
D('12_Anwohnergespraech.docx','Gespräch mit den Nachbarn','01.10.2026','Ottilie Karg','Initiative Bankgespräch', '''Ich habe heute mit drei Bewohnerinnen der unmittelbar angrenzenden Häuser gesprochen. Alle drei finden die Idee eines Gesprächs über den Platz grundsätzlich gut. Zwei von ihnen sorgen sich wegen der Nachtstunden und möglicher Lautstärke. Eine Bewohnerin arbeitet im Frühdienst und bat darum, nach 21 Uhr keine verstärkten Beiträge zu halten. Ich habe gesagt, dass dies unserem derzeitigen Plan entspricht, aber noch keine rechtsverbindliche Zusage im Namen der gesamten Gruppe abgegeben.

Die Einfahrt der sozialen Einrichtung wird morgens und am späten Nachmittag genutzt. Eine Pflegekraft erklärte mir, dass auch an Wochenenden einzelne Transporte stattfinden. Ein fester Plan ist noch nicht übersandt. Wir sollten die Einfahrt deshalb durchgehend frei lassen und nicht mit dem Argument arbeiten, sonntags sei dort sicher niemand unterwegs. Der Türbereich wird außerdem von Menschen mit Rollstuhl benutzt.

Eine Nachbarin bot an, für unsere Helfer nachts Wasser bereitzustellen. Ihr Angebot bezog sich auf einen gelegentlichen Nachfüllbedarf, nicht auf die Versorgung beliebig vieler Gäste. Ihre private Toilette möchte sie nicht zur allgemeinen Nutzung freigeben. Das respektieren wir. Für zwei mobile Toiletten liegt ein Preisangebot vor, allerdings noch keine bestätigte Lieferzeit.

Die älteste Bewohnerin, Frau Schramm, möchte am Samstag ihre Erinnerungen an den Platz vorlesen. Sie braucht einen stabilen Stuhl und einen gut zugänglichen Weg. Für mich spricht das dafür, den öffentlichen Gesprächsbereich übersichtlich zu halten. Vier Schlafzelte direkt davor würden die Sicht auf die Stellwände beeinträchtigen. Ob wir mit zwei Zelten auskommen, müssen wir anhand des tatsächlichen Nachtplans entscheiden. Die acht Personen aus Halle habe ich diesen Nachbarinnen nicht als fest eingeplante Campgäste vorgestellt.'''),
D('13_Anbieterangebot.docx','Angebot mobile Infrastruktur','01.10.2026','Platzpause Service GmbH','Initiative Bankgespräch', '''Sehr geehrte Frau Wippermann,

wir bieten Ihnen für den Zeitraum vom 16. bis zum 18. Oktober zwei mobile Toilettenkabinen einschließlich Anlieferung, Abholung und einer Zwischenreinigung an. Eine Kabine kann in barrierearmer Ausführung bereitgestellt werden, sofern Sie dies bis zum 7. Oktober bestätigen. Die in Ihrer ersten Skizze eingezeichnete Fläche reicht für diese größere Kabine nicht aus. Sie erhalten dafür nach Bestätigung eine gesonderte Maßzeichnung.

Der vorläufige Gesamtpreis beträgt 680 Euro einschließlich Umsatzsteuer. Das Angebot ist bis zum 7. Oktober freibleibend. Eine Reservierung besteht erst nach unserer schriftlichen Auftragsbestätigung. Für die Lieferung benötigen wir einen befahrbaren Zugang und eine verantwortliche Person vor Ort. Wir nehmen keine Prüfung vor, ob die Aufstellung öffentlich-rechtlich zulässig ist. Diese Abstimmung bleibt bei Ihnen.

Die Anlieferung wäre am Freitag zwischen 11 und 13 Uhr möglich. Am Sonntag können wir das Material erst ab 19 Uhr abholen. Bitte klären Sie, ob diese Aufbau- und Abholzeiten von Ihrer Flächennutzung umfasst sind. Eine Abholung um 18 Uhr können wir am Veranstaltungstag wegen eines anderen Auftrags nicht garantieren. Die Zwischenreinigung ist für Samstagvormittag geplant und erfordert freien Zugang.

Sie hatten außerdem nach einem Wasserkocher gefragt. Wir vermieten derzeit keine Kochgeräte für diesen Zweck. Wenn Sie isolierte Getränkebehälter verwenden, berücksichtigen Sie bitte das Gewicht und einen standsicheren Tisch. Zelte liefern wir nicht. Eine Bestellung sämtlicher hier genannter Leistungen ist noch nicht erfolgt. Für Rückfragen erreichen Sie uns unter service@platzpause.example.

Mit freundlichen Grüßen
Platzpause Service GmbH'''),
T('14_Chat_Konzeptkorrektur.txt','Organisation am 1. Oktober','01.10.2026','01.10.2026 18:14 Ottilie: Der Nachtplan braucht gleichzeitig nur vier eigene Personen. Warum vier Zelte?\n01.10.2026 18:19 Balthasar: Die erste Idee war großzügiger. Zwei Zweipersonenzelte könnten reichen, wenn nicht alle gleichzeitig schlafen.\n01.10.2026 18:23 Yasmin: Bitte nicht die Gäste aus Halle in diese Rechnung schieben. Das sind andere Personen und ein anderes Programm.\n01.10.2026 18:31 Balthasar: Ich schreibe ihnen heute, dass wir keine verbindliche Zusage geben können.\n01.10.2026 18:40 Ottilie: Und statt Küche schreiben wir Teestation. Es war wirklich nie ein Gasherd geplant.'),
E('15_An_Gaestegruppe.eml','Übernachtung noch nicht zugesagt','2026-10-01T19:06:00+02:00','Balthasar Knödel <balthasar@bankgespraech.example>','Kulturgruppe Hallenlicht <kontakt@hallenlicht.example>','Liebe Jana,\n\nich muss mein spontanes Angebot korrigieren. Unsere Gruppe hat keine acht zusätzlichen Schlafplätze beschlossen, und die Infrastruktur ist noch in Abstimmung. Bitte plant nicht verbindlich mit einer Übernachtung bei uns. Ich möchte euch rechtzeitig sagen, dass ihr eine andere Unterkunft suchen solltet. Es tut mir leid, dass ich vorschnell war.\n\nViele Grüße\nBalthasar'),
D('16_Beschluss_Orga.docx','Stand der gemeinsamen Planung','02.10.2026','Yasmin Wippermann, Ottilie Karg und Balthasar Knödel','Interne Ablage und anwaltliche Beratung', '''Wir haben heute Morgen gemeinsam den Stand des Campkonzepts besprochen. Die dreitägige öffentliche Auseinandersetzung mit der Nutzung des Brunnenplatzes bleibt unser gemeinsames Ziel. Die tagsüber geplanten Gesprächsrunden und die Ausstellung sollen unverändert vorbereitet werden. Für die Nachtstunden wollen wir eine ruhige, sichtbare Mahnwache mit wechselnder Besetzung beschreiben. Dafür benötigen wir noch eine klare Erläuterung, welche Aussage diese Präsenz über die bloße Bewachung von Material hinaus vermittelt.

Wir gehen nach dem aktuellen Schichtplan von vier eigenen Personen gleichzeitig in jeder Nacht aus. Zwei sollen ansprechbar sein, zwei können ruhen. Die Schichten werden innerhalb dieser Gruppe gewechselt. Vier Schlafzelte erscheinen uns nach dieser Rechnung nicht mehr erforderlich. Wir möchten mit der Kanzlei prüfen, ob zwei kleine Zelte und das offene Gesprächszelt als Wetterschutz ein tragfähiger Vorschlag sind. Eine endgültige Änderung der Anzeige hat Yasmin noch nicht abgesandt.

Das Übernachtungsangebot an acht externe Gäste wird nicht aufrechterhalten. Balthasar hat dies am Vorabend mitgeteilt. Die betreffende Gruppe kann selbstverständlich wie andere Besucher an unseren öffentlichen Gesprächsrunden teilnehmen. Daraus folgt aber keine Zusage einer Unterkunft. Es soll keine verdeckte Reservierung im Nachtplan geben.

Die Bezeichnung Gemeinschaftsküche wird berichtigt. Vorgesehen ist eine Teestation ohne Kochen und ohne Gas. Die größere barrierearme Toilette könnte zusätzliche Fläche benötigen; vor einer Bestellung warten wir die Maßzeichnung ab. Yasmin darf die anwaltliche Beratung beauftragen und den abgestimmten Ergänzungstext nach Freigabe an die Versammlungsstelle senden. Eine Klage, ein Anerkenntnis behördlicher Vorgaben oder ein endgültiger Verzicht auf die Nachtpräsenz sind von diesem internen Beschluss nicht umfasst.'''),
E('17_Konzeptkorrektur.eml','Heutiger Planungsstand im Anhang','2026-10-02T10:04:00+02:00','Yasmin Wippermann <yasmin@bankgespraech.example>','Jule Morgen <post@kanzlei-kanal.example>','Sehr geehrte Frau Morgen,\n\nim Anhang unser heutiger gemeinsamer Stand. Bitte verwechseln Sie ihn nicht mit einer bereits abgesandten Änderung der Anzeige. Die Frist aus der Mail der Versammlungsstelle endet am Dienstag um 12 Uhr. Wir möchten vorher den fertigen Text lesen.\n\nMit freundlichen Grüßen\nYasmin Wippermann'),
E('18_Rueckmeldung_Gaeste.eml','Andere Unterkunft gefunden','2026-10-02T11:21:00+02:00','Kulturgruppe Hallenlicht <kontakt@hallenlicht.example>','Balthasar Knödel <balthasar@bankgespraech.example>','Lieber Balthasar,\n\ndanke für die schnelle Klarstellung. Wir haben heute acht Betten in einer Jugendherberge angefragt und die Reservierung bestätigt bekommen. Bei euch rechnen wir nicht mehr mit Schlafplätzen. Zwei von uns möchten vielleicht am Sonntag an eurer Abschlussrunde teilnehmen. Das entscheiden sie vor Ort.\n\nViele Grüße\nJana')]))
