"""Gemeinsame Anzeigeaufbereitung für generierte Markdown-Übersichten."""

from __future__ import annotations

import re
from pathlib import Path
from runpy import run_path


_REPAIR_SCRIPT = Path(__file__).with_name("fix-readmes-umlaute-und-zip.py")
_TRANSFORM_TEXT = run_path(str(_REPAIR_SCRIPT))["transform_text"]
_WAVE_2 = run_path(str(Path(__file__).with_name("sweep-umlaut-welle-2.py")))
_WAVE_3 = run_path(str(Path(__file__).with_name("sweep-umlaut-welle-3.py")))
_PLUGIN_README = run_path(
    str(Path(__file__).with_name("inject-direkt-loslegen-section.py"))
)
_DISPLAY_PROTECT_PATTERNS = tuple(
    pattern
    for pattern in _WAVE_2["PROTECT_PATTERNS"]
    if pattern.pattern != r"\b[a-z]{18,}\b"
)
_PROSE_REPLACEMENTS = {
    **_PLUGIN_README["PROSE_REPLACEMENTS"],
    "Anfaenger": "Anfänger",
    "anfaenger": "anfänger",
    "Einschaetzung": "Einschätzung",
    "einschaetzung": "einschätzung",
    "Erstgespraech": "Erstgespräch",
    "erstgespraech": "erstgespräch",
    "Gesetzentwuerfen": "Gesetzentwürfen",
    "gesetzentwuerfen": "gesetzentwürfen",
    "Bauueberwachung": "Bauüberwachung",
    "bauueberwachung": "bauüberwachung",
    "Behoerden": "Behörden",
    "behoerden": "behörden",
    "Behoerde": "Behörde",
    "behoerde": "behörde",
    "Kuendigung": "Kündigung",
    "kuendigung": "kündigung",
    "Buergschaft": "Bürgschaft",
    "buergschaft": "bürgschaft",
    "Ruege": "Rüge",
    "ruege": "rüge",
    "Ruegen": "Rügen",
    "ruegen": "rügen",
    "Luecken": "Lücken",
    "luecken": "lücken",
    "Steürn": "Steuern",
    "steürn": "steuern",
    "Umsatzsteür": "Umsatzsteuer",
    "umsatzsteür": "umsatzsteuer",
    "BAfoeG": "BAföG",
    "Bafoeg": "BAföG",
    "BAFOEG": "BAföG",
    "DueV": "DüV",
    "GOAE": "GOÄ",
    "Goae": "GOÄ",
    "WpueG": "WpÜG",
    "Wpueg": "WpÜG",
    "AueG": "AÜG",
    "Aueg": "AÜG",
    "AEK": "ÄK",
    "Aek": "ÄK",
    "OEPNV": "ÖPNV",
    "OePNV": "ÖPNV",
    "Oepnv": "ÖPNV",
    "Eigentuemsübergang": "Eigentumsübergang",
    "Themaeingrenzung": "Themeneingrenzung",
}
_INTERNAL_REPLACEMENTS = (
    ("abhaeng", "abhäng"),
    ("abfaell", "abfäll"),
    ("abschoepf", "abschöpf"),
    ("adhaes", "adhäs"),
    ("aegypt", "ägypt"),
    ("aequatorial", "äquatorial"),
    ("aequival", "äquival"),
    ("aethiop", "äthiop"),
    ("aelter", "älter"),
    ("aehn", "ähn"),
    ("aender", "änder"),
    ("anaesth", "anästh"),
    ("aerzt", "ärzt"),
    ("aeste", "äste"),
    ("aeusser", "äußer"),
    ("aktionaer", "aktionär"),
    ("annaeher", "annäher"),
    ("anlaess", "anläss"),
    ("antraeg", "anträg"),
    ("ansaess", "ansäss"),
    ("anruehr", "anrühr"),
    ("auskuenft", "auskünft"),
    ("ausruest", "ausrüst"),
    ("ausueb", "ausüb"),
    ("ausfuell", "ausfüll"),
    ("ausschuett", "ausschütt"),
    ("ausschluess", "ausschlüss"),
    ("ausschue", "ausschü"),
    ("aussagetuecht", "aussagetücht"),
    ("autoritaer", "autoritär"),
    ("behoerd", "behörd"),
    ("beitraeg", "beiträg"),
    ("belaest", "beläst"),
    ("beeintraecht", "beeinträcht"),
    ("boes", "bös"),
    ("beguenst", "begünst"),
    ("beschaeft", "beschäft"),
    ("beschlue", "beschlü"),
    ("beschaed", "beschäd"),
    ("beschraenk", "beschränk"),
    ("bestaend", "beständ"),
    ("betraeg", "beträg"),
    ("bevollmaechtig", "bevollmächtig"),
    ("boers", "börs"),
    ("buecher", "bücher"),
    ("buehn", "bühn"),
    ("buend", "bünd"),
    ("buerg", "bürg"),
    ("buerokr", "bürokr"),
    ("bueroneubau", "büroneubau"),
    ("daen", "dän"),
    ("denkmaeler", "denkmäler"),
    ("dienstgeraet", "dienstgerät"),
    ("doerf", "dörf"),
    ("doppelboed", "doppelböd"),
    ("dueng", "düng"),
    ("eigenstaend", "eigenständ"),
    ("eigentuemer", "eigentümer"),
    ("endguelt", "endgült"),
    ("entschaed", "entschäd"),
    ("entschliess", "entschließ"),
    ("entschluessel", "entschlüssel"),
    ("entwaesser", "entwässer"),
    ("entwuerf", "entwürf"),
    ("europae", "europä"),
    ("erfuell", "erfüll"),
    ("ergaenz", "ergänz"),
    ("erhaelt", "erhält"),
    ("erhoeh", "erhöh"),
    ("erlaess", "erläss"),
    ("faellig", "fällig"),
    ("faelle", "fälle"),
    ("faeh", "fäh"),
    ("faeroe", "färö"),
    ("foederal", "föderal"),
    ("foerm", "förm"),
    ("franzoes", "französ"),
    ("geringfueg", "geringfüg"),
    ("fuell", "füll"),
    ("fuenf", "fünf"),
    ("gebaeud", "gebäud"),
    ("geraet", "gerät"),
    ("geruest", "gerüst"),
    ("geschaeft", "geschäft"),
    ("gestaend", "geständ"),
    ("gehaelter", "gehälter"),
    ("gewaess", "gewäss"),
    ("glaeub", "gläub"),
    ("groenland", "grönland"),
    ("groess", "größ"),
    ("gruend", "gründ"),
    ("gruen", "grün"),
    ("guelt", "gült"),
    ("guete", "güte"),
    ("gueter", "güter"),
    ("gehoer", "gehör"),
    ("grenzgaeng", "grenzgäng"),
    ("haend", "händ"),
    ("haendl", "händl"),
    ("haert", "härt"),
    ("haeufig", "häufig"),
    ("haeus", "häus"),
    ("haem", "häm"),
    ("hoefe", "höfe"),
    ("hoehe", "höhe"),
    ("hoechst", "höchst"),
    ("hoergeraet", "hörgerät"),
    ("hoer", "hör"),
    ("huette", "hütte"),
    ("inkuenft", "inkünft"),
    ("jaehr", "jähr"),
    ("jued", "jüd"),
    ("kapitaleinkuenft", "kapitaleinkünft"),
    ("komplementaer", "komplementär"),
    ("koenig", "könig"),
    ("koeln", "köln"),
    ("kaufmaenn", "kaufmänn"),
    ("kostendaempf", "kostendämpf"),
    ("kraeft", "kräft"),
    ("kuerz", "kürz"),
    ("laeng", "läng"),
    ("laerm", "lärm"),
    ("luebeck", "lübeck"),
    ("lueth", "lüth"),
    ("maengel", "mängel"),
    ("maess", "mäß"),
    ("mandatstraeg", "mandatsträg"),
    ("menschenwuerd", "menschenwürd"),
    ("moebel", "möbel"),
    ("moeg", "mög"),
    ("muell", "müll"),
    ("muendel", "mündel"),
    ("muendlich", "mündlich"),
    ("natuer", "natür"),
    ("noet", "nöt"),
    ("nuernberg", "nürnberg"),
    ("oeff", "öff"),
    ("oert", "ört"),
    ("organnaehe", "organnähe"),
    ("paecht", "pächt"),
    ("paedagog", "pädagog"),
    ("palaest", "paläst"),
    ("persoen", "persön"),
    ("phaen", "phän"),
    ("plaen", "plän"),
    ("praedikt", "prädikt"),
    ("praekl", "präkl"),
    ("praenatal", "pränatal"),
    ("praeferenz", "präferenz"),
    ("praereg", "präreg"),
    ("praez", "präz"),
    ("praerog", "prärog"),
    ("praetorisch", "prätorisch"),
    ("raeuber", "räuber"),
    ("raeum", "räum"),
    ("rumaen", "rumän"),
    ("rueg", "rüg"),
    ("ruerup", "rürup"),
    ("saechs", "sächs"),
    ("saeum", "säum"),
    ("saeul", "säul"),
    ("saetz", "sätz"),
    ("saemt", "sämt"),
    ("schaed", "schäd"),
    ("schluessel", "schlüssel"),
    ("schoepf", "schöpf"),
    ("schuel", "schül"),
    ("schuetz", "schütz"),
    ("selbststaend", "selbstständ"),
    ("sonderbaend", "sonderbänd"),
    ("souveraen", "souverän"),
    ("spaet", "spät"),
    ("staedt", "städt"),
    ("staend", "ständ"),
    ("stuetz", "stütz"),
    ("straeg", "sträg"),
    ("sued", "süd"),
    ("taeg", "täg"),
    ("taeusch", "täusch"),
    ("tatsaech", "tatsäch"),
    ("traeg", "träg"),
    ("tuer", "tür"),
    ("toet", "töt"),
    ("uebung", "übung"),
    ("ueble", "üble"),
    ("ungewoehn", "ungewöhn"),
    ("unguenst", "ungünst"),
    ("unterstuetz", "unterstütz"),
    ("untertaen", "untertän"),
    ("unverzueg", "unverzüg"),
    ("verbaend", "verbänd"),
    ("veterinaer", "veterinär"),
    ("verhaeltn", "verhältn"),
    ("verfueg", "verfüg"),
    ("verguet", "vergüt"),
    ("verkuend", "verkünd"),
    ("verkuerz", "verkürz"),
    ("verlaeng", "verläng"),
    ("verwaesser", "verwässer"),
    ("verschluessel", "verschlüssel"),
    ("verstoess", "verstöß"),
    ("voelker", "völker"),
    ("voelkling", "völkling"),
    ("vorgaeng", "vorgäng"),
    ("vorschlaeg", "vorschläg"),
    ("vorstaend", "vorständ"),
    ("vorlaeuf", "vorläuf"),
    ("waehler", "wähler"),
    ("waend", "wänd"),
    ("waerm", "wärm"),
    ("wechseldatentraeg", "wechseldatenträg"),
    ("wertgegenstaend", "wertgegenständ"),
    ("wilhelmshoehe", "wilhelmshöhe"),
    ("willensmaengel", "willensmängel"),
    ("wuensch", "wünsch"),
    ("zaehl", "zähl"),
    ("zulaeng", "zuläng"),
    ("zuschlaeg", "zuschläg"),
    ("zuecht", "zücht"),
    ("zoell", "zöll"),
    ("zugaeng", "zugäng"),
    ("zugestaend", "zugeständ"),
    ("zusaetz", "zusätz"),
    ("zustaend", "zuständ"),
)
_STEM_REPLACEMENTS = (
    ("Aussergewoehn", "Außergewöhn"),
    ("aussergewoehn", "außergewöhn"),
    ("Berufsausueb", "Berufsausüb"),
    ("berufsausueb", "berufsausüb"),
    ("Grenzueber", "Grenzüber"),
    ("grenzueber", "grenzüber"),
    ("Verhältnismaess", "Verhältnismäß"),
    ("verhältnismaess", "verhältnismäß"),
    ("Zahlungsunfaeh", "Zahlungsunfäh"),
    ("zahlungsunfaeh", "zahlungsunfäh"),
    ("Verpflichtungsermaechtig", "Verpflichtungsermächtig"),
    ("verpflichtungsermaechtig", "verpflichtungsermächtig"),
    ("Vollstaend", "Vollständ"),
    ("vollstaend", "vollständ"),
    ("Laienverstaend", "Laienverständ"),
    ("laienverstaend", "laienverständ"),
    ("Staatsangehoer", "Staatsangehör"),
    ("staatsangehoer", "staatsangehör"),
    ("Unabhaeng", "Unabhäng"),
    ("unabhaeng", "unabhäng"),
    ("Dokumentationslueck", "Dokumentationslück"),
    ("dokumentationslueck", "dokumentationslück"),
    ("Energiepreiserhoeh", "Energiepreiserhöh"),
    ("energiepreiserhoeh", "energiepreiserhöh"),
    ("Gebuehrenunterschreit", "Gebührenunterschreit"),
    ("gebuehrenunterschreit", "gebührenunterschreit"),
    ("Minderjaehr", "Minderjähr"),
    ("minderjaehr", "minderjähr"),
    ("Versicherungsvertraeg", "Versicherungsverträg"),
    ("versicherungsvertraeg", "versicherungsverträg"),
    ("Angehoer", "Angehör"),
    ("angehoer", "angehör"),
    ("Bevoelk", "Bevölk"),
    ("bevoelk", "bevölk"),
    ("Bonitaet", "Bonität"),
    ("bonitaet", "bonität"),
    ("Einschaetz", "Einschätz"),
    ("einschaetz", "einschätz"),
    ("Fahrlaess", "Fahrläss"),
    ("fahrlaess", "fahrläss"),
    ("Fristenversaeum", "Fristenversäum"),
    ("fristenversaeum", "fristenversäum"),
    ("Geldwaesch", "Geldwäsch"),
    ("geldwaesch", "geldwäsch"),
    ("Humanitaer", "Humanitär"),
    ("humanitaer", "humanitär"),
    ("Identitaet", "Identität"),
    ("identitaet", "identität"),
    ("Insolvenznaehe", "Insolvenznähe"),
    ("insolvenznaehe", "insolvenznähe"),
    ("Kollegialitaet", "Kollegialität"),
    ("kollegialitaet", "kollegialität"),
    ("Konformitaet", "Konformität"),
    ("konformitaet", "konformität"),
    ("Qualitaet", "Qualität"),
    ("qualitaet", "qualität"),
    ("Sanierungsnaehe", "Sanierungsnähe"),
    ("sanierungsnaehe", "sanierungsnähe"),
    ("Sammelfaeh", "Sammelfäh"),
    ("sammelfaeh", "sammelfäh"),
    ("Sozietaet", "Sozietät"),
    ("sozietaet", "sozietät"),
    ("Anfaeng", "Anfäng"),
    ("anfaeng", "anfäng"),
    ("Anhoer", "Anhör"),
    ("anhoer", "anhör"),
    ("Anwaelt", "Anwält"),
    ("anwaelt", "anwält"),
    ("Aussen", "Außen"),
    ("aussen", "außen"),
    ("Begruend", "Begründ"),
    ("begruend", "begründ"),
    ("Bezueg", "Bezüg"),
    ("bezueg", "bezüg"),
    ("Brueck", "Brück"),
    ("brueck", "brück"),
    ("Buerger", "Bürger"),
    ("buerger", "bürger"),
    ("Deckungslueck", "Deckungslück"),
    ("deckungslueck", "deckungslück"),
    ("Einfuehr", "Einführ"),
    ("einfuehr", "einführ"),
    ("Eroeff", "Eröff"),
    ("eroeff", "eröff"),
    ("Erhoeh", "Erhöh"),
    ("erhoeh", "erhöh"),
    ("Erklaer", "Erklär"),
    ("erklaer", "erklär"),
    ("Ermaechtig", "Ermächtig"),
    ("ermaechtig", "ermächtig"),
    ("Faeh", "Fäh"),
    ("faeh", "fäh"),
    ("Flaech", "Fläch"),
    ("flaech", "fläch"),
    ("Foerder", "Förder"),
    ("foerder", "förder"),
    ("Frueh", "Früh"),
    ("frueh", "früh"),
    ("Fuehr", "Führ"),
    ("fuehr", "führ"),
    ("Gebuehr", "Gebühr"),
    ("gebuehr", "gebühr"),
    ("Geflueg", "Geflüg"),
    ("geflueg", "geflüg"),
    ("Gespraech", "Gespräch"),
    ("gespraech", "gespräch"),
    ("Grundstueck", "Grundstück"),
    ("grundstueck", "grundstück"),
    ("Grundzueg", "Grundzüg"),
    ("grundzueg", "grundzüg"),
    ("Haert", "Härt"),
    ("haert", "härt"),
    ("Haustuer", "Haustür"),
    ("haustuer", "haustür"),
    ("Hoeflich", "Höflich"),
    ("hoeflich", "höflich"),
    ("Klaer", "Klär"),
    ("klaer", "klär"),
    ("Koerper", "Körper"),
    ("koerper", "körper"),
    ("Kuendig", "Kündig"),
    ("kuendig", "kündig"),
    ("Kuenst", "Künst"),
    ("kuenst", "künst"),
    ("Laend", "Länd"),
    ("laend", "länd"),
    ("Loes", "Lös"),
    ("loes", "lös"),
    ("Lueck", "Lück"),
    ("lueck", "lück"),
    ("Maess", "Mäß"),
    ("maess", "mäß"),
    ("Militaer", "Militär"),
    ("militaer", "militär"),
    ("Mueller", "Müller"),
    ("mueller", "müller"),
    ("Naech", "Näch"),
    ("naech", "näch"),
    ("Nebentaet", "Nebentät"),
    ("nebentaet", "nebentät"),
    ("Oeff", "Öff"),
    ("oeff", "öff"),
    ("Oek", "Ök"),
    ("oek", "ök"),
    ("Oepp", "ÖPP"),
    ("oepp", "öpp"),
    ("Oester", "Öster"),
    ("oester", "öster"),
    ("Pfaend", "Pfänd"),
    ("pfaend", "pfänd"),
    ("Praes", "Präs"),
    ("praes", "präs"),
    ("Praevent", "Prävent"),
    ("praevent", "prävent"),
    ("Prue", "Prü"),
    ("prue", "prü"),
    ("Roem", "Röm"),
    ("roem", "röm"),
    ("Rueck", "Rück"),
    ("rueck", "rück"),
    ("Schaerf", "Schärf"),
    ("schaerf", "schärf"),
    ("Schaetz", "Schätz"),
    ("schaetz", "schätz"),
    ("Schwaerz", "Schwärz"),
    ("schwaerz", "schwärz"),
    ("Stoer", "Stör"),
    ("stoer", "stör"),
    ("Taet", "Tät"),
    ("taet", "tät"),
    ("Thuer", "Thür"),
    ("thuer", "thür"),
    ("Ueber", "Über"),
    ("ueber", "über"),
    ("Veraender", "Veränder"),
    ("veraender", "veränder"),
    ("Verjaehr", "Verjähr"),
    ("verjaehr", "verjähr"),
    ("Vermoeg", "Vermög"),
    ("vermoeg", "vermög"),
    ("Verstaend", "Verständ"),
    ("verstaend", "verständ"),
    ("Vertraeg", "Verträg"),
    ("vertraeg", "verträg"),
    ("Veroeff", "Veröff"),
    ("veroeff", "veröff"),
    ("Versaeum", "Versäum"),
    ("versaeum", "versäum"),
    ("Waehr", "Währ"),
    ("waehr", "währ"),
    ("Woerter", "Wörter"),
    ("woerter", "wörter"),
    ("Wuerdig", "Würdig"),
    ("wuerdig", "würdig"),
    ("Wuertt", "Württ"),
    ("wuertt", "württ"),
    ("Zwoelf", "Zwölf"),
    ("zwoelf", "zwölf"),
)


def display_prose(text: str) -> str:
    """Stellt Prosa mit Umlauten dar und schützt Slugs, Links und Code."""
    value = _TRANSFORM_TEXT(text).replace("§§", "Paragrafen").replace("§", "Paragraf")
    placeholders: list[str] = []

    def stash(match: re.Match[str]) -> str:
        placeholders.append(match.group(0))
        return f"\x00PROTECT{len(placeholders) - 1}\x00"

    protected = value
    for pattern in _DISPLAY_PROTECT_PATTERNS:
        protected = pattern.sub(stash, protected)
    protected = _WAVE_2["apply_replacements"](protected)
    protected = _WAVE_3["apply_stem_replacements"](protected)
    for old, new in _STEM_REPLACEMENTS:
        protected = protected.replace(old, new)
    for old, new in _INTERNAL_REPLACEMENTS:
        protected = protected.replace(old, new)
        protected = protected.replace(old.capitalize(), new.capitalize())
    for old, new in sorted(
        _PROSE_REPLACEMENTS.items(), key=lambda item: len(item[0]), reverse=True
    ):
        protected = re.sub(r"\b" + re.escape(old), new, protected)
    return _WAVE_2["unstash_protected"](protected, placeholders)
