"""Drei fiktive Mandatsakten zum Markenamt-Assistenten; keine Musterlösungen."""
from __future__ import annotations


def d(file,title,body='',**kw):return {'file':file,'title':title,'body':body,**kw}
def mail(file,title,sender,recipient,body,date='2026-09-28T10:30:00+02:00'):
 return d(file,title,body,**{'from':sender,'to':recipient,'date':date})
def case(slug,title,client,summary,assignment,documents):
 return {'slug':slug,'plugin':'markenamt-assistent','title':title,'subtitle':title,'date':'01.10.2026','client':client,'summary':summary,'assignment':assignment,'documents':documents}
CASES=[]
CASES.append(case('markenamt-rumpelrad','Rumpelrad – Das Fahrrad passt in den Hausflur','Rumpelrad Mobilität UG (haftungsbeschränkt)',
 'Drei Berliner Gründer bauen ein kompaktes Lastenfahrrad. Die Markenakte beginnt vor der Registereintragung der Gesellschaft und enthält zwei Logoentwürfe, einen ähnlich klingenden Registertreffer, eine fehlerhafte Gebührenanforderung und eine noch nicht abgeschickte Anmeldung.',
 'Übernehmen Sie die Markenanmeldung. Klären Sie anhand der Unterlagen Inhaberschaft, Markenform, Verzeichnis, Rechercheumfang und Gebühren. Erstellen Sie eine vollständige Anmeldefassung und die gezielt notwendigen Rückfragen. Eine tatsächliche externe Einreichung ist nicht beauftragt.',[
 d('01_Mandatsaufnahme.docx','Mandatsaufnahme vom 28.09.2026',[
 'Die Rumpelrad Mobilität UG (haftungsbeschränkt) entwickelt ein zweirädriges Lastenfahrrad mit einklappbarer Ladefläche. In Hausfluren soll nur ein schmaler Stellplatz benötigt werden. Der erste Vertrieb ist in Berlin und Leipzig geplant; eine niederländische Händlerin hat unverbindliches Interesse bekundet. Eine Serienzulassung und ein verbindlicher Liefertermin liegen noch nicht vor.',
 'Gesellschafter sind Ottilie Knorr, Produktdesignerin, mit 50 Prozent, Idris Feuerlein, Softwareentwickler, mit 30 Prozent, und Eberhard Funke, Fahrradmechaniker, mit 20 Prozent. Die Satzung wurde am 12.08.2026 beurkundet. Geschäftsführerin ist Ottilie Knorr. Das interne Firmenblatt nennt die Eintragung am 21.09.2026. Davor wurden Entwürfe teils von Ottilie privat und teils mit dem Zusatz „i. G.“ bestellt.',
 'Die Geschäftsführerin möchte eine deutsche Wortmarke. Im alten Onlineentwurf steht aber Ottilie als Anmelderin und die Agentur hat ein Bildzeichen beigefügt. Der Auftrag umfasst die Bereinigung dieses Entwurfs und die Vorbereitung der Einreichung. Ottilie möchte die Daten vor dem Absenden vollständig sehen. Über eine EU-Anmeldung soll erst nach dem Gespräch mit der Händlerin entschieden werden.' ],date='28.09.2026',sender='Kanzlei Salome Hummel',reference='26-104-RR'),
 d('02_Firmenblatt.pdf','Firmenblatt aus der Geschäftsablage',[
 'Firma: Rumpelrad Mobilität UG (haftungsbeschränkt). Sitz Berlin. Geschäftsanschrift: Werkhof 18, 10997 Berlin. Geschäftsführerin: Ottilie Knorr, geboren am 14.05.1990. Stammkapital: 3.000 EUR. Interne Referenz des Registerabrufs: RR-HR-20260922. Dieses Firmenblatt ist die von der Assistenz angefertigte Abschrift der Stammdaten; der amtliche Registerauszug wurde noch nicht zur Mandatsakte übermittelt.',
 'Die Ablage notiert: Anmeldung zum Handelsregister 18.08.2026; Eintragung 21.09.2026. Der Wortlaut der Vertretungsregel wurde in der Tabelle nicht erfasst. Ottilie verwendet seit 22.09.2026 die Firma ohne Gründungszusatz.' ],date='22.09.2026',sender='Rumpelrad / Büro'),
 mail('03_Email_Markenwunsch.eml','Bitte endlich RUMPELRAD anmelden','Ottilie Knorr <ottilie@rumpelrad.example>','Salome Hummel <kanzlei@hummel.example>',
 'Guten Morgen Frau Hummel,\n\nwir möchten RUMPELRAD als Wort schützen, ohne das kleine Rad über dem U. Die Agentur meint, das Logo sei ohnehin stärker. Mir ist wichtig, dass der Name zur UG gehört. Im August hatte ich mich privat durch das Formular geklickt. Ich weiß nicht, ob das schon draußen ist. Es gibt nur den gespeicherten Entwurf in der Anlage, kein Aktenzeichen.\n\nBitte nehmen Sie nicht automatisch die EU-Variante. Unser Budget für die erste Amtsgebühr beträgt 500 EUR. Die Anmeldung soll nach meiner Freigabe erfolgen.\n\nHerzliche Grüße\nOttilie'),
 d('04_Chat_Produktumfang.txt','Chat aus dem Produktkanal','24.09.2026 09:12 Idris: Die App ist vorerst nur ein herunterladbarer Prototyp. Keine Cloud-Abos.\n24.09.2026 09:14 Eberhard: Reparieren werden wir unsere eigenen Räder, aber auch Nachbarräder gegen Rechnung.\n24.09.2026 09:18 Ottilie: Und vielleicht später Kindersitze und Helme?\n24.09.2026 09:19 Idris: Dafür gibt es noch keinen Hersteller und keinen Beschluss.\n24.09.2026 09:24 Eberhard: Bitte nicht „alles mit Mobilität“. Im Laden wollen wir eigene Räder und ausgewählte fremde Fahrradschlösser verkaufen.\n24.09.2026 09:27 Ottilie: Das klingt nach mehr Klassen. Bitte Kosten nebeneinander zeigen.'),
 d('05_Produktblatt.docx','Produkt- und Leistungsbeschreibung',[
 'RUMPELRAD K1 ist ein nicht elektrisch unterstütztes Lastenfahrrad. Die Ladefläche klappt bei abgestelltem Rad seitlich hoch. Ein separat erhältliches elektronisches Schloss kann über eine herunterladbare App geöffnet werden. Die App zeigt keine öffentlichen Mietfahrzeuge und bietet keine Zahlungsabwicklung. Der vorliegende Plan nennt Android und iOS; ein webbasierter Dienst wird nicht angeboten.',
 'Der Werkstattbetrieb soll ab Februar 2027 eigene und fremde Fahrräder reparieren. Ein kleiner Verkaufsraum wird Ersatzteile und Fahrradschlösser anderer Hersteller anbieten. Die Geschäftsführung hat noch nicht beschlossen, ob auch ein Onlinehandel für fremde Waren betrieben wird. Eine Fahrzeugvermietung ist ausdrücklich nicht vorgesehen.',
 'Bis heute existieren vier fahrfähige Prototypen. Kein Fahrrad wurde verkauft. Die Testfahrten wurden ausschließlich intern organisiert. Eine spätere elektrische Variante steht auf einer Ideenliste, ohne Budget oder Entwicklungsauftrag.' ],date='25.09.2026'),
 d('06_Designvertrag_Entwurf.docx','Entwurf der Vereinbarung mit der Designagentur',[
 '1. Parteien\nAuftraggeberin ist nach dem bisherigen Entwurf Ottilie Knorr, handelnd für das Projekt Rumpelrad. Auftragnehmerin ist die Rasterfink Gestaltung GmbH, vertreten durch Milena Özdemir. Die Parteien haben die Auftraggeberbezeichnung nach Gründung der UG noch nicht angepasst.',
 '2. Leistungen und Vergütung\nDie Agentur erstellt zwei Wort-/Bildzeichen und ein Farbkonzept. Vereinbart sind 1.800 EUR netto zuzüglich Umsatzsteuer. Die Schlussrechnung ist fällig nach Lieferung der druckfähigen Dateien. Die vorhandene Rechnung wurde von der UG bezahlt.',
 '3. Nutzungsrechte\nNach vollständiger Zahlung erhält die Auftraggeberin ausschließliche Nutzungsrechte für Werbung, Verpackung und digitale Auftritte. Eine ausdrückliche Regelung zur Markenanmeldung oder Weiterübertragung an die UG enthält der bisherige Text nicht. Änderungen des Logos sollen mit der Agentur abgestimmt werden.',
 '4. Bearbeitungsstand\nDer Entwurf wurde am 03.09.2026 von der Agentur per E-Mail übersandt. Eine unterschriebene Fassung befindet sich nicht in dieser Ablage.' ],date='03.09.2026'),
 d('07_Rechnung_Design.pdf','Rechnung RF-2026-118',[
 'Rasterfink Gestaltung GmbH an Rumpelrad Mobilität UG (haftungsbeschränkt), Werkhof 18, 10997 Berlin. Leistungszeitraum 15.08.–12.09.2026. Geliefert wurden zwei Logoentwürfe und die Farbpalette. Zahlungsziel 14 Tage. Der Leistungsnachweis verweist auf den Angebotsentwurf vom 03.09.2026.',
 'Nettobetrag 1.800,00 EUR; Umsatzsteuer 19 Prozent 342,00 EUR; Rechnungsbetrag 2.142,00 EUR. Die Buchhaltung hat am 19.09.2026 den Zahlungsausgang erfasst. Die Rechnung enthält keine gesonderte Erklärung zur Markeninhaberschaft.' ],date='13.09.2026'),
 mail('08_Email_Agentur.eml','Rechte und richtige Logodatei','Milena Özdemir <milena@rasterfink.example>','Ottilie Knorr <ottilie@rumpelrad.example>',
 'Liebe Ottilie,\n\ndie bezahlten Dateien dürft ihr für euer Unternehmen nutzen. Unser Vertragsentwurf ist leider noch auf deinen Namen geschrieben. Sende mir bitte die vollständige Firmierung, damit wir das sauber nachziehen. Für eine Wortmarke braucht ihr die Logo-PNG natürlich nicht. Die finale Wort-/Bildfassung wäre RR_02_blau, nicht die graue Vorstufe RR_01.\n\nEine unterschriebene Ergänzung können wir diese Woche machen.\n\nViele Grüße\nMilena',date='2026-09-26T14:10:00+02:00'),
 d('09_Anmeldeentwurf.docx','Gespeicherter Anmeldeentwurf vom 19.08.2026',[
 'Der Entwurf wurde lokal aus der Arbeitsmaske in eine Textdatei übertragen. Anmelderin: Ottilie Knorr, Werkhof 18, Berlin. Markentyp: Wort-/Bildmarke. Angegebener Wortbestandteil: RUMPELRAD. Bilddatei: RR_01_grau.png. Verzeichnis: „Fahrräder; Software; Verkauf; Reparaturen; Mobilität“. Klassenfeld: 9, 12, 35.',
 'Priorität: keine Angabe. Vertreter: nicht eingetragen. Zahlungsart: noch nicht gewählt. Das interne Kommentarfeld lautet: „Später vielleicht Firma einsetzen“. Der Entwurf trägt keine Sendebestätigung und keine amtliche Nummer. Im Browserordner ist lediglich die Kennzeichnung „lokal gespeichert“ sichtbar.' ],date='19.08.2026'),
 d('10_Arbeitsansicht_Entwurf.png','Interne Ablage: Markenentwürfe','RR_20260819 – Status: lokal gespeichert\nAnmelderin: Ottilie Knorr\nMarkenform: Wort-/Bildmarke\nAnhang: RR_01_grau.png\nKein Aktenzeichen hinterlegt\nLetzte Bearbeitung: 19.08.2026 18:47\nAufgabe: mit Geschäftsführerin abgleichen',date='28.09.2026'),
 d('11_Recherchenotiz.pdf','Rechercheauszug der Assistenz',[
 'Die Assistenz suchte am 25.09.2026 nur nach dem exakt geschriebenen Wort RUMPELRAD im deutschen Register. In ihrer Notiz steht „kein identischer Treffer“. Eine zweite Suche nach RUMPEL ergab mehrere Treffer. Die Namen und Nummern wurden nicht vollständig übernommen.',
 'Ein für die Besprechung notierter Treffer lautet RUMMELRAD, Wortmarke, deutsche Anmeldung vom 17.02.2022, als eingetragen notiert, unter anderem Fahrradzubehör. Der amtliche Datensatz, das vollständige Verzeichnis und die Inhaberhistorie fehlen in der Ablage. Die Notiz soll keine tatsächliche Registerauskunft ersetzen.',
 'Die Internetadressen rumpelrad.example und rumpel-rad.example wurden intern reserviert. Daraus wurde im Chat abgeleitet, der Name sei frei. Andere Register, Lautvarianten und Unternehmenskennzeichen wurden noch nicht geprüft.' ],date='25.09.2026'),
 d('12_Gebuehrenplanung.xlsx','Gebührenvergleich der geplanten Anmeldungen',sheets=[{'name':'Anmeldung','headers':['Weg','Klassen','Grundgebühr EUR','Zusatz EUR','Gesamt EUR'], 'rows':[['DPMA elektronisch',3,290,0,'=C2+D2'],['DPMA elektronisch',4,290,100,'=C3+D3'],['EUIPO elektronisch',3,850,200,'=C4+D4'],['Freigegebenes Erstbudget',None,500,0,'=C5+D5']], 'widths':[30,12,22,20,22],'formats':{'C':'#,##0.00','D':'#,##0.00','E':'#,##0.00'},'expected':{'E2':290,'E3':390,'E4':1050},'perturbations':[{'input':'C2','value':300,'output':'E2','expected':300}]}]),
 d('13_Warenplan.xlsx','Geschäftsplan nach Tätigkeiten',sheets=[{'name':'Tätigkeiten','headers':['Angebot','Start','Beschluss','Beleg','Rückfrage'], 'rows':[['Lastenfahrrad K1','Februar 2027','ja','Produktblatt','Verkaufsbegriff'],['Download-App','Prototyp','ja','Chat 24.09.','Funktionsbeschreibung'],['SaaS-Dienst','offen','nein','Ideenliste','Kein Entwicklungsauftrag'],['Fremde Schlösser verkaufen','Februar 2027','ja','Produktblatt','Laden oder auch online'],['Fahrradreparaturen','Februar 2027','ja','Produktblatt','Eigene und fremde Räder'],['Helme','unbestimmt','nein','Chat','Nicht beschlossen']], 'widths':[27,22,15,23,32]}]),
 mail('14_Email_Haendlerin.eml','Erst einmal zwölf Räder?','Noor van Dalen <noor@fietsbuurt.example>','Ottilie Knorr <ottilie@rumpelrad.example>',
 'Hallo Ottilie,\n\nwir würden uns den Prototyp gern im November ansehen. Zwölf Räder für Rotterdam wären denkbar, aber das ist noch keine Bestellung. Eine Exklusivität haben wir nicht vereinbart. Bitte plant wegen unserer Mail keine europaweite Lieferbereitschaft ein.\n\nBeste Grüße\nNoor',date='2026-09-27T16:20:00+02:00'),
 d('15_Zahlungsanforderung_Privatregister.pdf','Angebot der Markenverzeichnis Service S.à r.l.',[
 'An die Geschäftsleitung Rumpelrad Mobilität UG (haftungsbeschränkt). Betreff: Aufnahme Ihres Zeichens RUMPELRAD in das gewerbliche Markenverzeichnis. Für die Veröffentlichung im privaten Onlineverzeichnis wird ein Betrag von 980 EUR zuzüglich Umsatzsteuer angeboten. Zahlungsziel laut Angebot: fünf Werktage.',
 'Im Kleindruck am Ende des Angebots steht: „Die Leistung umfasst keine Anmeldung bei einem Markenamt. Der Vertrag kommt erst durch Zahlung zustande.“ Auf der ersten Seite ist eine graue Grafik mit der Aufschrift „Markenverzeichnis“ abgebildet. Ein amtliches Aktenzeichen ist nicht genannt. Die Assistenz hat auf dem Ausdruck handschriftlich „DPMA?“ vermerkt.' ],date='26.09.2026'),
 mail('16_Email_Buchhaltung.eml','Darf ich die 980 Euro freigeben?','Kunibert Pohl <buchhaltung@rumpelrad.example>','Ottilie Knorr <ottilie@rumpelrad.example>',
 'Liebe Ottilie,\n\nich habe die Anforderung über 980 EUR zunächst gesperrt. Wir haben im Budget nur 500 EUR für die erste Anmeldung. Außerdem finde ich kein Aktenzeichen. Bitte sag mir nach Rücksprache mit der Kanzlei, was echte Amtsgebühr ist und was ein privates Angebot. Bisher ist nichts überwiesen.\n\nViele Grüße\nKunibert',date='2026-09-28T08:12:00+02:00'),
 d('17_Besprechungsnotiz.docx','Besprechung im Werkhof',[
 'Am 29.09.2026 besprechen Ottilie, Idris und Eberhard die Markenstrategie. Ottilie bleibt bei der deutschen Wortmarke RUMPELRAD. Eberhard möchte die Reparaturleistungen berücksichtigt wissen. Idris weist darauf hin, dass die App noch nicht öffentlich verfügbar ist, aber unter demselben Zeichen angeboten werden soll.',
 'Eine Anmeldung für Helme oder Kindersitze wird nicht beschlossen. Für einen Onlinehandel mit fremden Waren gibt es noch keine Entscheidung. Ottilie bittet die Kanzlei, den Schutzumfang in zwei sinnvollen Varianten mit Kosten vorzulegen. Sie möchte das alte Onlineformular nicht ungeprüft weiterverwenden.',
 'Die Beteiligten beauftragen keine Zahlung und keine Kontaktaufnahme mit dem ähnlich bezeichneten Unternehmen. Ein möglicher Konflikt soll zunächst anhand vollständiger Registerinformationen bewertet werden.' ],date='29.09.2026'),
 d('18_Vollmacht_Entwurf.docx','Vollmacht für den Markenvorgang – Entwurf',[
 'Die Rumpelrad Mobilität UG (haftungsbeschränkt), vertreten durch die Geschäftsführerin Ottilie Knorr, beabsichtigt, Rechtsanwältin Salome Hummel mit der Vorbereitung und Begleitung einer deutschen Markenanmeldung RUMPELRAD zu beauftragen. Die Vertretungsregel der Gesellschaft ist vor Unterzeichnung anhand des amtlichen Registerauszugs zu prüfen.',
 'Der vorliegende Entwurf umfasst keine Ermächtigung zur Aufgabe bestehender Schutzrechte, zur Unterzeichnung einer Koexistenzvereinbarung oder zur Entgegennahme eines kostenpflichtigen privaten Registerangebots. Die konkrete Anmeldung soll erst nach Bestätigung von Inhaber, Zeichenform und Endverzeichnis eingereicht werden.',
 'Bearbeitungsstand: nicht unterzeichnet. Ort und Datum werden bei Freigabe ergänzt. Die Beauftragung ersetzt nicht die gesonderte Prüfung erforderlicher Vertretungsbefugnis beim jeweiligen Amt.' ],date='29.09.2026'),
 d('19_Dateiliste.csv','Übergebene Anlagen',headers=['Datei','Stand','Absender','Status'],rows=[['RR_01_grau.png','19.08.2026','Rasterfink','Vorstufe'],['RR_02_blau.png','12.09.2026','Rasterfink','aktuelle Logo-Fassung'],['Anmeldeentwurf','19.08.2026','Ottilie','lokal'],['Firmenblatt','22.09.2026','Büro','Abschrift'],['Vollmacht','29.09.2026','Kanzlei','Entwurf']]),
 mail('20_Email_Nachtrag.eml','Noch zwei Dinge zum Formular','Ottilie Knorr <ottilie@rumpelrad.example>','Salome Hummel <kanzlei@hummel.example>',
 'Liebe Frau Hummel,\n\nich habe gerade nachgesehen: Im August kam keine Eingangsbestätigung, und es wurde auch keine Gebühr gezahlt. Den amtlichen Handelsregisterauszug fordere ich aus der Gründungsakte an. Bitte schicken Sie mir die finale Markenfassung mit den zwei Kostenvarianten. Danach entscheide ich.\n\nHerzliche Grüße\nOttilie',date='2026-10-01T08:42:00+02:00'),
]))
CASES.append(case('markenamt-kichererbse','Kichererbse – Streit um das neue Supermarktregal','Kichererbse Küche GmbH',
 'Eine Berliner Lebensmittelherstellerin bereitet die Verteidigung ihrer Unionsmarkenanmeldung vor. Ein älteres Zeichen, eine unklare Übertragung, britische Benutzungsunterlagen und eine jüngere Lizenz erzeugen mehrere voneinander unabhängige Beweisfragen.',
 'Bereiten Sie die Verteidigung im EUIPO-Widerspruch vor. Klären Sie zuerst Verfahrensstand, Fristen und Berechtigung. Ordnen Sie Benutzungsunterlagen nach Marke, Ware, Ort und Zeitraum und formulieren Sie die nötigen Anträge und Rückfragen. Die Akte enthält keine echten Registerdaten.',[
 d('01_Auftrag.docx','Mandatsauftrag Kichererbse',[
 'Die Kichererbse Küche GmbH vertreibt gekühlte Aufstriche auf Kichererbsenbasis und pflanzliche Fertigmahlzeiten. Geschäftsführerin ist Fritzi Yılmaz. Der Mitgründer Wolfram Birnbaum betreut den Vertrieb. Die Gesellschaft hat im Frühjahr 2026 eine Unionswortmarke KICHERERBSE angemeldet; eine Arbeitsabschrift nennt den 15.05.2026 als Anmeldetag und den 12.06.2026 als Veröffentlichungstag.',
 'Die Nährwerk Handels GmbH hat am 08.09.2026 Widerspruch eingelegt. Die weitergeleitete Nachricht nennt eine ältere deutsche Wortmarke KIKERBSE und zusätzlich eine britische unregistrierte Bezeichnung KIKERBSE KITCHEN. Die vollständige EUIPO-Verfahrensmitteilung befindet sich noch im Benutzerkonto des bisherigen Vertreters.',
 'Fritzi möchte den Konflikt nicht eskalieren, benötigt aber vor den Gesprächen mit einer Supermarktkette eine belastbare Verteidigung. Sie hat noch keiner Warenbeschränkung und keiner Zahlung an die Gegenseite zugestimmt. Die Kanzlei soll die Verteidigung vorbereiten und fehlende Unterlagen gezielt anfordern.' ],date='24.09.2026',reference='26-109-KE'),
 d('02_Anmeldeabschrift.pdf','Interne Abschrift der Unionsmarkenanmeldung',[
 'Zeichen: KICHERERBSE, Wortmarke. Inhaberin: Kichererbse Küche GmbH, Berlin. Anmeldetag laut Abschrift 15.05.2026; Veröffentlichung laut Ablage 12.06.2026. Verfahrenssprache Deutsch, zweite Sprache Englisch. Die Akte verwendet die interne Referenz KE-EU-2026-01 anstelle der nicht übernommenen Registernummer.',
 'Klasse 29: Aufstriche auf Gemüsebasis; zubereitete Mahlzeiten überwiegend aus Gemüse. Klasse 30: Saucen; Würzmittel. Klasse 35: Einzelhandelsdienstleistungen in Bezug auf Lebensmittel. Die veröffentlichte Originalfassung ist mit dieser Abschrift abzugleichen. Eine Eintragung ist in der internen Statuszeile noch nicht vermerkt.' ],date='15.06.2026'),
 mail('03_Email_Widerspruch.eml','Fwd: KIKERBSE gegen KICHERERBSE','Fritzi Yılmaz <fritzi@kichererbse.example>','Salome Hummel <kanzlei@hummel.example>',
 'Sehr geehrte Frau Hummel,\n\nunser bisheriger Vertreter hat mir gestern nur die erste Seite weitergeleitet. Dort steht Widerspruch vom 8. September. Die übrige Nachricht liegt wohl im Portal. Ich kann derzeit nur das Firmenkonto sehen, nicht sein Vertreterkonto. Bitte prüfen Sie zuerst, was wir bis wann tun müssen.\n\nIch möchte nicht allein wegen des ähnlichen Namens die gesamte Anmeldung aufgeben.\n\nMit freundlichen Grüßen\nFritzi Yılmaz',date='2026-09-24T09:05:00+02:00'),
 d('04_Widerspruch_Arbeitsabschrift.docx','Arbeitsabschrift des gegnerischen Vortrags',[
 'Die Nährwerk Handels GmbH macht in dem übermittelten Auszug eine ältere deutsche Wortmarke KIKERBSE geltend. Als Inhaberin nennt der beigefügte alte Auszug noch die Nährwerk Lebensmittel KG. Der Vortrag verweist auf eine Übertragung vom 01.07.2025. Der unterschriebene Vertrag ist im übersandten Paket nicht enthalten.',
 'Für die ältere deutsche Marke nennt die Arbeitsabschrift eine Anmeldung vom 10.02.2016 und einen Abschluss des Eintragungsverfahrens am 20.06.2016. Als Waren sind unter anderem Gemüsekonserven und Aufstriche aufgeführt. Eine vollständige aktuelle Registerauskunft fehlt. Zusätzlich beruft sich die Gegenseite auf seit 2014 bestehende britische Benutzungsrechte an KIKERBSE KITCHEN.',
 'Die Gegenseite verlangt die Zurückweisung der Anmeldung für sämtliche Waren und Dienstleistungen. Zur Benutzung legt sie einen Lizenzvertrag, vier Rechnungsabschriften und zwei Produktfotos vor. Eine formelle Anforderung von Benutzungsnachweisen durch das Amt wird in den vorliegenden Seiten nicht erwähnt.' ],date='08.09.2026'),
 d('05_Altregister_Abschrift.pdf','Älteres Recht – Notiz aus der Vertragsablage',[
 'KIKERBSE; deutsche Wortmarke; ursprüngliche Inhaberin Nährwerk Lebensmittel KG. Die interne Ablage nennt als ursprüngliche Waren „Gemüsekonserven; Brotaufstriche auf Gemüsebasis“. Die Notiz wurde zuletzt am 02.07.2025 bearbeitet. Der Verlängerungsstand 2026 und die Eintragung der Erwerberin sind nicht dokumentiert.',
 'Auf der Rückseite steht handschriftlich: „Übertragung an Handels-GmbH mit Asset Deal, Anlage 7“. Anlage 7 wurde beim Versand an die neue Kanzlei ausgelassen. Die Notiz ist keine beglaubigte Registerabschrift; die Registernummer wurde nicht in die Notiz übernommen.' ],date='02.07.2025'),
 d('06_Uebertragungsentwurf.docx','Entwurf Markenübertragung',[
 '1. Beteiligte\nDie Nährwerk Lebensmittel KG beabsichtigt, die im Anlagenverzeichnis aufgeführten Marken auf die Nährwerk Handels GmbH zu übertragen. Im vorliegenden Entwurf sind die Namen der vertretungsberechtigten Personen nicht eingesetzt. Das Anlagenverzeichnis ist nicht beigefügt.',
 '2. Übertragungsgegenstand\nÜbertragen werden sollen die Marken des Geschäftsbetriebs Gemüseaufstriche einschließlich zugehöriger Domains. Eine genaue Registernummer und ein Warenverzeichnis enthält der Text nicht. Für mögliche Teilrechte soll eine gesonderte Anlage maßgeblich sein.',
 '3. Vollzug\nDer Entwurf sieht einen wirtschaftlichen Übergang zum 01.07.2025 vor. Die Parteien sollen die erforderlichen Registererklärungen abgeben. Das vorliegende Exemplar enthält keine Unterschriften. Der Dateiname im Datenraum endet auf „Entwurf_5“.' ],date='24.06.2025'),
 mail('07_Email_Gegenseite.eml','Unterlagen zur Benutzung','Adelheid Kron <recht@naehrwerk.example>','Salome Hummel <kanzlei@hummel.example>',
 'Sehr geehrte Frau Hummel,\n\nanbei senden wir die bisher zusammengestellten Belege. Die Übertragung wurde seinerzeit im Unternehmenskauf mitgeregelt; das unterschriebene Anlagenpaket liegt bei unserem früheren Berater. Die Lizenz ist nach unserer Auffassung ausreichend, weil der Lizenznehmer zur Vermarktung verpflichtet war.\n\nDie britischen Verkäufe bestanden schon lange vor Ihrer Anmeldung. Bitte nehmen Sie die Anmeldung vollständig zurück. Ein Vergleichsvorschlag folgt.\n\nMit freundlichen Grüßen\nAdelheid Kron',date='2026-09-26T15:15:00+02:00'),
 d('08_Lizenzvertrag.docx','Lizenzvertrag mit Löffelbund GmbH',[
 'Die Nährwerk Handels GmbH gestattet der Löffelbund GmbH ab 01.08.2025 die ausschließliche Nutzung der Bezeichnung KIKERBSE für gekühlte Gemüseaufstriche in Deutschland. Vertragsgegenstand ist nach dem Text die deutsche Marke aus Anlage 1. Diese Anlage ist in der Kopie enthalten und nennt die Wortmarke KIKERBSE, jedoch keine bildliche Gestaltung.',
 'Der Lizenznehmer soll spätestens im ersten Quartal 2026 mit der Vermarktung beginnen. Eine jährliche Mindestlizenz von 6.000 EUR ist unabhängig vom Umsatz vereinbart. Die Lizenzgeberin erhält quartalsweise Absatzberichte. Ein Bericht für das erste Quartal 2026 weist lediglich Produktentwicklung und interne Verkostungen aus.',
 'Der Vertrag wurde von Gerlinde Pfau für die Lizenzgeberin und Joonas Weber für die Lizenznehmerin unterzeichnet. Die Vertretungsnachweise sind in der übergebenen Kopie nicht enthalten. Die vertragliche Absatzpflicht ersetzt keinen Nachweis tatsächlicher Verkäufe.' ],date='01.08.2025'),
 d('09_Rechnung_2022.pdf','Rechnungsabschrift NW-2022-418',[
 'Nährwerk Lebensmittel KG an Marktkrone eG, Dresden. Lieferdatum 14.09.2022. 480 Gläser Gemüseaufstrich, Artikel 440-18, zu 2,10 EUR netto. Nettosumme 1.008,00 EUR, Umsatzsteuer 7 Prozent 70,56 EUR, Bruttosumme 1.078,56 EUR. Der Warenname KIKERBSE erscheint nicht auf der Rechnung.',
 'Eine handschriftliche Notiz lautet „Artikel 440-18 = KIKERBSE Paprika?“. Die zugehörige Artikelstammliste und das damalige Verpackungsbild wurden nicht beigefügt. Ein Lieferschein wird unter Nummer LS-418 erwähnt.' ],date='16.09.2022'),
 d('10_Rechnung_2024.pdf','Rechnungsabschrift NW-2024-071',[
 'Nährwerk Lebensmittel KG an Küchentisch Handel OHG, Hamburg. Lieferdatum 20.02.2024. Position 1: 96 Gläser KIKERBSE Gemüseaufstrich, 2,40 EUR netto je Glas. Netto 230,40 EUR; Umsatzsteuer 7 Prozent 16,13 EUR; Brutto 246,53 EUR. Position 2 ist mit „kostenlose Muster, 12 Stück“ bezeichnet und ohne Berechnung.',
 'Der Überweisungseingang wird auf einer internen Liste vom 12.03.2024 bestätigt. Die Empfängeradresse in Hamburg ist vollständig in der Originalrechnung enthalten; in der Zahlungsablage wird die Straße als Marktgasse 31 geführt.' ],date='22.02.2024'),
 d('11_Rechnung_UK_2020.pdf','Sales invoice NK-2020-88',[
 'Nährwerk Kitchen Ltd an Pantry Lane Ltd, Bristol. Supply date 11 November 2020. Goods: 360 jars KIKERBSE KITCHEN spread. Unit price GBP 1.90; net amount GBP 684.00. The accompanying sales note records delivery exclusively within the United Kingdom.',
 'This is the copy retained by the German group office. No delivery into an EU Member State is documented in this invoice. The claimant relies on the document as evidence of earlier UK trading activity.' ],date='12.11.2020'),
 d('12_Rechnung_2026.pdf','Rechnung LB-2026-033',[
 'Löffelbund GmbH an Feinkost Hering & Sohn, Berlin. Lieferdatum 16.09.2026. 240 Gläser KIKERBSE Aufstrich, 2,80 EUR netto je Glas. Netto 672,00 EUR; Umsatzsteuer 7 Prozent 47,04 EUR; Brutto 719,04 EUR. Der Zahlungsstatus ist offen, Zahlungsziel 14 Tage.',
 'Im Versandordner liegen ein Lieferschein mit Empfangsnotiz und ein Verpackungsfoto vom 15.09.2026. Frühere Lieferungen des Lizenznehmers sind in der übergebenen Sammlung nicht enthalten.' ],date='17.09.2026'),
 d('13_Benutzungsablage.xlsx','Belegverzeichnis der Gegenseite',sheets=[{'name':'Belege','headers':['Beleg','Datum','Gebiet','Warenbezeichnung','Netto','Zuordnung'], 'rows':[['NW-2022-418','16.09.2022','Deutschland','Artikel 440-18',1008,'Stammliste fehlt'],['NW-2024-071','22.02.2024','Deutschland','KIKERBSE Aufstrich',230.40,'96 Gläser'],['NK-2020-88','12.11.2020','UK','KIKERBSE KITCHEN',684,'GBP; separat'],['LB-2026-033','17.09.2026','Deutschland','KIKERBSE Aufstrich',672,'Nach Anmeldung'],['Euro-Summe ohne UK',None,None,None,'=E2+E3+E5','Keine rechtliche Gesamtbewertung']], 'widths':[24,16,20,28,18,32],'formats':{'E':'#,##0.00'},'expected':{'E6':1910.40},'perturbations':[{'input':'E2','value':1108,'output':'E6','expected':2010.4}]}]),
 d('14_Fristenablage.xlsx','Verfahrensdaten laut Assistenz',sheets=[{'name':'Daten','headers':['Ereignis','Datum','Beleg','Status'], 'rows':[['Anmeldung','15.05.2026','Arbeitsabschrift','Original abgleichen'],['Veröffentlichung','12.06.2026','Arbeitsabschrift','Original abgleichen'],['Widerspruch','08.09.2026','Weitergeleitete Seite','Volltext fehlt'],['Portalmitteilung','23.09.2026','Benachrichtigungs-Mail','Zugang beim Vertreter'],['Geplanter Gesprächstermin','07.10.2026','Kalender','Keine Amtsfrist']], 'widths':[28,18,34,38]}]),
 d('15_Chat_Produktfoto.txt','Chat zur Herkunft der Produktfotos','27.09.2026 11:02 Wolfram: Das linke Foto zeigt die alte Verpackung von 2018.\n27.09.2026 11:04 Fritzi: Woher weißt du das? Die Datei heißt nur kikerbse_final.jpg.\n27.09.2026 11:09 Wolfram: Ich kenne das aus dem Supermarkt. Sicher bin ich nicht.\n27.09.2026 11:18 Fritzi: Dann bitte nicht als Datum in unsere Antwort schreiben.\n27.09.2026 11:26 Wolfram: Das rechte Foto hat wenigstens die neue Löffelbund-Adresse und die Aufnahmeangabe 15.09.2026.'),
 d('16_Bildablage.png','Interne Belegablage KIKERBSE','Foto_A.jpg – Herkunft: E-Mail Nährwerk\nAufnahmedatum: nicht vorhanden\nDateiname: kikerbse_final.jpg\nFoto_B.jpg – Verpackung Löffelbund\nAufnahmevermerk: 15.09.2026\nKeine Rückseitenansicht bei Foto_A\nZuordnung zur Rechnung NW-2022-418: offen',date='28.09.2026'),
 d('17_Vergleichsvorschlag.docx','Vergleichsvorschlag der Nährwerk Handels GmbH',[
 '1. Markenanmeldung\nDie Kichererbse Küche GmbH soll ihre Unionsmarkenanmeldung vollständig zurücknehmen. Die Nährwerk Handels GmbH würde im Gegenzug den Widerspruch für erledigt erklären.',
 '2. Geschäftliche Verwendung\nDie Kichererbse Küche GmbH soll sich verpflichten, KICHERERBSE künftig nicht für Lebensmittel, Gastronomie, Kochkurse, Apps, Internetdomains und Werbemittel zu benutzen. Eine Umstellungsfrist von sechs Wochen wird vorgeschlagen. Die bestehenden Verpackungen sollen nicht mehr ausgeliefert werden.',
 '3. Kosten und Stand\nJede Seite soll eigene Kosten tragen. Der Vorschlag ist bis 07.10.2026 offen und wurde bisher von keiner Seite unterzeichnet. Er enthält keine Erklärung darüber, ob eine Einschränkung auf bestimmte Waren als Alternative akzeptiert würde.' ],date='28.09.2026'),
 mail('18_Email_Vertrieb.eml','Was wir auf keinen Fall verlieren dürfen','Wolfram Birnbaum <wolfram@kichererbse.example>','Fritzi Yılmaz <fritzi@kichererbse.example>',
 'Fritzi,\n\nwir brauchen den Namen für die gekühlten Aufstriche. Saucen verkaufen wir noch gar nicht, und fremde Lebensmittel handeln wir ebenfalls nicht. Ein völliger Namenswechsel würde mindestens 18.000 EUR Verpackungskosten verursachen. Ich weiß aber nicht, ob die Gegenseite auch eine begrenzte Lösung akzeptieren würde.\n\nBitte kein Gespräch führen, in dem wir aus Versehen die Rücknahme schon zusagen.\n\nWolfram',date='2026-09-29T13:35:00+02:00'),
 d('19_Besprechungsvermerk.docx','Vorbereitung der Übergabe vom bisherigen Vertreter',[
 'Fritzi hat den bisherigen Vertreter am 29.09.2026 um die vollständige Portalakte, sämtliche Zustellinformationen und die aktuelle Vollmacht gebeten. Bis zum Stand dieses Vermerks liegt nur die automatische Eingangsbestätigung der Kanzlei vor. Eine Vertretungsänderung beim EUIPO ist noch nicht dokumentiert.',
 'Die neue Kanzlei soll zunächst mit den vorhandenen Unterlagen arbeiten. Nach Eingang der Portalakte sind sämtliche Fristangaben abzugleichen. Ein behauptetes Cooling-off-Ende aus dem Telefonat wurde nicht in den Kalender als gesicherte Amtsfrist übernommen.',
 'Für eine Entscheidung über eine Warenbeschränkung will Fritzi die genaue Reichweite und die wirtschaftlichen Folgen schriftlich sehen. Die angefragten Originalbelege zur Benutzung und zur Erwerbskette sind gesondert zu behandeln.' ],date='30.09.2026'),
 mail('20_Email_Stand.eml','Portalakte folgt, bitte zunächst vorbereiten','Fritzi Yılmaz <fritzi@kichererbse.example>','Salome Hummel <kanzlei@hummel.example>',
 'Sehr geehrte Frau Hummel,\n\nich bekomme die vollständige Akte heute Nachmittag. Bis dahin bitte die rechtlichen und tatsächlichen Rückfragen vorbereiten. Ich will insbesondere verstehen, was aus Großbritannien und was aus Deutschland überhaupt belegt ist. Der neuere Lizenzvertrag klingt für mich noch nicht nach Verkäufen.\n\nEine Rücknahme oder ein Vergleich ist weiterhin nicht freigegeben.\n\nFreundliche Grüße\nFritzi',date='2026-10-01T09:20:00+02:00'),
]))
CASES.append(case('markenamt-farbwerk','Farbwerk – Wem gehört das Aubergine im Baumarkt?','Farbwerk Heimbedarf GmbH',
 'Eine inhabergeführte Baumarktkette verteidigt eine abstrakte Farbmarke. Zwei Befragungen verwenden unterschiedliche Grundgesamtheiten und Stimuli. Parallel sind Umfirmierung, Registeranschrift, Verlängerung und ein privates Gebührenangebot zu bearbeiten.',
 'Entwickeln Sie die Verteidigung gegen den Nichtigkeitsantrag, prüfen Sie den Aussagewert der Befragungen und bereiten Sie die erforderlichen Registeränderungen vor. Berechnen Sie keine sichere Frist ohne Zustellnachweis. Treffen Sie keine eigenmächtige Entscheidung über Aufgabe oder Einschränkung der Marke.',[
 d('01_Mandatsaufnahme.docx','Aufnahme Farbwerk',[
 'Die Farbwerk Heimbedarf GmbH betreibt fünf Fachmärkte für Heimwerkerbedarf in Niedersachsen. Die geschäftsführende Gesellschafterin Edeltraud Nguyen übernahm die Leitung 2024 von ihrem Vater Wilibald Schlotterbeck. Seit 2021 wird im Außenauftritt die Farbe Aubergine eingesetzt. Die Gesellschaft hieß bei Anmeldung noch Schlotterbeck Heimbedarf GmbH.',
 'Die Akte betrifft eine deutsche abstrakte Farbmarke für Einzelhandelsdienstleistungen in Bezug auf Heimwerker- und Gartenbedarfswaren. In der internen Registerabschrift steht als Farbdefinition RAL 4007. Ein Wettbewerber hat Nichtigkeit wegen fehlender Unterscheidungskraft und fehlender Verkehrsdurchsetzung beantragt. Die Zulässigkeit und der Verfahrensstand sind anhand der vollständigen Amtsakte zu klären.',
 'Die Geschäftsführerin hält eine Kundenbefragung mit 71 Prozent Zuordnung für entscheidend. Der Gegner hat eine breitere Erhebung vorgelegt. Im Marketing werden Farbe und weißer Schriftzug regelmäßig zusammen verwendet. Die Kanzlei soll die Befragungen, die konkrete Schutzform und die noch nicht erledigte Umfirmierung im Markenregister prüfen.' ],date='25.09.2026',reference='26-112-FW'),
 d('02_Registerblatt_Abschrift.pdf','Arbeitsabschrift des Markenbestands',[
 'Interne Referenz FW-DE-FARBE-2018. Markenform: abstrakte Farbmarke. Farbdefinition: RAL 4007. Anmeldetag laut Altakte: 14.11.2018. Eintragung laut Arbeitsblatt: 20.08.2021. Inhaberin laut damaliger Abschrift: Schlotterbeck Heimbedarf GmbH. Anschrift: Gewerbering 9, Hildesheim.',
 'Dienstleistungen: Einzelhandelsdienstleistungen in Bezug auf Heimwerker- und Gartenbedarfswaren. Der genaue Registerwortlaut und die Darstellung sind vor Verwendung anhand des Originals abzugleichen. Die Arbeitsabschrift enthält die Markenregisternummer nicht und ist nicht beglaubigt.',
 'Eine Änderung auf Farbwerk Heimbedarf GmbH wurde in der internen Liste am 18.03.2024 eingetragen. Ob das Markenregister geändert wurde, ist nicht vermerkt. Die bisher geführte Schutzfrist endet laut alter Liste am 30.11.2028.' ],date='25.09.2026'),
 mail('03_Email_Geschaeftsfuehrerin.eml','Unsere Farbe kann doch jeder zuordnen','Edeltraud Nguyen <edeltraud@farbwerk.example>','Salome Hummel <kanzlei@hummel.example>',
 'Liebe Frau Hummel,\n\nin unserer Befragung nennen 71 Prozent Farbwerk. Der Gegner hat Menschen gefragt, die seit Jahren keinen Baumarkt besucht haben. Das kann doch nicht zählen. Bitte sehen Sie sich trotzdem beide Unterlagen an. Ich möchte wissen, ob wir noch eine neue Erhebung brauchen.\n\nDie Farbe ohne Schriftzug verwenden wir vor allem an den Einkaufswagen. Auf den Fassaden steht immer FAR BWERK – mit dem kleinen Abstand im Logo.\n\nViele Grüße\nEdeltraud',date='2026-09-25T11:10:00+02:00'),
 d('04_Amtsmitteilung_Arbeitsabschrift.docx','Abschrift der Mitteilung zum Nichtigkeitsantrag',[
 'Die Markenabteilung übersendet nach der vorliegenden Abschrift den Antrag eines Wettbewerbers auf Erklärung der Nichtigkeit wegen absoluter Schutzhindernisse. Beanstandet wird insbesondere, dass die isolierte Farbe für die beanspruchten Einzelhandelsdienstleistungen nicht als Herkunftshinweis verstanden werde. Die Antragsschrift stellt ferner die Tragfähigkeit der früheren Verkehrsdurchsetzungsunterlagen in Frage.',
 'Der sichtbare Text nennt eine Stellungnahmefrist von zwei Monaten ab Zustellung. Die Abschrift enthält kein Zustellungsdatum. In der Mail der Assistenz wird der 18.09.2026 genannt, während ein Posteingangsstempel auf der ersten Seite den 21.09.2026 zeigt. Der Umschlag und der elektronische Zustellnachweis sind angefordert.',
 'Die Abschrift wurde für die Geschäftsleitung erstellt. Sie ersetzt nicht die vollständige amtliche Mitteilung mit Rechtsbehelfs- und Verfahrenshinweisen.' ],date='16.09.2026'),
 d('05_Antrag_Gegner.docx','Auszug aus dem Vortrag der Gartenfokus Handels GmbH',[
 'Die Gartenfokus Handels GmbH beantragt die Erklärung der Nichtigkeit der abstrakten Farbmarke. Sie meint, die Farbe werde als dekorative Hausfarbe verstanden. Die Eintragung beruhe auf einer unzureichenden Auswahl befragter Personen; nur Besucher der Märkte seien in die damalige Befragung aufgenommen worden.',
 'Die Antragstellerin legt eine neue Erhebung vor, die Erwachsene einschließlich Nichtkunden erfasst. Sie verweist außerdem auf einen von Farbwerk verwendeten weißen Schriftzug. Die bekannte Wort-/Bildgestaltung lasse keinen sicheren Schluss auf eine herkunftshinweisende Wirkung der isolierten Farbe zu.',
 'Die Antragstellerin bestreitet nicht, dass Farbwerk wirtschaftlich erfolgreich ist und die Farbe häufig verwendet. Sie bestreitet jedoch die Gleichsetzung von Unternehmensbekanntheit, Erinnerungswert des Logos und Verkehrsdurchsetzung der abstrakten Farbmarke.' ],date='11.09.2026'),
 d('06_Befragung_2021.pdf','Erhebung Kundenforum 2021 – Methodenblatt',[
 'Auftraggeberin: Schlotterbeck Heimbedarf GmbH. Erhebungszeitraum 12.–19.04.2021. Befragt wurden 600 volljährige Personen, die in den vorausgegangenen zwölf Monaten mindestens einen Markt der Auftraggeberin besucht hatten. Die Rekrutierung erfolgte über den Kundennewsletter.',
 'Den Befragten wurde zunächst eine Farbfläche in Aubergine gezeigt. Die anschließende Frage lautete: „An welchen Baumarkt denken Sie bei dieser Farbe?“ Vor der Befragung enthielt die Einladung das Logo Schlotterbeck Heimbedarf auf auberginefarbenem Hintergrund. 426 Befragte nannten die Auftraggeberin oder die spätere interne Kurzbezeichnung Farbwerk.',
 'Die Auswertung gibt 71 Prozent bezogen auf alle 600 Teilnehmer an. Eine Hochrechnung auf die Gesamtbevölkerung wurde nicht erstellt. Die Rohdaten enthalten keine Vergleichsgruppe ohne Newsletterkontakt. Die Ergebnispräsentation wurde von der Marketingabteilung erstellt.' ],date='03.05.2021'),
 d('07_Befragung_2026.pdf','Erhebung Marktbild 2026 – Methodenblatt',[
 'Auftraggeberin: Gartenfokus Handels GmbH. Erhebungszeitraum 04.–18.07.2026. Befragt wurden 1.000 volljährige Personen aus Deutschland. Die Stichprobe umfasste aktuelle Baumarktkunden, gelegentliche Kunden und Personen ohne Kauf in den letzten drei Jahren. Das Institut berichtet eine Quotierung nach Alter, Geschlecht und Region.',
 'Gezeigt wurde nach dem Methodenblatt eine isolierte Farbfläche mit der Bezeichnung RAL 4007, ohne Unternehmenslogo. Die erste Frage war offen. 270 Personen ordneten die Farbe Farbwerk beziehungsweise Schlotterbeck zu. 190 nannten andere Unternehmen, 540 machten keine Unternehmenszuordnung. Eine zweite Frage mit vorgegebenen Namen wird im gesonderten Anhang ausgewertet.',
 'Das Institut weist darauf hin, dass sich Erhebungsjahr, Grundgesamtheit und Kontakt zum Auftraggeber von der Befragung 2021 unterscheiden. Der vollständige Fragebogen ist in der Akte enthalten; personenbezogene Rohdaten wurden nicht übergeben.' ],date='04.08.2026'),
 d('08_Fragebogen_2026.docx','Fragebogen Marktbild – übergebene Fassung',[
 '1. Einleitung\nWir zeigen Ihnen im Folgenden eine Farbe. Es gibt keine richtigen oder falschen Antworten. Bitte nennen Sie spontan, was Ihnen dazu einfällt. Die Einladung enthält keinen Namen eines Baumarktunternehmens.',
 '2. Offene Fragen\nWoran denken Sie beim Anblick dieser Farbe? Verbinden Sie die Farbe mit einem bestimmten Unternehmen oder mehreren Unternehmen? Falls ja, nennen Sie bitte das Unternehmen. Der Interviewer darf keinen Namen anbieten und fragt bei unklarer Antwort nur nach der genauen Bezeichnung.',
 '3. Weitere Erfassung\nErst nach Abschluss der offenen Fragen werden eine Liste von Unternehmensnamen und Fragen zum Einkaufsverhalten gezeigt. Die offene Zuordnung wird gesondert ausgewertet. Die Akte enthält keine Tonaufnahmen; die Codieranweisung sieht eine gesonderte Behandlung unklarer Antworten vor.' ],date='30.06.2026'),
 d('09_Befragungszahlen.xlsx','Arbeitsrechnung zu den Erhebungen',sheets=[{'name':'Zuordnung','headers':['Erhebung','Befragte','Farbwerk zugeordnet','Quote','Grundgesamtheit'], 'rows':[['Kundenforum 2021',600,426,'=C2/B2','Newsletter; Marktbesuch'],['Marktbild 2026',1000,270,'=C3/B3','Erwachsene Deutschland'],['Differenz Prozentpunkte',None,None,'=D2-D3','Methoden nicht gleich']], 'widths':[28,15,24,19,38],'formats':{'D':'0.0%'},'expected':{'D2':.71,'D3':.27,'D4':.44},'perturbations':[{'input':'C2','value':300,'output':'D4','expected':.23}]}]),
 d('10_Marketingvermerk.docx','Verwendung der Hausfarbe',[
 'Die Fassaden sämtlicher fünf Märkte zeigen die Farbe Aubergine zusammen mit einem weißen Schriftzug. Die Einkaufstaschen und Werbeprospekte enthalten zusätzlich ein Blattmotiv. Auf Einkaufswagen und einigen Regalböden wird die Farbe allein verwendet. Es liegen aber nur wenige datierte Fotos dieser isolierten Verwendung vor.',
 'Seit März 2024 wird das Wort FAR BWERK in der Gestaltung mit einem schmalen Abstand zwischen R und B eingesetzt. Im Fließtext schreiben wir Farbwerk. Die Marketingabteilung hat bisher sämtliche Auftritte in einer gemeinsamen Bildablage geführt, ohne nach abstrakter Farbe, Wortmarke und Wort-/Bildzeichen zu unterscheiden.',
 'Eine im Frühjahr 2026 geplante Onlinekampagne „Seit 1897 für Ihr Zuhause“ wurde nicht veröffentlicht. Das Unternehmen besteht nach den vorliegenden Unterlagen seit 1989. Die Zahl 1897 stammt aus einer alten Werkzeugkiste des Großvaters und sollte nostalgisch wirken.' ],date='23.09.2026'),
 d('11_Chat_Traditionszahl.txt','Marketing-Chat zum Motiv Seit 1897','17.03.2026 13:08 Malte: Die alte Kiste von Opa trägt 1897. Das sieht wertig aus.\n17.03.2026 13:13 Edeltraud: Unsere Firma wurde 1989 gegründet. Bitte nicht einfach 1897 als Gründungsjahr nehmen.\n17.03.2026 13:16 Malte: Dann nur im Hintergrund?\n17.03.2026 13:20 Edeltraud: Erst rechtlich klären. Keine Druckfreigabe.\n17.03.2026 13:33 Wilibald: Der Kasten ist vom Flohmarkt. Mit einer alten Familientradition hat der nichts zu tun.'),
 d('12_Registeraenderung.docx','Firmenänderung und Geschäftsanschrift',[
 'Die Gesellschaft führte bis 15.03.2024 die Firma Schlotterbeck Heimbedarf GmbH. Durch Satzungsänderung wurde sie in Farbwerk Heimbedarf GmbH umbenannt. Es handelt sich nach dem beigefügten internen Firmenblatt um denselben Rechtsträger. Ein Unternehmenskauf oder eine Übertragung der Marke war nicht Bestandteil des Vorgangs.',
 'Die Geschäftsanschrift lautet seit 01.08.2025 Werkallee 26, 31137 Hildesheim. Das Markenverwaltungsblatt nennt noch Gewerbering 9. Die Post wird derzeit über einen Nachsendeauftrag weitergeleitet, dessen Laufzeit Ende 2026 ausläuft.',
 'Die Assistenz findet einen vorbereiteten Antrag auf Änderung der Anschrift, aber keinen Sende- oder Eintragungsnachweis. Der Antrag soll vor einer erneuten Übermittlung mit dem aktuellen Registerstand abgeglichen werden.' ],date='24.09.2026'),
 d('13_Bestandsliste.xlsx','Interne Markenverwaltung',sheets=[{'name':'Bestand','headers':['Recht','Inhaber laut Liste','Anmeldung','Schutzende laut Altakte','Offener Vorgang'], 'rows':[['Abstrakte Farbe RAL 4007','Schlotterbeck Heimbedarf GmbH','14.11.2018','30.11.2028','Umfirmierung/Adresse'],['Wortzeichen FARBWERK','Farbwerk Heimbedarf GmbH','18.03.2024','18.03.2034','Separat prüfen'],['Logo mit Blattmotiv','Farbwerk Heimbedarf GmbH','18.03.2024','18.03.2034','Bildfassung abgleichen']], 'widths':[31,36,20,28,33]}]),
 mail('14_Email_Institut.eml','Welche Erhebung meinen Sie?','Saskia Mbaye <saskia@kundenforum.example>','Edeltraud Nguyen <edeltraud@farbwerk.example>',
 'Sehr geehrte Frau Nguyen,\n\nunsere damalige Befragung war als Kundenbefragung beauftragt. Eine repräsentative Bevölkerungsumfrage war nicht vereinbart. Wir können den Versand der Einladung und den vollständigen Fragebogen aus dem Archiv liefern. Die 71 Prozent beziehen sich auf die von uns befragten Newsletterteilnehmer mit Marktbesuch.\n\nOb diese Auswahl für Ihr Markenverfahren genügt, haben wir seinerzeit nicht rechtlich geprüft.\n\nFreundliche Grüße\nSaskia Mbaye',date='2026-09-26T09:40:00+02:00'),
 d('15_Bildablage.png','Interne Bildablage Hausfarbe','Fassade_HI_2026.jpg – Farbe und weißer Schriftzug\nWagen_ohne_Logo.jpg – isolierte Farbe, Datum unbekannt\nProspekt_Mai_2023.pdf – Farbe, Blattmotiv und Wort\nKasse_2021.jpg – Aufnahmevermerk 02.05.2021\nFarbdefinition der Druckerei: RAL 4007\nFreigabe Motiv Seit 1897: gesperrt',date='27.09.2026'),
 d('16_Angebot_Privatregister.pdf','Angebot Schutzrechtsarchiv Europa',[
 'Schutzrechtsarchiv Europa bietet der Farbwerk Heimbedarf GmbH die Aufnahme ihrer Marke in ein privates Archiv für 1.490 EUR an. Der Text verwendet den Begriff „Verlängerungsservice“ und verweist auf eine Marke aus dem Bestand der Gesellschaft. Eine konkrete amtliche Gebührennummer ist nicht angegeben.',
 'Im Abschnitt Leistungsbeschreibung steht: „Der Vertrag umfasst die Archivveröffentlichung und die Erinnerung an den vom Kunden angegebenen Ablauf. Amtliche Gebühren und rechtsgeschäftliche Erklärungen sind nicht enthalten.“ Die Buchhaltung hat den Vorgang noch nicht bezahlt.' ],date='22.09.2026'),
 mail('17_Email_Buchhaltung.eml','Zwei unterschiedliche Inhaber im Bestand','Hasso Dinkel <hasso@farbwerk.example>','Edeltraud Nguyen <edeltraud@farbwerk.example>',
 'Edeltraud,\n\nin der Bestandsliste steht noch die alte Firma. Ich hatte gedacht, die Änderung beim Handelsregister läuft automatisch überall durch. Für die Farbe habe ich den 30. November 2028 als Ende übernommen; die neuen Wort- und Bildmarken stehen taggenau auf März 2034.\n\nDas Angebot über 1.490 EUR ist zurückgestellt. Bitte erst sagen, ob es überhaupt etwas mit dem DPMA zu tun hat.\n\nHasso',date='2026-09-28T14:25:00+02:00'),
 d('18_Besprechungsnotiz.docx','Vorbereitung der Verteidigung',[
 'Edeltraud möchte die Farbmarke verteidigen, aber keine unzutreffende Aussage über eine repräsentative Umfrage machen. Das Institut soll die ursprünglichen Materialien liefern. Die Kanzlei soll erklären, ob und wofür eine neue Erhebung hilfreich wäre; die Geschäftsleitung gibt noch kein Budget frei.',
 'Die Wort- und Wort-/Bildmarken sollen von dem Nichtigkeitsverfahren getrennt behandelt werden. Es ist nicht beabsichtigt, wegen der Auseinandersetzung um die Farbe sämtliche anderen Kennzeichen aufzugeben. Die Registeränderung der Firma und Anschrift soll unabhängig davon vorbereitet werden.',
 'Der Umschlag zur Amtsmitteilung befindet sich wahrscheinlich bei Wilibald. Er hat die Post vom alten Standort abgeholt. Der zuständige Mitarbeiter soll ihn bis zum Nachmittag anrufen. Das Originaldatum ist noch nicht bestätigt.' ],date='29.09.2026'),
 d('19_Unterlagenstand.csv','Nachzureichende Originalunterlagen',headers=['Unterlage','Angefordert bei','Datum','Stand'],rows=[['Amtsmitteilung vollständig','ehemaliger Vertreter','25.09.2026','offen'],['Zustellnachweis/Umschlag','Wilibald','29.09.2026','offen'],['Originalfragebogen 2021','Kundenforum','26.09.2026','zugesagt'],['Aktueller Markenregisterauszug','Assistenz','29.09.2026','offen'],['Registerbeleg Umfirmierung','Geschäftsleitung','24.09.2026','vorhanden in Firmenakte']]),
 mail('20_Email_Nachtrag.eml','Bitte keine pauschale 71-Prozent-Argumentation','Edeltraud Nguyen <edeltraud@farbwerk.example>','Salome Hummel <kanzlei@hummel.example>',
 'Liebe Frau Hummel,\n\nich habe verstanden, dass unsere Umfrage eine andere Gruppe erfasst. Bitte bauen Sie die Antwort so, dass wir die tatsächlichen Stärken zeigen und die offenen Fragen ehrlich benennen. Die Unterlagen von 2021 kommen morgen. Über eine Einschränkung oder eine neue Befragung möchte ich erst nach Ihrer Einordnung entscheiden.\n\nHerzliche Grüße\nEdeltraud',date='2026-10-01T10:05:00+02:00'),
]))
