#!/usr/bin/env python3
"""Ergänzung 33–42 zur unveränderten Vergabeakte. Autor: Klotzkette."""
from pathlib import Path
import importlib.util
import json
import hashlib

ROOT=Path(__file__).resolve().parents[1]
CASE=ROOT/'testakten/bauwirtschaft-vergabeverfahren-feuerwehrhaus-northeim'
QA=Path('/tmp/bauwirtschaft-vertiefung-20261006/northeim')

def main():
    QA.mkdir(parents=True,exist_ok=True)
    spec=importlib.util.spec_from_file_location('northeim_original',ROOT/'scripts/build-bauwirtschaft-northeim-akte.py')
    a=importlib.util.module_from_spec(spec);spec.loader.exec_module(a)
    baseline={p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in CASE.iterdir() if p.name[:2].isdigit() and int(p.name[:2])<=32}
    (QA/'original-hashes.json').write_text(json.dumps(baseline,indent=2),encoding='utf-8')
    (QA/'positions.json').write_text(json.dumps(a.POSITIONS,ensure_ascii=False),encoding='utf-8')
    a.eml('33_herstelleranfrage.eml','Lena Winter <angebote@leinetal-luft.de>','Felix Ahrens <auslegung@auenluft-geraet.example>','2026-09-22T08:34:00+02:00','Bitte um vorhandene Unterlagen zum Gespräch am 26 August','''Sehr geehrter Herr Ahrens,

die Stadt hat die Nichtberücksichtigung aufrechterhalten. Für die Zusammenstellung unserer Unterlagen benötige ich Ihre vorhandene Gesprächsnotiz vom 26.08.2026 und den für uns geltenden Konditionenauszug. Bitte senden Sie die damaligen Aufzeichnungen ohne nachträgliche Ergänzung einer Ventilatorauswahl. Wenn Sie sich unabhängig von der Notiz noch an eine Auswahl erinnern, erläutern Sie bitte gesondert, worauf diese Erinnerung beruht.

Nach meiner Erinnerung habe ich den Betriebspunkt 6.000 m³/h bei 600 Pa, die Grenze von 1,80 und den Preisrahmen von 61.000 EUR genannt. In unserer Antwort an die Stadt haben wir erklärt, E2 kalkuliert zu haben. Eine schriftliche Projektauslegung vor Angebotsabgabe haben wir weiterhin nicht. Es hilft uns deshalb nicht, wenn die aktuelle Auslegung auf den August zurückdatiert oder die heutige Lieferbarkeit als damalige Bestellung bezeichnet wird.

Bitte unterscheiden Sie den Rabatt auf die Baureihe von einem verbindlichen Preis für die vollständige Northeimer Konfiguration. Der Geräteeinkauf von 61.000 EUR ist unser Kalkulationsansatz. Wir haben der Stadt erklärt, Abweichungen selbst zu tragen. Für eine etwaige weitere Stellungnahme müssen wir erkennen können, was Ihre Unterlagen tatsächlich bestätigen.

Die Nachfrage ändert weder unsere Angebotsdatei noch die am 09.09.2026 übermittelten Erklärungen. Bitte liefern Sie die Unterlagen zunächst nur an uns. Über eine Vorlage im Nachprüfungsverfahren entscheidet die Geschäftsführung nach Sichtung.

Mit freundlichen Grüßen
Lena Winter
Leinetal Lufttechnik GmbH''','NO26-LT033')
    a.pdf('34_gespraechsnotiz_hersteller.pdf','Auenluft Gerätebau GmbH | Technische Auslegung','Gesprächsnotiz aus dem Kundenkonto','26.08.2026; Auszug erstellt am 24.09.2026',[[
        ('1 Erfassung','Kundenkonto Leinetal Lufttechnik GmbH, Vorgang AL-ANF-260826-17. Felix Ahrens erfasste den Anruf am 26.08.2026 um 15:18 Uhr nach einem Gespräch mit Frau Winter von 15:02 bis 15:14 Uhr. Der am 24.09.2026 um 08:20 Uhr gedruckte Auszug gibt den Text des gespeicherten Gesprächsfelds wieder. Ein revisionssicherer Änderungsverlauf dieses Felds wird vom Kundenprogramm nicht ausgegeben.'),
        ('2 Gespeicherter Gesprächsinhalt','Frau Winter fragt AL 6000 K für Feuerwehrhaus Northeim an. Zu- und Abluft jeweils 6.000 m³/h, 600 Pa extern. Kompakte Aufstellung, Gehäuse maximal 3.200 x 1.600 x 1.800 mm. Bitte auf geringe elektrische Aufnahme achten. SFP laut Kundin maximal 1,80. BACnet über Regelpaket. Angebotstermin Montag. Jahreskondition ansprechen, Ziel Einkauf 61.000 netto. Keine verbindliche Bestellung. Detaillierte Auslegung nachreichen, falls Auftrag in Aussicht.'),
        ('3 Nicht belegte Auswahl','Das gesonderte Auswahlfeld Ventilatorsatz ist im Datensatz leer. Im Freitext wird weder E1 noch E2 genannt. Es gibt zu diesem Vorgang keine angehängte Berechnung vom August. Die am 08.09.2026 erstellte Auslegung NO-AL-260908-01 beruht auf der am 07.09.2026 mitgeteilten Auswahl E2. Die vorhandene Notiz belegt einen technischen Bedarf, keine dokumentierte Konfigurationsfreigabe.'),
        ('4 Begleitvermerk zum Auszug','Ich erinnere mich an die knappen Einbaumaße und die Preisfrage. Eine eigenständige Erinnerung daran, ob ich E2 ausdrücklich genannt oder Frau Winter E2 festgelegt hat, habe ich heute nicht. Die Notiz ist deshalb nicht um eine Auswahl ergänzt worden. Der Auszug wurde am 24.09.2026 um 08:32 Uhr an Frau Winter übermittelt. Felix Ahrens, technische Auslegung.')]])
    a.pdf('35_jahreskondition_geraet.pdf','Auenluft Gerätebau GmbH | Vertriebsinnendienst','Konditionsauszug für Leinetal','05.01.2026; Kopie vom 24.09.2026',[[
        ('1 Geltung und Berechnungsbasis','Kundenvereinbarung JK-LT-2026, gültig für Abrufe vom 01.01.2026 bis 31.12.2026. Für Geräte der Kompaktbaureihe AL 6000 K gilt auf den Listen-Grundpreis von 76.250,00 EUR netto ein Jahresrabatt von 20 %. Daraus ergibt sich ein Grundpreis nach Rabatt von 61.000,00 EUR netto. Die Kondition setzt einen unveränderten Kundenstatus und Zahlung binnen 30 Tagen voraus. Ein Skonto ist nicht vorgesehen.'),
        ('2 Leistungsgrenzen','Der rabattfähige Grundpreis erfasst das werkseitig zusammengesetzte Grundgerät. Projektabhängige Komponenten, die Auswahl des Ventilatorsatzes und das Regelpaket sind in einem Abrufblatt zu bestimmen. Für E1 und E2 enthält dieser Konditionsauszug weder einen getrennten Preis noch eine Erklärung gleicher Preise. Transport, Entladung, Montage, Schaltschrank und Inbetriebnahme vor Ort gehören nicht zum Grundpreis. Ein Angebot für ein bestimmtes Bauvorhaben entsteht erst durch ein projektspezifisches Vertriebsangebot.'),
        ('3 Stand für Northeim','Unter dem Projektstichwort Northeim wurde bis zum 31.08.2026 kein Abrufblatt freigegeben. Ein projektspezifisches Vertriebsangebot mit gesonderter E2-Bepreisung ist in unserem Vertriebssystem für diesen Zeitraum nicht abgelegt. Wir bestätigen die Kundenkondition und die rechnerische Rabattwirkung. Ob Leinetal mit 61.000,00 EUR auch den tatsächlich erforderlichen Lieferumfang abdecken kann, lässt sich aus diesem Auszug allein nicht feststellen.'),
        ('4 Kopiervermerk','Diese Kopie wurde am 24.09.2026 an Leinetal ausgegeben. Sie ersetzt weder eine Bestellung noch eine Lieferfreigabe. Die technische Auslegung vom 08.09.2026 bleibt eine gesonderte Unterlage. Anja Beck, Vertriebsinnendienst.')]])
    a.docx('36_erlaeuterung_vorkalkulation.docx',a.ALPHA,'Erläuterung zur internen Vorkalkulation','25.09.2026, 09:15 Uhr',[
        ('1 Anlass und Herkunft','Frau Winter hat mich am 24.09.2026 gebeten, meinen Anteil an der Kalkulation vom August festzuhalten. Dieser Vermerk wird heute aus meiner Erinnerung sowie aus dem eingereichten Angebot und der Antwort vom 09.09.2026 erstellt. Er ist keine im August entstandene Kalkulationsdatei. Meine damalige Papiernotiz ist nicht mehr vorhanden. Eine von Frau Winter und mir gemeinsam abgezeichnete Ventilatorauswahl kann ich nicht vorlegen.'),
        ('2 Mengen und Arbeitsansatz','Für Position 01.020 setzte ich für die Gerätemontage 160 Arbeitsstunden zu einem internen Verrechnungssatz von 47,50 EUR an. Daraus ergeben sich 7.600,00 EUR. Der Ansatz umfasst das Aufstellen der drei Segmente, das Verbinden sowie das Ausrichten. Für Transport und Hebevorgang waren 3.200,00 EUR, für Anschlussmaterial 1.200,00 EUR angesetzt. Diese Beträge wurden ohne neues Nachunternehmerangebot aus vergleichbaren Aufträgen übernommen. Der Verrechnungssatz ist eine Kalkulationsgröße einschließlich lohnbezogener Nebenkosten, kein an die Stadt angebotener Stundenlohn.'),
        ('3 Geräteeinkauf und Ergebnisanteil','Den Einkauf übernahm ich mit 61.000,00 EUR aus der von Frau Winter genannten Jahreskondition. Ich habe keinen Herstellerpreis für E2 gesondert eingeholt. Frau Winter sagte nach meiner Erinnerung, wir müssten die sparsame Ausführung für den vorgegebenen Betriebspunkt vorsehen. Ob in diesem Gespräch bereits ausdrücklich die Bezeichnung E2 gefallen ist, weiß ich nicht mehr. Der verbleibende Ansatz von 5.000,00 EUR sollte Gemeinkosten und Ergebnis abdecken. Ob darin ein Mehrpreis für die passende Ventilatorausführung aufgefangen werden müsste, wurde nicht gesondert notiert.'),
        ('4 Andere Positionen und offene Frage','Regelung und Schaltschrank wurden mit 24.500,00 EUR in Position 01.120 geführt. Für Inbetriebnahme einschließlich der erforderlichen Herstellerunterstützung standen 9.200,00 EUR in Position 01.160. Diese Beträge dürfen beim Nachvollziehen nicht nochmals der Geräteposition zugeschlagen werden. Aus meiner Erinnerung kann ich die preisliche Trennung erklären. Ich kann damit keine vor Angebotsabgabe schriftlich festgelegte E2-Auswahl belegen. Frau Winter erhält den Vermerk zur Prüfung einer weiteren Vorlage; ich habe ihn nicht an die Stadt versandt.')], 'Tobias Renz, Bauleitung und Kalkulationsmitarbeit, 25.09.2026.')
    a.pdf('37_servicebeleg_weidenfeld.pdf','Auenluft Gerätebau GmbH | Service','Abrechnung des Servicetermins Weidenfeld','22.10.2024; Archivkopie vom 24.09.2026',[[
        ('1 Auftrag und Rechnung','Rechnung SV-241022-086, Rechnungsempfänger Leinetal Lufttechnik GmbH, Kundenkonto LT-041. Einsatzort Sportzentrum Weidenfeld, Göttingen. Leistungsdatum 16.10.2024. Bestellung telefonisch durch Tobias Renz am 10.10.2024, Serviceauftrag SV-241010-52. Im Archiv ist Leinetal als Kostenträger eingetragen. Ein gesonderter schriftlicher Servicevertrag ist dieser Rechnung nicht beigefügt.'),
        ('2 Abgerechnete Leistung','Servicetechniker: Daniel Eilers. Acht Stunden Parametrierung und Prüfung der geräteseitigen Sicherheitsfunktionen zu 118,00 EUR netto je Stunde ergeben 944,00 EUR. Fahrtkostenpauschale 186,00 EUR netto. Nettorechnungsbetrag 1.130,00 EUR, Umsatzsteuer 19 % in Höhe von 214,70 EUR, Rechnungsbetrag 1.344,70 EUR. Zahlungsziel war der 05.11.2024. Die Buchhaltung kennzeichnet die Rechnung als ausgeglichen am 04.11.2024; ein Kontoauszug liegt der Archivkopie nicht bei.'),
        ('3 Einsatzbemerkung','Im Serviceauftrag ist vermerkt: Gerät gestartet, Betriebsparameter gesetzt, geräteseitige Sicherheitskette ohne Störung. Luftmengenmessung und kanalnetzseitige Einregulierung erfolgen durch Leinetal. Herr Renz war anwesend. Die Übergabe der Gesamtanlage an den Generalunternehmer gehört nicht zum abgerechneten Herstellertermin. Der Servicebeleg enthält keine Unterschrift des Generalunternehmers und kein von Hersteller und Leinetal gemeinsam unterzeichnetes Inbetriebnahmeprotokoll.'),
        ('4 Archivkopie','Die Rechnungskopie mit dem zugeordneten Einsatztext wurde am 24.09.2026 auf Bitte von Frau Winter aus dem Servicearchiv ausgegeben. Die Beträge betreffen die Referenzanlage von 2024. Sie sind weder Bestandteil des Angebots Northeim noch ein Preisnachweis für das dort angebotene Gerät. Anja Beck, Serviceabrechnung.')]])
    a.eml('38_rueckfrage_referenzgeber.eml','Eva Rauch <eva.rauch@bauverbund-weidenfeld.de>','Lena Winter <angebote@leinetal-luft.de>','2026-09-24T15:46:00+02:00','Weidenfeld und Ihre Nachfrage zur Inbetriebnahme','''Sehr geehrte Frau Winter,

ich habe nach Ihrem heutigen Telefonat die Abnahmeakte nochmals angesehen. In unserem Übergabevermerk vom 18.10.2024 ist Leinetal als Ansprechpartner für die Lüftungsanlage eingetragen. Beanstandet waren fehlende Schilder an zwei Klappen. Die Anlage lief beim Termin. Der Vermerk trennt nicht zwischen mechanischer Einregulierung, Softwareparametrierung und Freigabe der Sicherheitskette. Er ist damit kein von Ihnen und dem Hersteller gemeinsam unterschriebenes Inbetriebnahmeprotokoll.

Ich bleibe bei unserer Bestätigung vom 07.09.2026. Herr Renz organisierte den Herstellertermin und war dabei. Mein damaliger Kontakt für die betriebsbereite Übergabe war Leinetal. Die heute von Ihnen erwähnte Servicerechnung war uns bisher nicht bekannt. Ich habe sie nicht geprüft und kann aus unserer eigenen Akte nicht ergänzend bestätigen, welche Verpflichtungen Sie gegenüber Auenluft übernommen hatten.

Die bei uns abgelegte Abrechnung betrifft Ihren Gesamtauftrag über 248.000 EUR netto. Eine gesonderte Kostenposition des Herstellers steht darin nicht. Dass wir Sie als Vertragspartner angesprochen haben, sagt für sich genommen noch nicht, wer welche technische Handlung ausgeführt hat. Zu diesen Handlungen bleibt der bereits beschriebene Ablauf maßgeblich.

Bitte verwenden Sie diese Nachricht zusammen mit der ursprünglichen Bestätigung. Ich möchte nicht, dass einzelne Formulierungen den Eindruck erwecken, ich bestätige eine von mir nicht beobachtete eigene Parametrierung durch Leinetal. Für eine Anfrage der Vergabekammer kann ich den Ablauf erläutern.

Mit freundlichen Grüßen
Eva Rauch
Projektleitung Bauverbund Weidenfeld GmbH''','NO26-LT038')
    a.docx('39_technischer_rechenvermerk.docx','Stadt Northeim | Fachbereich Hochbau','Nachvollzug der Gerätedaten','25.09.2026, 11:20 Uhr',[
        ('1 Auftrag und vorhandene Unterlagen','Mara Seidel bat um eine nachvollziehbare Darstellung der bereits vorliegenden Gerätedaten für die Aktenvorlage. Grundlage sind das Leistungsverzeichnis, das Angebot Leinetal sowie die Auslegung vom 08.09.2026. Der bisherige Wertungsvermerk wird damit nicht ersetzt. Neue Herstellerunterlagen oder interne Kalkulationsaufzeichnungen des Bieters liegen mir heute nicht vor.'),
        ('2 Umrechnung des Betriebspunktes','Der Luftvolumenstrom eines Strangs beträgt 6.000 m³/h. Durch Division durch 3.600 ergeben sich 1,6667 m³/s. Für E2 nennt der Hersteller für beide Ventilatoren zusammen 2,80 kW. Die Division 2,80 durch 1,6667 ergibt 1,68 kW/(m³/s). Bei E1 ergeben 3,15 kW am gleichen Betriebspunkt einen Wert von 1,89. Die im LV genannte Obergrenze beträgt 1,80. Der Nenner darf nicht nochmals verdoppelt werden; er ist nach den Vergabeunterlagen der Luftstrom eines Strangs.'),
        ('3 Gehäuse und Einbringung','Das E2-Gehäuse bleibt mit 3.150 x 1.580 x 1.760 mm unter den vorgegebenen Höchstmaßen. Das größte Segment hat nach Herstellerangabe einen Einbringquerschnitt von 1.580 x 1.720 mm. Gegenüber der Öffnung von 1.700 x 2.100 mm ergeben sich rechnerisch 120 mm in der Breite und 380 mm in der Höhe. Diese Differenzen enthalten keine Prüfung von Rangierflächen, Schutzverpackung oder Türbeschlägen. Die Vorhaltung des Wartungsgangs von 0,90 m ist bei der späteren Ausführungsplanung am Aufstellort zu kontrollieren.'),
        ('4 Grenze der technischen Aussage','Die Zahlen machen die unterschiedlichen Auswirkungen von E1 und E2 verständlich. Eine rechnerische Einhaltung der technischen Grenzwerte belegt nicht, welche Konfiguration am 31.08.2026 angeboten war. Die Herstellerangabe, dass beide Sätze dieselbe äußere Typbezeichnung haben, und die erst später dokumentierte Auswahl bleiben getrennt zu betrachten. Die Arbeitsmappe zum Nachvollzug führt deshalb keinen automatischen Zuschlagsstatus.')], 'Dipl.-Ing. Nora Brandt, Fachbereich Hochbau.')
    a.docx('40_aktenzusammenstellung.docx',a.CITY,'Zusammenstellung für die Vergabekammer','25.09.2026, 13:00 Uhr',[
        ('1 Unveränderte Ausgangsdateien','Die ursprünglichen Angebote 08, 10 und 12 und ihre Eignungserklärungen werden in der gesicherten Ablage nicht überschrieben. Die Arbeitsfassungen des Preisvergleichs werden gesondert geführt. Die sechzehn im Beleg 30 aufgeführten Dateien gehören zu dem am 24.09.2026 übermittelten Antragspaket. Spätere Arbeitsunterlagen dürfen in dessen Anlagenverzeichnis nicht nachträglich als damalige Anlagen erscheinen.'),
        ('2 Stand bei der Stadt','Die Stadt verfügt über die Unterlagen 01 bis 32 und die heute erstellten städtischen Bearbeitungsunterlagen. Eine Vollständigkeitserklärung für die noch nicht abgeschlossene Aktenvorlage wird heute nicht abgegeben. Für die Vorlage müssen die Portaldateien anhand von Kennung und Zeitstempel zugeordnet, Geheimhaltungskennzeichnungen geprüft und die Stellungnahme fertiggestellt werden. Die Schreiben und Bestätigungen 19 bis 21 bilden den Stand der bisherigen Bieteraufklärung.'),
        ('3 Noch nicht vorgelegte Unterlagen','Frau Winter hat heute telefonisch angekündigt, weitere Aufzeichnungen ihres Herstellers und zur Referenz gefunden zu haben. Dateien oder ein ergänzender Schriftsatz sind hierzu bis 13:00 Uhr weder im Verfahrensportal noch im Behördenpostfach der Stadt eingegangen. Jonas Berg vermerkt deshalb lediglich die Ankündigung. Inhalte, Entstehungszeiten und Beweiswert sind von der Stadt noch nicht überprüft. Die Gerätewahl vor Fristablauf und ein gemeinsam unterzeichnetes Inbetriebnahmeprotokoll bleiben nach unserem Aktenstand nicht belegt.'),
        ('4 Versandvorbereitung','Jonas Berg stellt die Unterlagen bis 28.09.2026, 10:00 Uhr, in einer Versandkopie zusammen. Nora Brandt liefert die technische Erläuterung; Mara Seidel verfasst die Stellungnahme. Vor Freigabe wird kontrolliert, ob zu jeder übermittelten Datei ein lesbarer Inhalt und die richtige Fassung vorliegen. Die Kammerfrist 30.09.2026, 12:00 Uhr, wird hierdurch nicht verändert. Der tatsächliche Versand ist später mit Empfangsbestätigung zu dokumentieren.')], 'Mara Seidel; aufgenommen durch Jonas Berg.')
    a.docx('41_weitergabe_belege_leinetal.docx',a.ALPHA,'Sichtung der ergänzenden Belege','25.09.2026, 11:45 Uhr',[
        ('1 Gegenwärtiger Stand','Die ergänzenden Unterlagen aus dem Herstellerkontakt und zur Referenz liegen nun bei uns vor. Sie waren dem am 24.09.2026 um 11:24:08 Uhr eingegangenen Antrag nicht beigefügt. Die ursprüngliche Anlagenliste und der Übermittlungsbeleg bleiben unverändert. Eine Nachreichung ist bis zum Zeitpunkt dieses Vermerks nicht erfolgt. Heute Vormittag habe ich gegenüber der Stadt nur angekündigt, dass wir zusätzliche Unterlagen prüfen.'),
        ('2 Inhaltlicher Abgleich','Der Konditionsauszug bestätigt den Rabatt und den daraus folgenden Grundpreis. Er bestätigt keinen projektspezifischen Preis einschließlich E2. Die Gesprächsnotiz enthält die Leistungsgrenze, aber kein ausgefülltes Auswahlfeld. Herr Renz hat heute seine Kalkulationsmitarbeit erläutert. Seine Erklärung beruht auf Erinnerung und den vorhandenen Beträgen. Sie darf nicht als Originalnotiz aus dem August bezeichnet werden. Wir halten an unserer Erklärung fest, E2 kalkuliert zu haben, müssen aber die Grenzen der neuen Unterlagen offen angeben.'),
        ('3 Referenz und Vertraulichkeit','Die Serviceabrechnung ist an uns gerichtet und weist uns als Kostenträger aus. Sie kann den bisherigen Ablauf ergänzen. Sie enthält keine gemeinsame Abnahme der Inbetriebnahme. Frau Rauchs Nachricht lässt ihre ursprüngliche Bestätigung unverändert. Vor einer etwaigen Vorlage sollen Kundennummern und die allgemeine Jahreskondition konkret bezeichnet werden, soweit wir deren vertrauliche Behandlung beantragen. Die Gerätebezeichnung, die Daten des Einsatzes und die für unseren Vortrag benötigten Beträge dürfen dabei nicht so entfernt werden, dass die Aussage nicht mehr verständlich ist.'),
        ('4 Weiteres Vorgehen','Ich werde eine ergänzende Erklärung zu Herkunft und Aussageumfang der Dateien vorbereiten. Herr Renz soll seinen Erinnerungsvermerk unverändert aufbewahren. Herr Ahrens soll keine nachträgliche Konfigurationsbestätigung mit einem Datum vor Angebotsabgabe erstellen. Ob und in welcher Fassung die Unterlagen nachgereicht werden, entscheide ich nach Durchsicht. Aus diesem internen Sichtungsvermerk folgt kein Versandauftrag.')], 'Lena Winter, Geschäftsführerin.')
    a.eml('42_interne_termine.eml','Mara Seidel <vergabe@northeim-vergabe.de>','Jonas Berg <jonas.berg@northeim-vergabe.de>; Nora Brandt <nora.brandt@northeim-vergabe.de>','2026-09-25T12:10:00+02:00','Aufgaben bis zur Aktenvorlage am 30 September','''Guten Tag Herr Berg, guten Tag Frau Brandt,

die im Schreiben der Kammer gesetzte Frist endet am 30.09.2026 um 12:00 Uhr. Bitte stellen Sie mir die Versandkopie am Montag, 28.09., bis 10:00 Uhr bereit. Dieser Montagstermin ist unsere interne Zuarbeit, keine Fristverlängerung der Kammer. Für die Prüfung der Geheimhaltungskennzeichnungen und den Abgleich der Portalereignisse plane ich bis Dienstag, 29.09., 15:00 Uhr. Eine Empfangsbestätigung für unsere Aktenvorlage gibt es noch nicht.

Frau Brandt, bitte fügen Sie Ihren heutigen Rechenvermerk zu den technischen Werten bei. Ein offener Punkt zur Geräteidentität soll auch dann als offen erkennbar bleiben, wenn die Zahlen für E2 rechnerisch passen. Herr Berg, bitte lassen Sie ursprüngliche Angebote, später eingegangene Belege und interne Bearbeitungsfassungen an ihren bisherigen Stellen erkennbar. Frau Winter hat zusätzliche Unterlagen angekündigt, uns aber bisher keine Dateien übermittelt.

Die bisherige Bindefrist endet am 30.10.2026 um 24:00 Uhr; der ausgeschriebene Ausführungsbeginn ist 02.11.2026. Für eine Änderung dieser Termine oder eine Anfrage zur Bindefristverlängerung ist bisher keine Erklärung abgegeben worden. In der Terminmappe sollen diese Daten getrennt von den Bearbeitungsterminen erscheinen. Bitte erzeugen Sie aus einem rechnerisch abgelaufenen Wartezeitraum keine Zuschlagsfreigabe. Die Kammermitteilung und die interne Sperre sind gesondert vermerkt.

Den Entwurf der Stellungnahme fertige ich. Sobald die Versandkopie geprüft ist, erhalten Sie die endgültige Dateiliste zur Gegenkontrolle. Bis dahin bleibt der Versandstatus offen.

Mara Seidel
Zentrale Vergabestelle''','NO26-INT042')
    assert baseline=={p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in CASE.iterdir() if p.name in baseline}
    print('10 Belege 33–42 erzeugt; 32 Originale unverändert.')

if __name__=='__main__':main()
