#!/usr/bin/env node
// Fallbezogene Weiterführung; Originalangebote und Originalpreisspiegel bleiben unverändert.
import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
import {loadWorkbookRuntime} from './akten-workbook-runtime.mjs';
const {Workbook,SpreadsheetFile}=await loadWorkbookRuntime();
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const dir=path.join(root,'testakten/bauwirtschaft-vergabeverfahren-feuerwehrhaus-northeim');
const qa='/tmp/bauwirtschaft-vertiefung-20261006/northeim';
const positions=JSON.parse(await fs.readFile(path.join(qa,'positions.json'),'utf8'));
const money='[$-407]#,##0.00';
const set=(s,c,v)=>s.getRange(c).values=[[v]];
const form=(s,c,v)=>s.getRange(c).formulas=[[v]];
const val=(s,c)=>s.getRange(c).values[0][0];
const near=(a,b)=>assert(Math.abs(a-b)<1e-6,`${a} != ${b}`);
function sheet(w,name,widths,rows){
 const s=w.worksheets.add(name);s.showGridLines=false;
 const end=String.fromCharCode(64+widths.length);
 s.getRange(`A1:${end}${rows}`).format={font:{name:'Times New Roman',size:11,color:'#202020'},rowHeight:20,verticalAlignment:'center'};
 widths.forEach((v,i)=>s.getRange(`${String.fromCharCode(65+i)}1:${String.fromCharCode(65+i)}${rows}`).format.columnWidthPx=v);
 s.getRange('A2').format.font={name:'Times New Roman',size:15,bold:true};return s;
}
function head(s,row,values){const end=String.fromCharCode(64+values.length);s.getRange(`A${row}:${end}${row}`).values=[values];s.getRange(`A${row}:${end}${row}`).format={fill:'#34474c',font:{name:'Times New Roman',size:11,bold:true,color:'#ffffff'},rowHeight:42,wrapText:true,horizontalAlignment:'center'};}
function line(s,r,text){set(s,`A${r}`,text);}
function input(s,r){s.getRange(r).format.fill='#fff3d6';s.getRange(r).format.font.color='#1d4f70';}
function status(s,r){s.getRange(r).conditionalFormats.add('containsText',{text:'fehlt',format:{fill:'#fce3dd',font:{color:'#9a291e'}}});s.getRange(r).conditionalFormats.add('containsText',{text:'offen',format:{fill:'#fff3d6'}});}
async function finish(w,name,views){
 w.recalculate();const scan=await w.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A|#NUM!|#NULL!|#SPILL!|#CALC!',options:{useRegex:true,maxResults:80},maxChars:6000});
 assert(!/"value"\s*:\s*"#/.test(scan.ndjson),scan.ndjson);
 await fs.writeFile(path.join(qa,name+'.errors.ndjson'),scan.ndjson);
 for(const [sheetName,range]of views){const p=await w.render({sheetName,range,scale:1.4,format:'png'});await fs.writeFile(path.join(qa,`${name}-${sheetName}.png`),new Uint8Array(await p.arrayBuffer()));}
 const x=await SpreadsheetFile.exportXlsx(w);await x.save(path.join(dir,name));
 await fs.rename(path.join(dir,name+'.inspect.ndjson'),path.join(qa,name+'.export.ndjson')).catch(()=>{});
 console.log(name);
}
{
const w=Workbook.create();
const s=sheet(w,'Preisvergleich',[90,265,80,130,130,130,140],37);
const src=sheet(w,'Angebotswerte',[90,295,70,70,135,135,135],35);
const k=sheet(w,'Kostenaufklärung',[285,145,145,150,240],29);
line(s,2,'Preisvergleich mit nachvollziehbaren Rechenschritten');line(s,3,'Nora Brandt · Stand 25.09.2026, 12:30 Uhr · Beträge in EUR netto');
head(s,5,['Bieter','Nettoangebot EUR','Preisrang','Abstand zu Leinetal EUR','Abstand zu Leinetal %','Erfasste Positionen','Rechenstatus']);
for(let j=0;j<3;j++){const r=6+j,c=String.fromCharCode(68+j),p=String.fromCharCode(69+j);set(s,`A${r}`,['Leinetal','Weserklima','Harzraum'][j]);form(s,`B${r}`,`=IF(COUNT(${c}13:${c}32)=20,SUM(${c}13:${c}32),"Preis fehlt")`);form(s,`C${r}`,`=IF(COUNT($B$6:$B$8)=3,RANK(B${r},$B$6:$B$8,1),"offen")`);form(s,`D${r}`,`=IF(AND(ISNUMBER(B${r}),ISNUMBER($B$6)),B${r}-$B$6,"offen")`);form(s,`E${r}`,`=IF(AND(ISNUMBER(D${r}),ISNUMBER($B$6),$B$6>0),D${r}/$B$6,"offen")`);form(s,`F${r}`,`=COUNT('Angebotswerte'!${p}6:${p}25)`);form(s,`G${r}`,`=IF(F${r}=20,"vollständig","Preis fehlt")`);}
s.getRange('B6:B8').setNumberFormat(money);s.getRange('D6:D8').setNumberFormat(money);s.getRange('E6:E8').setNumberFormat('[$-407]0.00%');
line(s,10,'Der Preisrang berücksichtigt nur Zahlen. Die Berücksichtigungsfähigkeit bleibt Gegenstand der Prüfung.');
head(s,12,['Position','Leistung','Menge','Leinetal GP','Weserklima GP','Harzraum GP','Weserklima minus Leinetal']);
s.getRange('A13:A32').setNumberFormat('@');
positions.forEach((p,i)=>{const r=i+13,q=i+6;set(s,`A${r}`,p[0]);set(s,`B${r}`,p[1]);form(s,`C${r}`,`='Angebotswerte'!C${q}`);for(let j=0;j<3;j++){const c=String.fromCharCode(68+j),ep=String.fromCharCode(69+j);form(s,`${c}${r}`,`=IF(AND(ISNUMBER('Angebotswerte'!C${q}),ISNUMBER('Angebotswerte'!${ep}${q})),ROUND('Angebotswerte'!C${q}*'Angebotswerte'!${ep}${q},2),"Preis fehlt")`);}form(s,`G${r}`,`=IF(AND(ISNUMBER(D${r}),ISNUMBER(E${r})),E${r}-D${r},"offen")`);});
s.getRange('A13:A32').setNumberFormat('@');s.getRange('D13:G32').setNumberFormat(money);s.getRange('B13:B32').format.wrapText=true;s.getRange('A13:G32').format.rowHeight=28;s.freezePanes.freezeRows(12);status(s,'B6:G8');status(s,'D13:G32');
line(s,34,'Rechenweg: Menge × Einheitspreis je Position, auf Cent gerundet. Die 20 Gesamtpreise ergeben die Nettosumme.');line(s,35,'Unbedingte Nachlässe betragen laut allen drei Angeboten 0 %. Es wird kein Skonto abgezogen.');line(s,36,'Quelle und Eingaben: Blatt Angebotswerte. Eine leere Preiszelle sperrt nur die betroffene Summe und die Rangfolge.');line(s,37,'Ein Preis von 0,00 EUR bleibt eine echte Zahl. Dies besagt nichts über seine vergaberechtliche Behandlung.');
line(src,2,'Übertragene Angebotswerte');line(src,3,'Quelle: 08, 10 und 12, jeweils Blatt LV, Zeilen 6–25. Mengen aus 04, Blatt LV.');head(src,5,['Position','Leistung','Menge','Einheit','Leinetal EP','Weserklima EP','Harzraum EP']);
src.getRange('A6:A25').setNumberFormat('@');
positions.forEach((p,i)=>src.getRange(`A${i+6}:G${i+6}`).values=[[p[0],p[1],p[2],p[3],p[5],p[6],p[7]]]);
src.getRange('A6:A25').setNumberFormat('@');src.getRange('E6:G25').setNumberFormat(money);src.getRange('B6:B25').format.wrapText=true;src.getRange('A6:G25').format.rowHeight=28;input(src,'C6:C25');input(src,'E6:G25');src.getRange('E6:G25').dataValidation={rule:{type:'decimal',operator:'greaterThanOrEqual',formula1:0}};src.freezePanes.freezeRows(5);
line(src,27,'Gelbe Felder sind bearbeitbare Überträge. Die eingegangenen Dateien 08, 10 und 12 bleiben unverändert.');line(src,28,'Die Einheitspreise sind in EUR netto gespeichert. Menge und Einheit müssen zusammen aus dem LV übernommen werden.');line(src,29,'Bei Korrekturen den Übertrag mit der Quelle vergleichen. Eine Bearbeitung hier ändert kein eingegangenes Angebot.');
line(src,31,'Weiterführung des Preisspiegels 23: Dort stehen bereits Gesamtpreise. Hier werden sie aus Menge und EP neu berechnet.');line(src,32,'Die historischen Mappen 04, 08, 10, 12 und 23 bleiben wegen der Übermittlungsbelege in ihrer archivierten Fassung.');line(src,33,'Das Blatt Preisvergleich erläutert Summe, Abstände und Rang. Kostenaufklärung zeigt den Betrag aus Antwort 19.');line(src,35,'Stand der Quellen: Angebotseinreichung 31.08.2026; Antwort 19 vom 09.09.2026. Keine externen Dateiverknüpfungen.');
line(k,2,'Nachvollzug Position 01.020');line(k,3,'Nora Brandt · Zahlen aus Antwort 19, Abschnitt 3 · EUR netto');
head(k,5,['Bestandteil','Ansatz EUR','Anteil am EP','Rechenart','Beleglage']);
const comps=[['Geräteeinkauf',61000,'Einkaufsansatz des Bieters'],['Transport und Hebevorgang',3200,'Erläuterung des Bieters'],['Montagepersonal',7600,'Erläuterung des Bieters'],['Anschlussmaterial',1200,'Erläuterung des Bieters'],['Gemeinkosten und Ergebnis',5000,'Erläuterung des Bieters']];
comps.forEach((r,i)=>{const n=i+6;k.getRange(`A${n}:E${n}`).values=[[r[0],r[1],null,'Übertrag aus 19',r[2]]];form(k,`C${n}`,`=IF(AND(ISNUMBER(B${n}),ISNUMBER($B$13),$B$13>0),B${n}/$B$13,"offen")`);});
set(k,'A12','Summe der Erläuterung');form(k,'B12','=IF(COUNT(B6:B10)=5,SUM(B6:B10),"Ansatz fehlt")');set(k,'A13','Angebotener Einheitspreis');set(k,'B13',78000);set(k,'A14','Differenz zur Erläuterung');form(k,'B14','=IF(AND(ISNUMBER(B12),ISNUMBER(B13)),B12-B13,"offen")');set(k,'A15','Abgleich');form(k,'B15','=IF(ISNUMBER(B14),IF(ABS(B14)<0.005,"betragsgleich","Differenz"),"Ansatz fehlt")');
k.getRange('B6:B14').setNumberFormat(money);k.getRange('C6:C10').setNumberFormat('[$-407]0.0%');k.getRange('E6:E10').format.wrapText=true;k.getRange('A6:E10').format.rowHeight=38;input(k,'B6:B10');input(k,'B13');status(k,'B12:B15');
head(k,18,['Gesonderte Leistung','Preis EUR','Quelle','Zuordnung','Abgrenzung']);k.getRange('A19:E20').values=[['Regelung und Schaltschrank',24500,'19 Abschnitt 4','Position 01.120','Nicht nochmals in 01.020 addieren.'],['Inbetriebnahme',9200,'19 Abschnitt 4','Position 01.160','Enthält Herstellerunterstützung laut Bieter.']];k.getRange('A19:E20').format.wrapText=true;k.getRange('A19:E20').format.rowHeight=48;k.getRange('B19:B20').setNumberFormat(money);
line(k,22,'Die Übereinstimmung der Beträge belegt keine Einkaufsvereinbarung und keine ursprüngliche Ventilatorauswahl.');line(k,23,'Die Stadt hat die Jahreskondition bislang nicht selbst verifiziert. Fehlende Angaben werden nicht zu 0 EUR.');line(k,25,'Eingaben: gelbe Zellen. Formeln: Summe der fünf Ansätze, Differenz zum EP sowie Anteil jedes Ansatzes am EP.');line(k,26,'Ein zusätzlicher Einkaufspreis gehört nur nach belegter Änderung in eine neue Arbeitsfassung; das Angebot bleibt erhalten.');line(k,28,'Die Trennung von Gerätepreis, Regelung und Inbetriebnahme folgt Antwort 19 und dem Leistungsverzeichnis 04.');
w.recalculate();[313600,356178,371876].forEach((x,i)=>near(val(s,`B${i+6}`),x));near(val(k,'B14'),0);set(src,'E7',178000);w.recalculate();near(val(s,'C6'),3);set(src,'E7',null);w.recalculate();assert.equal(val(s,'B6'),'Preis fehlt');set(src,'E7',0);w.recalculate();near(val(s,'B6'),235600);set(src,'E7',78000);set(k,'B6',62000);w.recalculate();near(val(k,'B14'),1000);set(k,'B6',61000);w.recalculate();
await finish(w,'43_preisvergleich_weiterfuehrung.xlsx',[['Preisvergleich','A1:G37'],['Angebotswerte','A1:G35'],['Kostenaufklärung','A1:E29']]);
}
{
const w=Workbook.create();const s=sheet(w,'Gerätewerte',[300,140,160,160,260],36);const n=sheet(w,'Nachweisstand',[210,250,200,350],26);
line(s,2,'Nachvollzug der technischen Gerätewerte');line(s,3,'Nora Brandt · 25.09.2026, 12:45 Uhr · Quelle: 03 Abschnitt 4 und 21 Abschnitte 2–4');
head(s,5,['Größe und Rechenschritt','Einheit','E1','E2','Bedeutung']);
const rows=[['Luftstrom eines Strangs','m³/h',6000,6000,'Gleicher Betriebspunkt'],['Sekunden je Stunde','s/h',3600,3600,'Umrechnungsfaktor'],['Luftstrom nach Umrechnung','m³/s',null,null,'m³/h geteilt durch 3.600'],['Gesamtleistung beider Ventilatoren','kW',3.15,2.8,'Quelle: 21, keine Einzelmotorleistung'],['SFP berechnet','kW/(m³/s)',null,null,'Gesamtleistung geteilt durch Luftstrom'],['SFP Höchstwert','kW/(m³/s)',1.8,1.8,'Quelle: 04, Position 01.020'],['Reserve bis zum Höchstwert','kW/(m³/s)',null,null,'Höchstwert minus berechneter SFP'],['Rechnerischer Vergleich','',null,null,'Keine Aussage zum Angebotsinhalt']];
rows.forEach((r,i)=>s.getRange(`A${i+6}:E${i+6}`).values=[r]);
for(const c of ['C','D']){form(s,`${c}8`,`=IF(AND(ISNUMBER(${c}6),${c}6>0,ISNUMBER(${c}7),${c}7>0),${c}6/${c}7,"Luftstrom fehlt")`);form(s,`${c}10`,`=IF(AND(ISNUMBER(${c}8),ISNUMBER(${c}9)),${c}9/${c}8,"Eingabe fehlt")`);form(s,`${c}12`,`=IF(AND(ISNUMBER(${c}10),ISNUMBER(${c}11)),${c}11-${c}10,"Eingabe fehlt")`);form(s,`${c}13`,`=IF(ISNUMBER(${c}12),IF(${c}12>=0,"Grenze eingehalten","Grenze überschritten"),"Eingabe fehlt")`);}
s.getRange('C8:D12').setNumberFormat('[$-407]0.0000');s.getRange('C6:D7').setNumberFormat('[$-407]#,##0');s.getRange('A6:E13').format.rowHeight=38;s.getRange('A6:E13').format.wrapText=true;for(const r of ['C6:D7','C9:D9','C11:D11'])input(s,r);status(s,'C8:D13');
head(s,16,['Abmessung E2','Einheit','Vorgabe','Herstellerwert','Freiraum bzw. Reserve']);
const dim=[['Gehäuselänge','mm',3200,3150],['Gehäusebreite','mm',1600,1580],['Gehäusehöhe','mm',1800,1760],['Einbringöffnung Breite / Segment','mm',1700,1580],['Einbringöffnung Höhe / Segment','mm',2100,1720],['Aufstellfläche Tragfähigkeit / Gewicht','kg',1800,1540],['Wärmerückgewinnung trocken','%',0.8,0.82]];
dim.forEach((x,i)=>{const r=i+17;s.getRange(`A${r}:D${r}`).values=[x];form(s,`E${r}`,`=IF(COUNT(C${r}:D${r})=2,${i===6?'D':'C'}${r}-${i===6?'C':'D'}${r},"Angabe fehlt")`);});s.getRange('A17:E23').format.rowHeight=38;s.getRange('A17:A23').format.wrapText=true;s.getRange('C17:E22').setNumberFormat('[$-407]#,##0');s.getRange('C23:E23').setNumberFormat('[$-407]0.0%');input(s,'C17:D23');status(s,'E17:E23');
line(s,25,'Die Reserven vergleichen ausschließlich Zahlen. Verpackung, Rangierflächen und Einbauablauf sind nicht abgebildet.');line(s,26,'Die Maße aus 03 Abschnitt 2 werden mit 21 Abschnitt 2 verglichen. Der Wartungsgang von 0,90 m bleibt zu planen.');line(s,28,'Gelbe Zellen enthalten übertragene Vorgaben und Herstellerdaten. Alle anderen Zahlenfelder sind Formeln.');line(s,29,'Ein fehlender oder nicht positiver Luftstrom ergibt keine SFP-Zahl. Eine eingetragene Leistung von 0 bleibt eine Zahl.');line(s,30,'Einheit und Nenner sind entscheidend: Die Leistung beider Ventilatoren wird durch den Luftstrom eines Strangs geteilt.');line(s,32,'Die Geräteauslegung wurde am 08.09.2026 erstellt. Sie belegt nach eigener Aussage keine Auswahl vor Angebotsabgabe.');line(s,33,'E1 und E2 werden nebeneinander aus Herstellerwerten gerechnet. Es wird keine gewertete Konfiguration ausgewählt.');line(s,35,'Nachweisstand und weitere Bearbeitung werden im zweiten Blatt geführt; der SFP-Vergleich entscheidet diese Punkte nicht.');
line(n,2,'Stand der technischen Nachweise');line(n,3,'Nora Brandt · Aktenstand bei der Stadt am 25.09.2026, 13:00 Uhr');head(n,5,['Gegenstand','Vorliegender Beleg','Arbeitsstand','Offene Angabe oder Reichweite']);
const ev=[['Hersteller und äußere Typbezeichnung','08 Angebot, B16','vorliegend','AL 6000 K; E1 und E2 sind dort nicht getrennt benannt.'],['Aktuelle technische Auslegung E2','21 vom 08.09.2026','vorliegend','Werte beziehen sich auf E2; Auswahl laut Hersteller am 07.09.2026.'],['Ursprüngliche Ventilatorauswahl','19 und 21','offen','Bieter erklärt E2; Hersteller bestätigt keine schriftliche Auswahl vor 31.08.'],['Verantwortung Referenzanlage','09, 19, 20','offen','Hersteller wirkte mit; Umfang der übernommenen Verantwortung bleibt streitig.'],['Gemeinsames Inbetriebnahmeprotokoll','32 Sachstand','offen','Ein von beiden Unternehmen unterzeichnetes Protokoll liegt weiterhin nicht vor.'],['Angekündigte neue Bieterbelege','40 Zusammenstellung Abschnitt 3','angekündigt','Bis 13:00 Uhr nicht bei der Stadt eingegangen; Inhalt nicht vorweggenommen.']];
ev.forEach((x,i)=>n.getRange(`A${i+6}:D${i+6}`).values=[x]);n.getRange('A6:D11').format.wrapText=true;n.getRange('A6:D11').format.rowHeight=70;input(n,'C6:C11');n.getRange('C6:C11').dataValidation={rule:{type:'list',values:['vorliegend','offen','angekündigt']}};status(n,'C6:C11');
set(n,'A14','Offene oder angekündigte Punkte');form(n,'C14','=COUNTIFS(C6:C11,"offen")+COUNTIFS(C6:C11,"angekündigt")');set(n,'A15','Erfasste Arbeitsstände');form(n,'C15','=COUNTA(C6:C11)');set(n,'A16','Dokumentationsstatus');form(n,'C16','=IF(C15<6,"Arbeitsstand fehlt",IF(C14>0,"Weitere Angaben offen","Alle Arbeitsstände erfasst"))');
line(n,19,'Arbeitsstände sind manuelle Dokumentationsangaben. Vorliegend bedeutet nur: Der bezeichnete Beleg ist vorhanden.');line(n,20,'Für eine Änderung des Arbeitsstands müssen Quelle und tatsächlicher Eingang nachvollziehbar sein.');line(n,21,'Offene Verantwortung und ursprüngliche Auswahl werden durch den numerischen Vergleich im ersten Blatt nicht erledigt.');line(n,23,'Neue Belege sind in einer folgenden Fassung mit Datum einzutragen. Hier ist der Stand 25.09.2026, 13:00 Uhr festgehalten.');line(n,25,'Die Zählung umfasst nur sechs konkrete Punkte und ist weder eine Eignungsbewertung noch eine Zuschlagsempfehlung.');
w.recalculate();near(val(s,'C10'),1.89);near(val(s,'D10'),1.68);near(val(n,'C14'),4);set(s,'D6',0);w.recalculate();assert.equal(val(s,'D10'),'Eingabe fehlt');set(s,'D6',6000);set(s,'D9',3);w.recalculate();assert.equal(val(s,'D13'),'Grenze eingehalten');set(s,'D9',3.001);w.recalculate();assert.equal(val(s,'D13'),'Grenze überschritten');set(s,'D9',2.8);set(n,'C8','vorliegend');w.recalculate();near(val(n,'C14'),3);assert.equal(val(n,'C16'),'Weitere Angaben offen');set(n,'C8','offen');w.recalculate();
await finish(w,'44_geraete_und_nachweise.xlsx',[['Gerätewerte','A1:E36'],['Nachweisstand','A1:D26']]);
}
{
const w=Workbook.create();const s=sheet(w,'Termine',[230,185,185,150,190,160],30);const d=sheet(w,'Unterlagen',[95,285,165,175,320],28);
line(s,2,'Termine für die Aktenvorlage');line(s,3,'Jonas Berg · Stand 25.09.2026, 14:00 Uhr MESZ · keine automatische Fortschreibung');
set(s,'A5','Kontrollzeitpunkt MESZ');set(s,'B5',new Date('2026-09-25T14:00:00Z'));s.getRange('B5').setNumberFormat('yyyy-mm-dd hh:mm');input(s,'B5');
head(s,7,['Aufgabe oder Termin','Vorgegebener Zeitpunkt','Erledigt bzw. Eingang','Rest in Kalendertagen','Bearbeitungsstatus','Quelle']);
const events=[['Aufklärungsantwort',new Date('2026-09-09T12:00:00Z'),new Date('2026-09-09T11:41:02Z'),'18, 17'],['Interne Versandkopie',new Date('2026-09-28T10:00:00Z'),null,'40 und 42'],['Interne Gegenkontrolle',new Date('2026-09-29T15:00:00Z'),null,'42'],['Aktenvorlage und Stellungnahme',new Date('2026-09-30T12:00:00Z'),null,'31'],['Ende Angebotsbindung',new Date('2026-10-31T00:00:00Z'),null,'02, 03; 30.10. 24:00'],['Ausführungsbeginn',new Date('2026-11-02T00:00:00Z'),null,'02 und 03']];
events.forEach((x,i)=>{const r=i+8;s.getRange(`A${r}:F${r}`).values=[[x[0],x[1],x[2],null,null,x[3]]];form(s,`D${r}`,`=IF(ISNUMBER(B${r}),B${r}-$B$5,"Termin fehlt")`);form(s,`E${r}`,`=IF(NOT(ISNUMBER(B${r})),"Termin fehlt",IF(C${r}="",IF(D${r}<0,"offen, Termin vorbei","offen"),IF(ISNUMBER(C${r}),IF(C${r}<=B${r},"bis Termin erfasst","nach Termin erfasst"),"Zeitangabe fehlt")))`);});s.getRange('A8:F13').format.wrapText=true;s.getRange('A8:F13').format.rowHeight=54;s.getRange('B8:C13').setNumberFormat('yyyy-mm-dd hh:mm:ss');s.getRange('D8:D13').setNumberFormat('[$-407]0.00');input(s,'B8:C13');status(s,'D8:E13');
line(s,15,'Resttage = Termin minus Kontrollzeitpunkt; Dezimalstellen bilden Tagesanteile ab. Es werden keine Arbeitstage gezählt.');line(s,16,'Leere Erledigungszellen bedeuten offen. Ein erfasster Eingang bestätigt nur den Zeitpunkt, nicht die inhaltliche Vollständigkeit.');line(s,17,'30.10.2026, 24:00 Uhr ist als 31.10.2026, 00:00 Uhr gespeichert. Maßgeblich ist jeweils die Ortszeit Northeim.');
head(s,19,['Wartezeit laut Information','Wert','Rechenweg','Quelle','Gesonderter Stand','']);
set(s,'A20','Elektronische Absendung');set(s,'B20',new Date('2026-09-14T15:00:00Z'));set(s,'C20','Tag der Absendung');set(s,'D20','17 / 25 / 26');set(s,'E20','Kammermitteilung liegt vor');
set(s,'A21','Beginn Kalendertage');form(s,'B21','=INT(B20)+1');set(s,'C21','Folgetag 00:00 Uhr');set(s,'D21','25 / 26 Abschnitt 3');
set(s,'A22','Dauer laut Information');set(s,'B22',10);set(s,'C22','Kalendertage');set(s,'D22','25 / 26 Abschnitt 3');
set(s,'A23','Rechnerischer frühester Tag');form(s,'B23','=B21+B22');set(s,'C23','Beginn plus zehn Tage');set(s,'D23','Abgleich mit 25 / 26');set(s,'E23','Keine Zuschlagsfreigabe');s.getRange('A20:F23').format.wrapText=true;s.getRange('A20:F23').format.rowHeight=38;s.getRange('B20:B21').setNumberFormat('yyyy-mm-dd hh:mm');s.getRange('B23').setNumberFormat('yyyy-mm-dd hh:mm');input(s,'B20');input(s,'B22');
line(s,25,'Die Berechnung vollzieht die in 25 und 26 genannte Wartezeit nach. Die Mitteilung 31 und Sperre 32 bleiben gesondert maßgeblich.');line(s,26,'Quellen der Berechnung: Paragraf 134 Absatz 2 GWB; https://www.gesetze-im-internet.de/gwb/__134.html');line(s,27,'Zum gesonderten Zuschlagsverbot: Paragraf 169 Absatz 1 GWB; https://www.gesetze-im-internet.de/gwb/__169.html');line(s,29,'Die Arbeitsmappe berechnet keine Rüge- oder Rechtsmittelfrist. Diese sind anhand der jeweiligen Voraussetzungen gesondert zu prüfen.');
line(d,2,'Unterlagen für die Aktenvorlage');line(d,3,'Jonas Berg · 25.09.2026, 13:00 Uhr · Quelle: 31, 32, 40 und 42');head(d,5,['Kennung','Arbeitsschritt','Verantwortlich','Arbeitsstand','Bezug und noch erforderlicher Beitrag']);
const docs=[['U01','Ursprüngliche Angebote sichern','Jonas Berg','erledigt','08–13 unverändert vorhanden; keine Neufassung einreichen.'],['U02','Portalereignisse zuordnen','Jonas Berg','offen','17 vorhanden; Kennung und Dateiliste vor Versand gegenprüfen.'],['U03','Technischen Rechenvermerk beifügen','Nora Brandt','erledigt','39 liegt seit 11:20 Uhr vor.'],['U04','Stellungnahme ausformulieren','Mara Seidel','offen','32: Schriftsatz noch nicht gefertigt.'],['U05','Geheimhaltungskennzeichnungen prüfen','Mara Seidel','offen','31 fordert konkrete Kennzeichnung.'],['U06','Versandkopie gegenkontrollieren','Jonas Berg','offen','40 und 42: nach Zusammenstellung, vor Freigabe.'],['U07','Empfangsbestätigung ablegen','Mara Seidel','offen','Versand und Eingang bislang nicht erfolgt.']];docs.forEach((x,i)=>d.getRange(`A${i+6}:E${i+6}`).values=[x]);d.getRange('A6:E12').format.wrapText=true;d.getRange('A6:E12').format.rowHeight=62;input(d,'D6:D12');d.getRange('D6:D12').dataValidation={rule:{type:'list',values:['offen','in Arbeit','erledigt']}};status(d,'D6:D12');
set(d,'A15','Offen oder in Arbeit');form(d,'C15','=COUNTIFS(D6:D12,"offen")+COUNTIFS(D6:D12,"in Arbeit")');set(d,'A16','Erfasste Arbeitsstände');form(d,'C16','=COUNTA(D6:D12)');set(d,'A17','Zusammenstellung');form(d,'C17','=IF(C16<7,"Arbeitsstand fehlt",IF(C15>0,"Arbeiten offen","Arbeiten als erledigt erfasst"))');
line(d,20,'Die gelben Arbeitsstände werden je konkretem Arbeitsschritt fortgeführt. Ein erledigter Teilpunkt schließt die übrigen nicht.');line(d,21,'Die Frist aus der Kammermitteilung steht im Blatt Termine. Diese Tabelle verlängert sie nicht und ersetzt keinen Versandbeleg.');line(d,23,'Die zusätzlich angekündigten Bieterbelege sind nach 40 bis 13:00 Uhr nicht bei der Stadt eingegangen.');line(d,24,'Ein späterer Eingang ist mit Datum und eigener Dateiliste zu dokumentieren. Das Antragspaket vom 24.09. bleibt unverändert.');line(d,26,'Die Mappen 43–45 sind interne Bearbeitungsunterlagen vom 25.09.2026; sie gehören nicht zu den sechzehn Dateien aus Beleg 30.');
w.recalculate();near(val(d,'C15'),5);assert.equal(val(s,'E8'),'bis Termin erfasst');set(d,'D7','erledigt');w.recalculate();near(val(d,'C15'),4);assert.equal(val(d,'C17'),'Arbeiten offen');set(d,'D7','offen');set(s,'B5',new Date('2026-10-01T12:00:00Z'));w.recalculate();assert.equal(val(s,'E11'),'offen, Termin vorbei');set(s,'B5',new Date('2026-09-25T14:00:00Z'));w.recalculate();
await finish(w,'45_fristen_und_aktenvorlage.xlsx',[['Termine','A1:F30'],['Unterlagen','A1:E28']]);
}
console.log('Alle eingebauten Mutationstests bestanden; Ausgangswerte wiederhergestellt.');
